#!/usr/bin/env python3
from pathlib import Path
import re
import sys

path = Path(__file__).resolve().parents[2] / "web/src/views/assets/DatabaseWorkbench.vue"
text = path.read_text(encoding="utf-8")
replacements = [
    ("environment.includes('生产')", "environment.includes('\\u751f\\u4ea7')"),
    ("PostgreSQL 将在当前连接数据库中创建 Schema，创建后会立即显示在左侧结构树。", "현재 연결된 PostgreSQL Database에 Schema를 생성합니다. 생성 후 왼쪽 Structure Tree에 즉시 표시됩니다."),
    ("将直接在当前 MySQL 实例中创建数据库，创建后会立即显示在左侧结构树。", "현재 MySQL Instance에 Database를 직접 생성합니다. 생성 후 왼쪽 Structure Tree에 즉시 표시됩니다."),
    ("高可信度：基于主键和操作前数据生成，执行前仍需复核。", "높은 신뢰도: Primary Key와 변경 전 Data를 기준으로 생성했습니다. 실행 전에도 반드시 검토하십시오."),
    ("该回滚 SQL 可信度有限，请人工核对后使用。", "이 Rollback SQL은 신뢰도가 제한적입니다. 수동 검토 후 사용하십시오."),
    ("支持语法高亮、关键字/库表字段补全、常用语句模板和快捷执行。", "Syntax Highlighting, Keyword 및 Database/Table Column 자동완성, 자주 쓰는 Query Template과 Quick Execution을 지원합니다."),
    ("支持常用 Redis 读取与变更命令，变更操作需二次确认并写入执行记录。", "일반적인 Redis Read/Write Command를 지원합니다. Write 작업은 재확인 후 Execution History에 기록됩니다."),
    ("当前类型支持连接检测和资源结构浏览；文档、键值和数据编辑能力将按类型逐步开放。", "현재 Type은 Connection Test와 Resource Structure 탐색을 지원합니다. Document, Key-Value 및 Data 편집 기능은 Type별로 단계적으로 제공합니다."),
    ("`Ctrl + Enter` 可执行当前选中 SQL；格式化与收藏仅作用于选中 SQL，未选中时作用于全部内容。", "`Ctrl + Enter`로 선택한 SQL을 실행합니다. Format과 Favorite는 선택한 SQL에만 적용되며 선택 영역이 없으면 전체 내용에 적용됩니다."),
    ("读取命令可直接执行，写入命令需确认；高危管理命令已禁用。", "Read Command는 즉시 실행할 수 있고 Write Command는 확인이 필요합니다. 고위험 관리 Command는 비활성화되어 있습니다."),
    ("支持带引号参数。按 Ctrl + Enter 执行，执行记录会保留在下方历史中。", "Quote가 포함된 Parameter를 지원합니다. Ctrl + Enter로 실행하며 기록은 아래 History에 보존됩니다."),
    ("可在左侧选择数据库、库与资源查看结构；MySQL 保留完整的数据编辑、导入导出与备份能力。", "왼쪽에서 Database와 Resource를 선택해 Structure를 확인할 수 있습니다. MySQL은 전체 Data 편집, Import/Export 및 Backup 기능을 제공합니다."),
    ("可按字段筛选 MongoDB 文档；下方会展示集合索引摘要。", "Column 기준으로 MongoDB Document를 Filter할 수 있으며 아래에 Collection Index 요약을 표시합니다."),
    ("支持新增、编辑和删除 Redis Key；所有写入操作均需确认并记录审计。", "Redis Key 추가, 수정, 삭제를 지원합니다. 모든 Write 작업은 확인 후 Audit에 기록됩니다."),
    ("展示 Redis Key 的类型、TTL 与值摘要，不会直接修改 Key。", "Redis Key의 Type, TTL 및 Value 요약을 표시하며 Key를 직접 변경하지 않습니다."),
    ("PostgreSQL 表数据支持分页与字段筛选；执行计划可直接在 SQL 编辑器中使用 EXPLAIN ANALYZE。", "PostgreSQL Table Data는 Pagination과 Column Filter를 지원합니다. SQL Editor에서 EXPLAIN ANALYZE로 Execution Plan을 확인할 수 있습니다."),
    ("请确认目标环境、数据库和 SQL 内容无误。写操作可能无法自动恢复。", "Target Environment, Database 및 SQL 내용을 확인하십시오. Write 작업은 자동 복구되지 않을 수 있습니다."),
    ("写入 Redis 将立即生效，并写入执行审计记录", "Redis Write는 즉시 적용되며 Execution Audit에 기록됩니다."),
    ("以字母或下划线开头，仅支持字母、数字和下划线。", "Letter 또는 underscore로 시작해야 하며 letter, number, underscore만 사용할 수 있습니다."),
    ("留空表示不修改 TTL；-1 表示永不过期。", "비워두면 TTL을 변경하지 않습니다. -1은 만료 없음입니다."),
    ("字段映射：{{ importPrecheck.commonColumns?.length || 0 }} 个，缺失字段：{{ importPrecheck.missingColumns?.length || 0 }} 个", "Column Mapping: {{ importPrecheck.commonColumns?.length || 0 }}개, 누락 Column: {{ importPrecheck.missingColumns?.length || 0 }}개"),
    ("当前 Redis 连接支持直接管理 Key", "현재 Redis Connection은 Key 직접 관리를 지원합니다."),
    ("当前资源以只读方式浏览", "현재 Resource는 Read-only로 탐색합니다."),
    ("为这条 SQL 设置名称，后续可一键填入编辑器。", "이 SQL의 이름을 지정하면 이후 Editor에 바로 불러올 수 있습니다."),
    ("选择连接后可浏览对象、执行语句与查看结果", "Connection을 선택하면 Object 탐색, Statement 실행 및 결과 확인이 가능합니다."),
    ("先从左侧选中一张表，或直接执行 SQL 查看结果。", "왼쪽에서 Table을 선택하거나 SQL을 직접 실행해 결과를 확인하십시오."),
    ("当前数据库为只读模式，后端将拒绝执行该 SQL", "현재 Database는 Read-only Mode이므로 Backend가 이 SQL 실행을 거부합니다."),
    ("复杂类型的值必须填写合法 JSON", "Complex Type Value는 유효한 JSON이어야 합니다."),
    ("Hash 值必须是 JSON 对象", "Hash Value는 JSON Object여야 합니다."),
    ("Hash 至少需要一个字段", "Hash에는 하나 이상의 Field가 필요합니다."),
    ("有序集合值必须是非空 JSON 数组", "Sorted Set Value는 비어 있지 않은 JSON Array여야 합니다."),
    ("有序集合元素必须包含 member 和 score", "Sorted Set Element에는 member와 score가 필요합니다."),
    ("List 或 Set 值必须是非空 JSON 数组", "List 또는 Set Value는 비어 있지 않은 JSON Array여야 합니다."),
    ("TTL 只能设置为 -1 或非负整数秒", "TTL은 -1 또는 0 이상의 정수 초로 설정해야 합니다."),
    ("Stream 类型暂不支持可视化编辑，请使用上方 Redis 命令控制台", "Stream Type은 아직 Visual Editing을 지원하지 않습니다. 위 Redis Command Console을 사용하십시오."),
    ("当前数据库类型不使用 SQL 工作台，请通过左侧资源树查看连接与结构信息", "현재 Database Type은 SQL Workbench를 사용하지 않습니다. 왼쪽 Resource Tree에서 Connection과 Structure를 확인하십시오."),
    ("当前数据库类型已支持连接和结构浏览，数据编辑功能将在后续版本提供", "현재 Database Type은 Connection과 Structure 탐색을 지원합니다. Data 편집은 추후 Version에서 제공합니다."),
    ("该数据库当前未连接，请先检查连接配置", "현재 Database가 연결되지 않았습니다. Connection 설정을 확인하십시오."),
    ("当前没有可导出的 SQL 结果", "Export할 SQL 결과가 없습니다."),
    ("当前数据库为只读模式", "현재 Database는 Read-only Mode입니다."),
    ("当前表没有主键，不能直接编辑", "현재 Table에 Primary Key가 없어 직접 편집할 수 없습니다."),
    ("Schema ${node.name} 暂无可浏览的数据表", "Schema ${node.name}에 탐색 가능한 Table이 없습니다."),
    ("请输入需要格式化的 SQL", "Format할 SQL을 입력하십시오."),
    ("请输入需要收藏的 SQL", "Favorite에 저장할 SQL을 입력하십시오."),
    ("请输入收藏名称", "Favorite 이름을 입력하십시오."),
    ("请输入字符串值", "String Value를 입력하십시오."),
    ("请输入要执行的 SQL", "실행할 SQL을 입력하십시오."),
    ("请输入 Redis 命令", "Redis Command를 입력하십시오."),
    ("请输入 Key 名称", "Key 이름을 입력하십시오."),
    ("请输入${createDatabaseObjectLabel.value}名称", "${createDatabaseObjectLabel.value} 이름을 입력하십시오."),
    ("请输入“${sqlConfirmationText()}”以确认执行", "실행을 확인하려면 “${sqlConfirmationText()}”을(를) 입력하십시오."),
    ("请输入 SQL，支持执行选中的语句。", "SQL을 입력하십시오. 선택한 Statement를 실행할 수 있습니다."),
    ("输入筛选值，支持模糊匹配", "Filter Value 입력, Fuzzy Match 지원"),
    ("请先选择要导出的表", "Export할 Table을 먼저 선택하십시오."),
    ("请先选择当前工作台目标表", "현재 Workbench의 Target Table을 먼저 선택하십시오."),
    ("请先完成导入预检查", "Import Precheck를 먼저 완료하십시오."),
    ("请完整选择源库、源表和目标表", "Source Database, Source Table 및 Target Table을 모두 선택하십시오."),
    ("SQL 已格式化", "SQL Format을 완료했습니다."),
    ("SQL 已收藏", "SQL을 Favorite에 저장했습니다."),
    ("单元格已更新", "Cell을 업데이트했습니다."),
    ("SQL 执行完成", "SQL 실행을 완료했습니다."),
    ("Redis 命令执行完成", "Redis Command 실행을 완료했습니다."),
    ("Redis Key 已删除", "Redis Key를 삭제했습니다."),
    ("回滚 SQL 已复制", "Rollback SQL을 복사했습니다."),
    ("导出任务已创建", "Export Task를 생성했습니다."),
    ("导入任务已创建", "Import Task를 생성했습니다."),
    ("新增成功", "추가했습니다."),
    ("更新成功", "업데이트했습니다."),
    ("删除成功", "삭제했습니다."),
    ("不支持的 Redis Key 类型", "지원하지 않는 Redis Key Type입니다."),
    ("Key 内容不正确", "Key 내용이 올바르지 않습니다."),
    ("删除 Redis Key", "Redis Key 삭제"),
    ("新增表数据", "Table Data 추가"),
    ("更新表数据", "Table Data 업데이트"),
    ("删除表数据行", "Table Data Row 삭제"),
    ("Redis 写命令：", "Redis Write Command: "),
    ("收藏 SQL", "SQL Favorite"),
    ("例如：查询近 24 小时订单", "예: 최근 24시간 Order 조회"),
    ("例如：GET key、HGETALL hash_key 或 SET key value", "예: GET key, HGETALL hash_key 또는 SET key value"),
    ("例如：ops_reporting", "예: ops_reporting"),
    ("例如：app:config", "예: app:config"),
    ("数据库工作台", "Database Workbench"),
    ("数据库连接", "Database Connection"),
    ("点击连接即可切换", "Connection을 클릭해 전환"),
    ("库表结构", "Database / Table Structure"),
    ("全部数据库", "전체 Database"),
    ("搜索数据库或数据表", "Database 또는 Table 검색"),
    ("上一页", "이전 Page"),
    ("下一页", "다음 Page"),
    ("SQL 编辑器", "SQL Editor"),
    ("Redis 命令控制台", "Redis Command Console"),
    ("数据库'} 资源浏览", "Database'} Resource Explorer"),
    ("执行 SQL", "SQL 실행"),
    ("格式化", "Format"),
    ("已收藏", "Favorite"),
    ("执行 Redis 命令", "Redis Command 실행"),
    ("导出任务", "Export Task"),
    ("导入任务", "Import Task"),
    ("工作区", "Workspace"),
    ("新增 Key", "Key 추가"),
    ("新增数据", "Data 추가"),
    ("刷新数据", "Data 새로고침"),
    ("表数据", "Table Data"),
    ("筛选字段", "Filter Column"),
    ("集合索引", "Collection Index"),
    ("SQL 结果", "SQL 결과"),
    ("筛选结果集", "Result Set Filter"),
    ("导出 CSV", "CSV Export"),
    ("执行记录", "Execution History"),
    ("执行编号", "Execution ID"),
    ("SQL 类型", "SQL Type"),
    ("影响行数", "Affected Rows"),
    ("耗时(ms)", "Duration (ms)"),
    ("执行人", "Operator"),
    ("客户端 IP", "Client IP"),
    ("执行时间", "Executed At"),
    ("回滚 SQL", "Rollback SQL"),
    ("高可信", "높은 신뢰도"),
    ("需复核", "검토 필요"),
    ("复用", "재사용"),
    ("导入导出任务", "Import / Export Task"),
    ("创建时间", "Created At"),
    ("确认执行写操作 SQL", "SQL Write 실행 확인"),
    ("高风险", "High Risk"),
    ("中风险", "Medium Risk"),
    ("低风险", "Low Risk"),
    ("未分配环境", "Environment 미지정"),
    ("语句数量", "Statement 수"),
    ("访问模式", "Access Mode"),
    ("只读连接", "Read-only Connection"),
    ("可写连接", "Writable Connection"),
    ("只读", "Read-only"),
    ("读写", "Read / Write"),
    ("确认执行", "실행 확인"),
    ("生产环境", "운영 환경"),
    ("新增 Redis Key", "Redis Key 추가"),
    ("编辑 Redis Key", "Redis Key 수정"),
    ("Key 名称", "Key 이름"),
    ("数据类型", "Data Type"),
    ("TTL（秒）", "TTL (초)"),
    ("确认保存", "저장 확인"),
    ("新增数据行", "Data Row 추가"),
    ("编辑数据行", "Data Row 수정"),
    ("当前记录没有回滚 SQL", "현재 Record에는 Rollback SQL이 없습니다."),
    ("创建导入任务", "Import Task 생성"),
    ("源数据库", "Source Database"),
    ("源库", "Source Database"),
    ("源表", "Source Table"),
    ("目标库表", "Target Table"),
    ("自动建表", "Table 자동 생성"),
    ("清空目标表", "Target Table 비우기"),
    ("预检查通过", "Precheck 통과"),
    ("预检查未通过", "Precheck 실패"),
    ("预检查", "Precheck"),
    ("检查字段与影响范围", "Column 및 영향 범위 검사"),
    ("缺失：", "누락: "),
    ("开始导入", "Import 시작"),
    ("新增${createDatabaseObjectLabel}", "${createDatabaseObjectLabel} 추가"),
    ("${createDatabaseObjectLabel}名称", "${createDatabaseObjectLabel} 이름"),
    ("字符集", "Character Set"),
    ("排序规则", "Collation"),
    ("确认创建", "생성 확인"),
    ("查看表", "Table 보기"),
    ("状态", "상태"),
    ("成功", "성공"),
    ("失败", "실패"),
    ("执行中", "실행 중"),
    ("等待中", "대기 중"),
    ("类型", "Type"),
    ("环境", "Environment"),
    ("进度", "진행률"),
    ("行数", "Row 수"),
    ("说明", "설명"),
    ("操作", "작업"),
    ("下载", "Download"),
    ("目标", "Target"),
    ("源", "Source"),
    ("库", "Database"),
    ("表", "Table"),
    ("值", "Value"),
    ("刷新", "새로고침"),
    ("查看", "보기"),
    ("复制", "복사"),
    ("编辑", "수정"),
    ("删除", "삭제"),
    ("新增", "추가"),
    ("更新", "업데이트"),
    ("保存", "저장"),
    ("取消", "취소"),
    ("名称", "이름"),
    ("个", "개"),
    ("行", "행"),
]
for old, new in replacements:
    text = text.replace(old, new)
path.write_text(text, encoding="utf-8")
remaining = [(n, line) for n, line in enumerate(text.splitlines(), 1) if re.search(r'[\u3400-\u4DBF\u4E00-\u9FFF]', line)]
print(f"web batch11 left {len(remaining)} Han line(s)")
for n, line in remaining[:60]:
    print(f"REMAINING: {n}: {line.strip()}", file=sys.stderr)
raise SystemExit(1 if remaining else 0)
