#!/usr/bin/env python3
from __future__ import annotations

from pathlib import Path
import re
import sys

ROOT = Path(__file__).resolve().parents[2]
PATH = ROOT / "backend/service/monitor.go"
HAN = re.compile(r"[\u3400-\u4DBF\u4E00-\u9FFF]")

REPLACEMENTS = [
    ('JSON 格式不正确', 'invalid JSON format'),
    ('数据源名称不能为空', 'datasource name is required'),
    ('数据源地址不能为空', 'datasource URL is required'),
    ('数据源已被告警规则引用，不能删除', 'datasource is referenced by alert rules and cannot be deleted'),
    ('数据源已被监控大屏引用，不能删除', 'datasource is referenced by monitoring dashboards and cannot be deleted'),
    ('数据源已被 K8s 集群监控绑定，不能删除', 'datasource is bound to Kubernetes cluster monitoring and cannot be deleted'),
    ('查询语句不能为空', 'query is required'),
    ('图表查询仅支持 Prometheus 或 VictoriaMetrics 数据源', 'chart queries support only Prometheus or VictoriaMetrics datasources'),
    ('VictoriaLogs 请在日志查询中使用 LogsQL', 'use LogsQL in Log Explorer for VictoriaLogs'),
    ('Prometheus API 返回状态码 %d: %s', 'Prometheus API returned status %d: %s'),
    ('查询结束时间必须晚于开始时间', 'query end time must be later than start time'),
    ('Elasticsearch 健康检查失败，状态码 %d: %s', 'Elasticsearch health check failed with status %d: %s'),
    ('Jaeger 健康检查失败，状态码 %d: %s', 'Jaeger health check failed with status %d: %s'),
    ('当前数据源不是 Jaeger', 'current datasource is not Jaeger'),
    ('请选择 Jaeger 数据源', 'select a Jaeger datasource'),
    ('请选择服务', 'select a service'),
    ('链路追踪仅支持 Jaeger 数据源', 'trace queries support only Jaeger datasources'),
    ('标签筛选必须是 JSON 对象', 'tag filter must be a JSON object'),
    ('请填写数据源和 Trace ID', 'datasource and Trace ID are required'),
    ('Trace ID 格式无效', 'invalid Trace ID format'),
    ('未找到该 Trace', 'trace was not found'),
    ('Jaeger API 返回状态码 %d: %s', 'Jaeger API returned status %d: %s'),
    ('Jaeger 查询失败: %v', 'Jaeger query failed: %v'),
    ('Jaeger API 未返回数据', 'Jaeger API returned no data'),
    ('Elasticsearch DSL 必须是有效的 JSON 对象', 'Elasticsearch DSL must be a valid JSON object'),
    ('Elasticsearch 索引不能包含路径分隔符', 'Elasticsearch index must not contain path separators'),
    ('Elasticsearch 查询失败，状态码 %d: %s', 'Elasticsearch query failed with status %d: %s'),
    ('请选择日志数据源', 'select a log datasource'),
    ('日志查询仅支持 Elasticsearch 或 VictoriaLogs 数据源', 'log queries support only Elasticsearch or VictoriaLogs datasources'),
    ('请选择 Elasticsearch 数据源', 'select an Elasticsearch datasource'),
    ('日志查询仅支持 Elasticsearch 数据源', 'log query supports only Elasticsearch datasources'),
    ('索引不能包含路径分隔符', 'index must not contain path separators'),
    ('VictoriaLogs 健康检查失败，状态码 %d: %s', 'VictoriaLogs health check failed with status %d: %s'),
    ('VictoriaLogs 查询失败，状态码 %d: %s', 'VictoriaLogs query failed with status %d: %s'),
    ('解析 VictoriaLogs 返回记录失败: %w', 'failed to parse VictoriaLogs records: %w'),
    ('请选择 VictoriaLogs 数据源', 'select a VictoriaLogs datasource'),
    ('当前数据源不是 VictoriaLogs', 'current datasource is not VictoriaLogs'),
    ('获取 VictoriaLogs Stream 失败，状态码 %d: %s', 'failed to retrieve VictoriaLogs streams; status %d: %s'),
    ('日志字段仅支持 Elasticsearch 或 VictoriaLogs 数据源', 'log fields support only Elasticsearch or VictoriaLogs datasources'),
    ('不支持的日志筛选字段', 'unsupported log filter field'),
    ('获取 Elasticsearch 字段失败，状态码 %d: %s', 'failed to retrieve Elasticsearch fields; status %d: %s'),
    ('获取 VictoriaLogs 字段失败，状态码 %d: %s', 'failed to retrieve VictoriaLogs fields; status %d: %s'),
    ('当前数据源不是 Elasticsearch', 'current datasource is not Elasticsearch'),
    ('获取 Elasticsearch 索引失败，状态码 %d: %s', 'failed to retrieve Elasticsearch indices; status %d: %s'),
    ('全部日志', 'All Logs'),
    ('错误日志', 'Error Logs'),
    ('异常与堆栈', 'Exceptions and Stack Traces'),
    ('告警与警告', 'Alerts and Warnings'),
    ('超时请求', 'Timed-out Requests'),
    ('连接失败', 'Connection Failures'),
    ('Kubernetes 重启', 'Kubernetes Restarts'),
    ('应用启动', 'Application Startup'),
    ('数据库慢查询', 'Database Slow Queries'),
    ('指定命名空间', 'Specific Namespace'),
    ('快捷语句名称不能为空', 'saved query name is required'),
    ('请选择快捷语句', 'select a saved query'),
    ('快捷语句不存在或无权删除', 'saved query does not exist or cannot be deleted by the current user'),
    ('Kafka 错误主题', 'Kafka Error Topic'),
    ('Prometheus YAML 解析失败：%w', 'failed to parse Prometheus YAML: %w'),
    ('未发现 groups；请选择 Prometheus Rule YAML 文件', 'no groups were found; select a Prometheus rule YAML file'),
    ('规则组 %s 的 interval 无效：%w', 'invalid interval for rule group %s: %w'),
    ('规则 %s 缺少 expr', 'rule %s is missing expr'),
    ('规则 %s 的 for 无效：%w', 'invalid for duration for rule %s: %w'),
    ('文件中没有 alert 规则；recording rule 不会导入为告警模板', 'the file contains no alert rules; recording rules are not imported as alert templates'),
    ('请选择目标模板分组', 'select a target template group'),
    ('请选择至少一条 Prometheus 告警规则', 'select at least one Prometheus alert rule'),
    ('单次最多导入 500 条告警规则', 'at most 500 alert rules can be imported at once'),
    ('导入项的名称和查询语句不能为空', 'imported item name and query are required'),
    ('%s（导入 %d）', '%s (Import %d)'),
    ('规则 %s 的标签或注解不是有效 JSON', 'labels or annotations for rule %s are not valid JSON'),
    ('请选择至少一条告警模板', 'select at least one alert template'),
    ('单次最多导出 500 条告警模板', 'at most 500 alert templates can be exported at once'),
    ('部分告警模板不存在或已被删除', 'some alert templates do not exist or were deleted'),
    ('模板「%s」不是 Prometheus/VictoriaMetrics 类型，不能导出为 Prometheus Rule YAML', 'template %q is not Prometheus or VictoriaMetrics and cannot be exported as Prometheus rule YAML'),
    ('# Exported by Ops Admin alert template library.\\n# Paste this content into: 告警模板 > 粘贴 Prometheus 模板。\\n\\n', '# Exported by Ops Admin alert template library.\\n# Paste this content into Alert Templates > Paste Prometheus Template.\\n\\n'),
    ('规则名称不能为空', 'rule name is required'),
    ('Elasticsearch 查询语句不能为空', 'Elasticsearch query is required'),
    ('PromQL 不能为空', 'PromQL is required'),
    ('请选择数据源', 'select a datasource'),
    ('日志告警只能选择 Elasticsearch 数据源', 'log alerts require an Elasticsearch datasource'),
    ('日志告警只能选择 VictoriaLogs 数据源', 'VictoriaLogs alerts require a VictoriaLogs datasource'),
    ('监控告警只能选择 Prometheus 或 VictoriaMetrics 数据源', 'metric alerts require a Prometheus or VictoriaMetrics datasource'),
    ('全部日志数据源', 'All Log Datasources'),
    ('全部 VictoriaLogs 数据源', 'All VictoriaLogs Datasources'),
    ('全部监控数据源', 'All Metric Datasources'),
    ('没有可用的匹配数据源', 'no matching datasource is available'),
    ('告警规则已停用，系统自动关闭未结束事件', 'alert rule disabled; open events were closed automatically'),
    ('结束时间必须晚于开始时间', 'end time must be later than start time'),
    ('规则名正则不能为空', 'rule-name regular expression is required'),
    ('屏蔽规则名称不能为空', 'silence rule name is required'),
    ('请选择至少一条规则', 'select at least one rule'),
    ('不支持的批量操作', 'unsupported batch operation'),
    ('告警规则已停用，事件自动关闭', 'alert rule disabled; event closed automatically'),
    ('系统', 'System'),
    ('请选择至少一条告警规则', 'select at least one alert rule'),
    ('告警规则不能为空', 'alert rule is required'),
    ('请填写持续时间', 'duration is required'),
    ('持续时间需在 0 到 86400 秒之间', 'duration must be between 0 and 86400 seconds'),
    ('所选规则中没有可修改持续时间的监控告警规则', 'none of the selected metric alert rules support duration updates'),
    ('请填写评估间隔', 'evaluation interval is required'),
    ('评估间隔需在 15 到 3600 秒之间', 'evaluation interval must be between 15 and 3600 seconds'),
    ('请选择通知规则', 'select a notification rule'),
    ('请填写重复通知间隔', 'repeat-notification interval is required'),
    ('重复通知间隔需在 1 分钟到 7 天之间', 'repeat-notification interval must be between one minute and seven days'),
    ('请填写最大发送次数', 'maximum send count is required'),
    ('最大发送次数需在 0 到 1000 之间', 'maximum send count must be between 0 and 1000'),
    ('请设置是否发送恢复通知', 'configure whether recovery notifications are sent'),
    ('通知规则不存在或已禁用', 'notification rule does not exist or is disabled'),
    ('告警规则已批量停用，系统自动关闭未结束事件', 'alert rules disabled in batch; open events were closed automatically'),
    ('规则预览', 'Rule Preview'),
    ('共查询 %d 个数据源，返回 %d 条序列，其中 %d 条满足 %s %.4f', 'queried %d datasources and returned %d series; %d matched %s %.4f'),
    ('，%d 个数据源查询失败', '; %d datasource queries failed'),
    ('全部匹配数据源评估失败', 'evaluation failed for all matching datasources'),
    ('命中 %d 条序列，%d 个数据源失败', '%d series matched; %d datasources failed'),
    ('VictoriaLogs 日志告警查询失败，状态码 %d: %s', 'VictoriaLogs alert query failed with status %d: %s'),
    ('VictoriaLogs 日志告警结果解析失败: %w', 'failed to parse VictoriaLogs alert result: %w'),
    ('已提交消息通知', 'notification submitted'),
    ('状态：%s，第 %d 次发送', 'status: %s; send attempt %d'),
    ('已发送聚合告警通知', 'aggregated alert notification sent'),
    ('聚合规则：%s，本批共 %d 条告警', 'aggregation rule: %s; %d alerts in this batch'),
    ('【聚合告警】%s：%d 条同类告警', '[Aggregated Alert] %s: %d related alerts'),
    ('聚合规则：%s\\n收敛窗口：%d 秒\\n命中数量：%d\\n样本标签：\\n%s', 'Aggregation Rule: %s\\nWindow: %d seconds\\nMatched: %d\\nSample Labels:\\n%s'),
    ('（聚合）', ' (Aggregated)'),
    ('%s 当前值 %.4f %s %.4f', '%s current value %.4f %s %.4f'),
    ('屏蔽已结束，告警仍在触发', 'silence ended while alert is still firing'),
    ('告警正式触发', 'alert entered firing state'),
    ('命中告警屏蔽', 'alert matched a silence rule'),
    ('命中聚合收敛规则', 'alert matched an aggregation rule'),
    ('告警事件已创建', 'alert event created'),
    ('等待持续时间', 'waiting for duration threshold'),
    ('告警已被屏蔽', 'alert silenced'),
    ('等待持续已取消', 'duration wait cancelled'),
    ('告警条件已恢复，未达到持续时间，不发送恢复通知', 'alert condition recovered before duration threshold; no recovery notification sent'),
    ('告警已自动恢复', 'alert recovered automatically'),
    ('指标已不再满足告警条件', 'metric no longer matches the alert condition'),
    ('【聚合恢复】%s：同组告警已全部恢复', '[Aggregated Recovery] %s: all alerts in the group recovered'),
    ('已发送聚合恢复通知', 'aggregated recovery notification sent'),
    ('同一聚合分组内的告警均已恢复', 'all alerts in the aggregation group recovered'),
    ('告警已认领', 'alert claimed'),
    ('告警已人工关闭', 'alert closed manually'),
    ('当前允许发送', 'send is currently allowed'),
    ('告警已结束，无需继续通知', 'alert has ended; no further notification is required'),
    ('命中屏蔽规则：', 'matched silence rule: '),
    ('未命名规则', 'Unnamed Rule'),
    ('已达到最大发送次数', 'maximum send count reached'),
    ('等待重复通知间隔', 'waiting for repeat-notification interval'),
    ('告警事件 ID 不能为空', 'alert event ID is required'),
    ('操作人', 'Operator'),
    ('所选事件没有可认领的等待持续或触发中告警', 'selected events contain no pending-duration or firing alerts that can be claimed'),
    ('所选事件没有可关闭的未结束告警', 'selected events contain no open alerts that can be closed'),
    ('告警已批量认领', 'alerts claimed in batch'),
    ('告警已批量关闭', 'alerts closed in batch'),
    ('告警已恢复', 'alert recovered'),
    ('数据源健康检查异常', 'datasource health check failed'),
    ('通知发送失败', 'notification delivery failed'),
    ('规则执行失败', 'rule execution failed'),
    ("COALESCE(NULLIF(region, ''), '未分配区域')", "COALESCE(NULLIF(region, ''), 'Unassigned Region')"),
    ("COALESCE(NULLIF(rule_name, ''), '未命名规则')", "COALESCE(NULLIF(rule_name, ''), 'Unnamed Rule')"),
    ('物理/云主机', 'Physical / Cloud Hosts'),
    ('Kubernetes 集群', 'Kubernetes Clusters'),
    ('数据库', 'Databases'),
    ('服务', 'Services'),
    ('日志数据源不支持 PromQL 监控面板，请选择 Prometheus 或 VictoriaMetrics', 'log datasources do not support PromQL monitoring panels; select Prometheus or VictoriaMetrics'),
    ('监控面板仅支持 Prometheus 或 VictoriaMetrics，请先配置指标数据源', 'monitoring panels support only Prometheus or VictoriaMetrics; configure a metric datasource first'),
]


def main() -> int:
    text = PATH.read_text(encoding="utf-8")
    count = 0
    for old, new in REPLACEMENTS:
        hits = text.count(old)
        if hits:
            text = text.replace(old, new)
            count += hits
    PATH.write_text(text, encoding="utf-8")
    remaining = [(n, line) for n, line in enumerate(text.splitlines(), 1) if HAN.search(line)]
    print(f"batch9 localized {count} occurrence(s); {len(remaining)} Han line(s) remain")
    for n, line in remaining[:40]:
        print(f"REMAINING: {n}: {line.strip()}", file=sys.stderr)
    return 1 if remaining else 0


if __name__ == "__main__":
    raise SystemExit(main())
