#!/usr/bin/env python3
from pathlib import Path
import re
import sys

path = Path(__file__).resolve().parents[2] / "web/src/views/monitor/MonitorDashboard.vue"
text = path.read_text(encoding="utf-8")
replacements = [
    ("以巡检清单方式核查 PromQL 面板状态，并支持导出巡检报告 PDF。", "Inspection Checklist 방식으로 PromQL Panel 상태를 점검하고 Inspection Report PDF Export를 지원합니다."),
    ("以网格大屏方式展示指标卡、趋势、排行和仪表盘，适合投屏观测。", "Grid Dashboard 방식으로 Metric Card, Trend, Ranking, Gauge를 표시하며 대형 화면 관제에 적합합니다."),
    ("创建一个空白大屏，手动添加 PromQL 面板。", "빈 Dashboard를 생성하고 PromQL Panel을 직접 추가합니다."),
    ("参考 Node Exporter 大屏，覆盖在线状态、CPU、内存、磁盘、网络和系统负载。", "Node Exporter Dashboard를 기준으로 Online 상태, CPU, Memory, Disk, Network, System Load를 표시합니다."),
    ("参考 K8S Dashboard 大屏风格，覆盖集群资源、容量、工作负载和网络指标。", "Kubernetes Dashboard 스타일로 Cluster Resource, Capacity, Workload, Network Metric을 표시합니다."),
    ("浏览器阻止了报告窗口，请允许弹窗后重试", "Browser가 Report Window를 차단했습니다. Popup을 허용한 뒤 다시 시도하십시오."),
    ("请先创建 Prometheus 数据源，再使用模板创建大屏", "Prometheus Datasource를 먼저 생성한 뒤 Template으로 Dashboard를 생성하십시오."),
    ("请先创建或选择监控大屏", "Monitoring Dashboard를 생성하거나 선택하십시오."),
    ("请填写面板标题、数据源和 PromQL", "Panel 제목, Datasource 및 PromQL을 입력하십시오."),
    ("请先在数据源管理中配置 Prometheus 或 VictoriaMetrics 数据源", "Datasource 관리에서 Prometheus 또는 VictoriaMetrics Datasource를 먼저 구성하십시오."),
    ("当前没有需要复核的异常面板", "현재 재검토할 이상 Panel이 없습니다."),
    ("复制失败，请手动复制 PromQL", "복사에 실패했습니다. PromQL을 직접 복사하십시오."),
    ("当前布局：列表巡检，适合日常排障和逐项核查。", "현재 Layout: Inspection List. 일상 Troubleshooting과 항목별 점검에 적합합니다."),
    ("当前布局：网格大屏，适合投屏展示和整体观测。", "현재 Layout: Grid Dashboard. 대형 화면 표시와 전체 관제에 적합합니다."),
    ("异常优先排序 · 当前展示 {{ inspectionPanels.length }} 项", "이상 항목 우선 정렬 · 현재 {{ inspectionPanels.length }}개 표시"),
    ("按面板逐项查看查询状态、当前值、返回序列和 PromQL，适合日常排障巡检。", "Panel별 Query 상태, 현재 값, 반환 Series, PromQL을 확인하며 일상 Troubleshooting Inspection에 적합합니다."),
    ("当前筛选条件下暂无面板", "현재 Filter 조건에 해당하는 Panel이 없습니다."),
    ("还没有监控大屏，请先创建一个", "Monitoring Dashboard가 없습니다. 먼저 생성하십시오."),
    ("当前大屏还没有面板，可以新增面板或使用模板创建", "현재 Dashboard에 Panel이 없습니다. Panel을 추가하거나 Template으로 생성하십시오."),
    ("请在名称和描述中搜索", "이름과 설명에서 검색"),
    ("请先选择巡检大屏", "Inspection Dashboard를 먼저 선택하십시오."),
    ("请输入${pageTitle.value}名称", "${pageTitle.value} 이름을 입력하십시오."),
    ("确认删除${pageTitle.value}「${activeDashboard.value.name}」吗？面板也会一起删除。", "${pageTitle.value} “${activeDashboard.value.name}”을(를) 삭제하시겠습니까? 연결된 Panel도 함께 삭제됩니다."),
    ("确认删除面板「${row.title}」吗？", "Panel “${row.title}”을(를) 삭제하시겠습니까?"),
    ("巡检报告", "Inspection Report"),
    ("打印 / 保存 PDF", "인쇄 / PDF 저장"),
    ("生成时间", "생성 시각"),
    ("查询数据源", "Query Datasource"),
    ("大屏状态", "Dashboard 상태"),
    ("刷新周期", "Refresh 주기"),
    ("面板数量", "Panel 수"),
    ("启用面板", "활성 Panel"),
    ("异常面板", "이상 Panel"),
    ("巡检类型", "Inspection Type"),
    ("列表巡检", "List Inspection"),
    ("暂无巡检面板", "Inspection Panel이 없습니다."),
    ("监控大屏", "Monitoring Dashboard"),
    ("巡检大屏", "Inspection Dashboard"),
    ("空白大屏", "빈 Dashboard"),
    ("主机资源大屏", "Host Resource Dashboard"),
    ("Kubernetes 大屏", "Kubernetes Dashboard"),
    ("主机总数", "전체 Host"),
    ("在线主机", "Online Host"),
    ("离线主机", "Offline Host"),
    ("平均 CPU 使用率", "평균 CPU 사용률"),
    ("平均内存使用率", "평균 Memory 사용률"),
    ("平均磁盘使用率", "평균 Disk 사용률"),
    ("CPU 使用率 Top", "CPU 사용률 Top"),
    ("内存使用率 Top", "Memory 사용률 Top"),
    ("磁盘使用率 Top", "Disk 사용률 Top"),
    ("系统负载 Top", "System Load Top"),
    ("网络接收速率 Top", "Network 수신 Rate Top"),
    ("网络发送速率 Top", "Network 송신 Rate Top"),
    ("磁盘读取速率 Top", "Disk Read Rate Top"),
    ("磁盘写入速率 Top", "Disk Write Rate Top"),
    ("CPU 使用趋势", "CPU 사용 Trend"),
    ("内存使用趋势", "Memory 사용 Trend"),
    ("文件句柄使用率", "File Handle 사용률"),
    ("运行进程数", "실행 Process 수"),
    ("系统运行时间 Top", "System Uptime Top"),
    ("主机信息", "Host 정보"),
    ("Pod 数量", "Pod 수"),
    ("异常 Pod", "이상 Pod"),
    ("Ready 节点", "Ready Node"),
    ("命名空间 Pod 分布", "Namespace별 Pod 분포"),
    ("节点 Pod 分布", "Node별 Pod 분포"),
    ("工作负载副本可用率", "Workload Replica 가용률"),
    ("异常原因 Top", "이상 Reason Top"),
    ("Pod 累计重启次数 Top", "Pod 누적 Restart Top"),
    ("Pod 最近 1 小时新增重启 Top", "최근 1시간 Pod Restart 증가 Top"),
    ("容器 CPU 使用趋势", "Container CPU 사용 Trend"),
    ("容器内存使用趋势", "Container Memory 사용 Trend"),
    ("Pod 网络接收速率", "Pod Network 수신 Rate"),
    ("Pod 网络发送速率", "Pod Network 송신 Rate"),
    ("Pod 明细", "Pod 상세"),
    ("CPU Request 使用率", "CPU Request 사용률"),
    ("内存 Request 使用率", "Memory Request 사용률"),
    ("命名空间", "Namespace"),
    ("未选择数据源", "Datasource 미선택"),
    ("未选择", "미선택"),
    ("个异常", "개 이상"),
    ("正常", "정상"),
    ("unit === '天'", "unit === '일'"),
    ("} 天`", "}일`"),
    ("unit !== '个' && unit !== '台'", "unit !== '개' && unit !== '대'"),
    ("stat: '指标'", "stat: 'Metric'"),
    ("gauge: '仪表盘'", "gauge: 'Gauge'"),
    ("bar: '排行'", "bar: 'Ranking'"),
    ("line: '趋势'", "line: 'Trend'"),
    ("table: '明细'", "table: '상세'"),
    ("已禁用", "비활성화됨"),
    ("查询失败", "Query 실패"),
    ("暂无数据", "Data 없음"),
    ("实时", "실시간"),
    ("PromQL 已复制", "PromQL을 복사했습니다."),
    ("保存成功", "저장했습니다."),
    ("删除成功", "삭제했습니다."),
    ("暂无{{ pageTitle }}", "{{ pageTitle }} 없음"),
    ("创建{{ pageTitle }}", "{{ pageTitle }} 생성"),
    ("最近更新", "최근 업데이트"),
    ("个启用面板", "개 활성 Panel"),
    ("选择数据源", "Datasource 선택"),
    ("最近 15 分钟", "최근 15분"),
    ("最近 1 小时", "최근 1시간"),
    ("最近 6 小时", "최근 6시간"),
    ("最近 24 小时", "최근 24시간"),
    ("关闭刷新", "자동 Refresh 끄기"),
    ("10 秒刷新", "10초 Refresh"),
    ("30 秒刷新", "30초 Refresh"),
    ("60 秒刷新", "60초 Refresh"),
    ("刷新全部", "전체 Refresh"),
    ("退出全屏", "전체 화면 종료"),
    ("大屏展示", "Dashboard 전체 화면"),
    ("导出巡检报告 PDF", "Inspection Report PDF Export"),
    ("编辑{{ pageTitle }}", "{{ pageTitle }} 수정"),
    ("删除{{ pageTitle }}", "{{ pageTitle }} 삭제"),
    ("新增面板", "Panel 추가"),
    ("关闭", "꺼짐"),
    ("全部 {{ panels.length }}", "전체 {{ panels.length }}"),
    ("异常 {{ inspectionSummary.danger }}", "이상 {{ inspectionSummary.danger }}"),
    ("待核查 {{ inspectionSummary.warning }}", "검토 필요 {{ inspectionSummary.warning }}"),
    ("正常 {{ inspectionSummary.healthy }}", "정상 {{ inspectionSummary.healthy }}"),
    ("复核异常", "이상 재검토"),
    ("执行巡检", "Inspection 실행"),
    ("巡检面板", "Inspection Panel"),
    ("未填写描述", "설명 없음"),
    ("当前值", "현재 값"),
    ("返回序列", "반환 Series"),
    ("数据源 / 类型", "Datasource / Type"),
    ("待确认", "확인 필요"),
    ("已停用", "비활성"),
    ("最近刷新", "최근 Refresh"),
    ("条序列", "개 Series"),
    ("最小", "최소"),
    ("平均", "평균"),
    ("最大", "최대"),
    ("起始", "시작"),
    ("实时采样", "실시간 Sampling"),
    ("编辑${pageTitle}", "${pageTitle} 수정"),
    ("创建${pageTitle}", "${pageTitle} 생성"),
    ("例如：生产环境${pageTitle}", "예: Production ${pageTitle}"),
    ("大屏模板", "Dashboard Template"),
    ("巡检大屏 / 列表巡检", "Inspection Dashboard / List Inspection"),
    ("监控大屏 / 网格展示", "Monitoring Dashboard / Grid Layout"),
    ("编辑面板", "Panel 수정"),
    ("标题", "제목"),
    ("数据源", "Datasource"),
    ("例如：up 或 sum(rate(http_requests_total[5m]))", "예: up 또는 sum(rate(http_requests_total[5m]))"),
    ("图表类型", "Chart Type"),
    ("指标卡", "Metric Card"),
    ("折线趋势", "Line Trend"),
    ("柱状排行", "Bar Ranking"),
    ("仪表盘", "Gauge"),
    ("表格", "Table"),
    ("单位", "Unit"),
    ("宽度", "Width"),
    ("排序", "Sort"),
    ("名称", "이름"),
    ("类型", "Type"),
    ("状态", "상태"),
    ("启用", "활성화"),
    ("禁用", "비활성화"),
    ("描述", "설명"),
    ("取消", "취소"),
    ("保存", "저장"),
    ("创建", "생성"),
    ("刷新", "Refresh"),
    ("编辑", "수정"),
    ("删除", "삭제"),
    ("操作", "작업"),
    ("面板", "Panel"),
    ("个", "개"),
    ("台", "대"),
    ("天", "일"),
    ("次", "회"),
    ("项", "개"),
    ("序列", "Series"),
]
for old, new in replacements:
    text = text.replace(old, new)
path.write_text(text, encoding="utf-8")
remaining = [(n, line) for n, line in enumerate(text.splitlines(), 1) if re.search(r'[\u3400-\u4DBF\u4E00-\u9FFF]', line)]
print(f"web batch12 left {len(remaining)} Han line(s)")
for n, line in remaining[:60]:
    print(f"REMAINING: {n}: {line.strip()}", file=sys.stderr)
raise SystemExit(1 if remaining else 0)
