#!/usr/bin/env python3
from __future__ import annotations

from pathlib import Path
import re
import sys

ROOT = Path(__file__).resolve().parents[2]
PATH = ROOT / "backend/service/ops_application.go"
HAN = re.compile(r"[\u3400-\u4DBF\u4E00-\u9FFF]")

REPLACEMENTS = [
    ('category == "全部模板"', 'category == "All Templates" || category == "\\u5168\\u90e8\\u6a21\\u677f"'),
    ('strings.Contains(env, "生产")', 'strings.Contains(strings.ToLower(env), "production") || strings.Contains(env, "\\u751f\\u4ea7")'),
    ('SVN 版本号仅支持 HEAD 或数字修订号', 'SVN revision supports only HEAD or a numeric revision'),
    ('构建参数 %s 格式不正确，只能使用大写字母、数字和下划线', 'invalid build parameter %s; use uppercase letters, digits, and underscores only'),
    ('构建参数 %s 重复', 'duplicate build parameter %s'),
    ('构建参数配置格式不正确', 'invalid build parameter configuration format'),
    ('请填写构建参数 %s', 'build parameter %s is required'),
    ('构建参数 %s 的值不在可选范围内', 'value for build parameter %s is outside the allowed options'),
    ('应用名称不能为空', 'application name is required'),
    ('应用编码不能为空', 'application code is required'),
    ('仓库地址不能为空', 'repository URL is required'),
    ('后端服务', 'Backend Service'),
    ('环境 %s 只能绑定一次', 'environment %s can be bound only once'),
    ('该应用下存在构建任务，请先删除构建任务', 'the application still has build tasks; delete them first'),
    ('该应用下存在 CI/CD 流水线，请先删除流水线', 'the application still has CI/CD pipelines; delete them first'),
    ('请选择所属应用', 'select an application'),
    ('构建任务名称不能为空', 'build task name is required'),
    ('构建脚本不能为空', 'build script is required'),
    ('构建执行节点类型不支持', 'unsupported build executor type'),
    ('请选择构建主机', 'select a build host'),
    ('构建任务ID不能为空', 'build task ID is required'),
    ('当前构建任务已禁用', 'the current build task is disabled'),
    ('当前应用已禁用，无法构建', 'the current application is disabled and cannot be built'),
    ('构建任务已创建，正在拉取代码', 'build task created; checking out source code'),
    ('构建记录 ID 不能为空', 'build record ID is required'),
    ('该历史记录不关联构建任务，无法按原配置重试', 'the build history is not linked to a build task and cannot be retried with the original configuration'),
    ('原构建参数无法读取，无法重试', 'original build parameters cannot be read; retry is unavailable'),
    ('镜像仓库名称和地址不能为空', 'image registry name and address are required'),
    ('镜像仓库 ID 不能为空', 'image registry ID is required'),
    ('Go 后端通用模板', 'Go Backend General Template'),
    ('Go 编译、镜像构建、上传镜像仓库、工作负载更新', 'Go compilation, image build, registry push, and workload update'),
    ('代码拉取', 'Source Checkout'),
    ('Go 依赖安装', 'Go Dependency Installation'),
    ('单元测试', 'Unit Test'),
    ('Go 编译', 'Go Build'),
    ('Docker 镜像构建', 'Docker Image Build'),
    ('上传镜像仓库', 'Push Image to Registry'),
    ('K8s 工作负载更新', 'Kubernetes Workload Update'),
    ('Maven Java 通用模板', 'Maven Java General Template'),
    ('Maven 打包、Jar 镜像、K8s 发布', 'Maven packaging, JAR image, and Kubernetes deployment'),
    ('Maven 依赖安装', 'Maven Dependency Installation'),
    ('Maven 打包', 'Maven Package'),
    ('K8s 发布', 'Kubernetes Deployment'),
    ('Vue 前端通用模板', 'Vue Frontend General Template'),
    ('npm 构建、镜像打包、K8s 滚动发布', 'npm build, image packaging, and Kubernetes rolling deployment'),
    ('K8s 滚动发布', 'Kubernetes Rolling Deployment'),
    ('发布通知', 'Deployment Notification'),
    ('流水线阶段配置不是有效 JSON', 'pipeline stage configuration is not valid JSON'),
    ('阶段 %d', 'Stage %d'),
    ('流水线至少需要配置一个执行阶段', 'pipeline requires at least one execution stage'),
    ('第 %d 个阶段的类型不受支持：%s', 'unsupported type for stage %d: %s'),
    ('第 %d 个阶段标识为空或重复', 'stage %d has an empty or duplicate identifier'),
    ('请填写第 %d 个阶段名称', 'stage %d name is required'),
    ('阶段「%s」缺少执行命令', 'stage %q is missing an execution command'),
    ('消息通知阶段「%s」需要选择通知规则', 'notification stage %q requires a notification rule'),
    ('镜像构建阶段「%s」需要选择镜像仓库', 'image-build stage %q requires an image registry'),
    ('K8s 发布阶段「%s」缺少集群、命名空间、工作负载或容器配置', 'Kubernetes deployment stage %q is missing cluster, namespace, workload, or container configuration'),
    ('上传镜像阶段「%s」需要引用前面的镜像构建阶段', 'image-push stage %q must reference a preceding image-build stage'),
    ('请选择流水线执行节点，流水线命令不会在 Ops Admin 容器内执行', 'select a pipeline executor; pipeline commands never run inside the Ops Admin container'),
    ('流水线名称不能为空', 'pipeline name is required'),
    ('流水线 ID 不能为空', 'pipeline ID is required'),
    ('请选择流水线执行节点', 'select a pipeline executor'),
    ('流水线执行节点不存在', 'pipeline executor does not exist'),
    ('所选流水线执行节点已停用', 'selected pipeline executor is disabled'),
    ('所选流水线执行节点未配置 SSH 认证凭据', 'selected pipeline executor has no SSH credential configured'),
    ('当前流水线已禁用，无法执行', 'the current pipeline is disabled and cannot be executed'),
    ('当前应用未配置所选环境的资源绑定', 'the application has no resource binding for the selected environment'),
    ('生产环境流水线必须包含人工确认阶段', 'production pipelines must include a manual approval stage'),
    ('该流水线已绑定构建任务，请选择已成功生成的制品', 'the pipeline is linked to a build task; select a successfully generated artifact'),
    ('所选制品不存在、不可用或不属于当前应用', 'selected artifact does not exist, is unavailable, or does not belong to the current application'),
    ('系统管理员', 'System Administrator'),
    ('流水线已创建，等待阶段执行', 'pipeline created and awaiting stage execution'),
    ('等待执行', 'Waiting'),
    ('流水线执行完成', 'pipeline execution completed'),
    ('等待人工审批：', 'Awaiting manual approval: '),
    ('等待人工审批', 'Awaiting manual approval'),
    ('正在执行：', 'Executing: '),
    ('正在执行', 'Executing'),
    ('执行成功', 'Execution succeeded'),
    ('执行失败，已按策略忽略：', 'Execution failed and was ignored by policy: '),
    (' 执行失败：', ' execution failed: '),
    ('[%s] 阶段执行完成：%s\\n', '[%s] Stage completed: %s\\n'),
    ('流水线执行 ID 不能为空', 'pipeline run ID is required'),
    ('当前流水线不处于待审批状态', 'the current pipeline is not awaiting approval'),
    ('未找到待审批阶段', 'no stage awaiting approval was found'),
    ('审批拒绝：', 'Approval rejected: '),
    ('人工审批未通过', 'manual approval was rejected'),
    ('审批通过：', 'Approved: '),
    ('审批通过，继续执行', 'approved; continuing execution'),
    ('没有找到可回滚的历史成功版本', 'no successful historical version is available for rollback'),
    ('当前流水线没有 K8s 发布阶段，无法自动回滚', 'the current pipeline has no Kubernetes deployment stage and cannot be rolled back automatically'),
    ('正在回滚到执行 #%d / %s', 'rolling back to run #%d / %s'),
    ('[%s] 阶段开始：%s\\n阶段类型：%s\\n执行策略：%s\\n执行节点：%s (%s)\\n工作目录：%s\\n\\n', '[%s] Stage started: %s\\nStage type: %s\\nExecution policy: %s\\nExecutor: %s (%s)\\nWorkspace: %s\\n\\n'),
    ('阶段脚本不能为空', 'stage script is required'),
    ('执行脚本', 'Execution Script'),
    (' 输出', ' Output'),
    ('镜像仓库登录', 'Image Registry Login'),
    ('上传镜像仓库: ', 'Push Image to Registry: '),
    ('K8s 发布需要选择目标集群', 'Kubernetes deployment requires a target cluster'),
    ('不支持的 K8s 工作负载类型：%s', 'unsupported Kubernetes workload type: %s'),
    ('发布后健康检查: ', 'Post-deployment Health Check: '),
    ('人工确认阶段由流水线调度器处理：执行会暂停，待审批通过后继续。\\n', 'The pipeline scheduler handles manual approval stages: execution pauses until approval is granted.\\n'),
    ('流水线 #%d 已执行到通知阶段「%s」', 'Pipeline #%d reached notification stage %q'),
    ('应用：%s\\n环境：%s\\n分支：%s\\n镜像版本：%s', 'Application: %s\\nEnvironment: %s\\nBranch: %s\\nImage Version: %s'),
    ('流水线 #%d', 'Pipeline #%d'),
    ('发送消息通知失败: %w', 'failed to send notification: %w'),
    ('所选通知规则未产生有效投递，请检查规则、模板和通知媒介状态', 'selected notification rule produced no valid delivery; verify the rule, template, and channel status'),
    ('已通过通知规则 #%d 创建 %d 条投递任务，实际发送结果请在消息通知 / 发送日志查看。\\n', 'Created %d delivery task(s) through notification rule #%d; review actual results in Notifications / Send Logs.\\n'),
    ('不支持的阶段类型：%s', 'unsupported stage type: %s'),
    ('流水线未配置执行节点', 'pipeline has no configured executor'),
    ('远程执行失败', 'remote execution failed'),
    ('远程代码拉取', 'Remote Source Checkout'),
    ('远程执行脚本', 'Remote Script Execution'),
    ('远程 Docker Build: ', 'Remote Docker Build: '),
    ('远程上传镜像仓库: ', 'Remote Registry Push: '),
    ('远程 kubectl 发布: ', 'Remote kubectl Deployment: '),
    ('远程发布后健康检查: ', 'Remote Post-deployment Health Check: '),
    ('请选择镜像仓库', 'select an image registry'),
    ('所选镜像仓库不存在或已禁用', 'selected image registry does not exist or is disabled'),
    ('所选镜像仓库不存在', 'selected image registry does not exist'),
    ('所选镜像仓库已停用', 'selected image registry is disabled'),
    ("echo '使用执行节点已有的 Docker 登录会话'", "echo 'Using the Docker login session already available on the executor'"),
    ('镜像仓库未配置登录账号或密码；请改用“执行节点已有登录会话”，或在镜像仓库中补充凭据', 'image registry has no username or password configured; use the executor existing login session or configure registry credentials'),
    ('目标集群 kubeconfig 为空', 'target cluster kubeconfig is empty'),
    ('未配置镜像仓库登录凭据，跳过 docker login。\\n', 'Image registry credentials are not configured; skipping docker login.\\n'),
    ('未配置仓库登录凭据，使用当前 Docker 客户端会话。\\n', 'Registry credentials are not configured; using the current Docker client session.\\n'),
    ('docker login 超时（%s）', 'docker login timed out (%s)'),
    ('当前应用已禁用，无法发布', 'the current application is disabled and cannot be deployed'),
    ('请先为应用创建构建任务', 'create a build task for the application first'),
    ('构建及构建后操作已完成', 'build and post-build operations completed'),
    ('构建主机不存在或不可用', 'build host does not exist or is unavailable'),
    ('正在拉取代码', 'Checking out source code'),
    ('远程代码拉取失败', 'remote source checkout failed'),
    ('正在执行构建脚本', 'Executing build script'),
    ('远程构建失败', 'remote build failed'),
    ('正在执行构建后操作', 'Executing post-build operation'),
    ('远程构建后操作失败', 'remote post-build operation failed'),
    ('构建失败', 'Build failed'),
    ('%s 执行超时', '%s execution timed out'),
    ('健康检查返回 HTTP %d', 'health check returned HTTP %d'),
    ('脚本执行超时', 'script execution timed out'),
]


def main() -> int:
    text = PATH.read_text(encoding="utf-8")
    count = 0
    for old, new in REPLACEMENTS:
        hits = text.count(old)
        if hits:
            text = text.replace(old, new)
            count += hits
    PATH.write_text(text, encoding="utf-8")
    remaining = [(n, line) for n, line in enumerate(text.splitlines(), 1) if HAN.search(line)]
    print(f"batch8 localized {count} occurrence(s); {len(remaining)} Han line(s) remain")
    for n, line in remaining[:30]:
        print(f"REMAINING: {n}: {line.strip()}", file=sys.stderr)
    return 1 if remaining else 0


if __name__ == "__main__":
    raise SystemExit(main())
