#!/usr/bin/env python3
from pathlib import Path
import re
import sys

path = Path(__file__).resolve().parents[2] / "web/src/views/monitor/MonitorAlertRule.vue"
text = path.read_text(encoding="utf-8")
replacements = [
    ("批量修改持续时间", "Duration 일괄 변경"),
    ("批量修改评估间隔", "Evaluation Interval 일괄 변경"),
    ("持续时间仅对监控告警生效；已选 ${selectedRuleIds.value.length} 条规则中的日志告警不会变更。", "Duration은 Metric Alert에만 적용됩니다. 선택한 ${selectedRuleIds.value.length}개 Rule 중 Log Alert는 변경되지 않습니다."),
    ("将统一更新已选 ${selectedRuleIds.value.length} 条告警规则的评估频率，并立即按新间隔重新调度。", "선택한 ${selectedRuleIds.value.length}개 Alert Rule의 Evaluation Frequency를 변경하고 새 Interval로 즉시 재예약합니다."),
    ("使用 Elasticsearch query_string（Lucene）语法，告警值为查询窗口内命中的日志条数。", "Elasticsearch query_string(Lucene) Syntax를 사용하며 Alert Value는 Query Window에서 Match된 Log 수입니다."),
    ("使用 VictoriaLogs LogsQL 语法，告警值为查询窗口内命中的日志条数。", "VictoriaLogs LogsQL Syntax를 사용하며 Alert Value는 Query Window에서 Match된 Log 수입니다."),
    ("PromQL 返回的每条时间序列都会独立与阈值比较，标签会保留在告警事件中。", "PromQL이 반환한 각 Time Series를 Threshold와 독립적으로 비교하며 Label은 Alert Event에 보존됩니다."),
    ("模板“${template.name}”没有可用的${alertTypeName(alertType)}数据源", "Template “${template.name}”에 사용할 수 있는 ${alertTypeName(alertType)} Datasource가 없습니다."),
    ("请先选择需要导入的告警模板", "Import할 Alert Template을 먼저 선택하십시오."),
    ("以下模板没有匹配的可用数据源：${invalid.map((item) => item.name).join('、')}", "다음 Template에 일치하는 사용 가능한 Datasource가 없습니다: ${invalid.map((item) => item.name).join(', ')}"),
    ("将从 ${templates.length} 个模板创建同名告警规则。新规则默认停用，确认测试后再启用。", "${templates.length}개 Template에서 같은 이름의 Alert Rule을 생성합니다. 새 Rule은 기본 비활성 상태이며 Test 후 활성화하십시오."),
    ("确认批量创建规则", "Alert Rule 일괄 생성 확인"),
    ("创建 ${templates.length} 条规则", "${templates.length}개 Rule 생성"),
    ("创建失败", "생성 실패"),
    ("已创建 ${succeeded.length} 条停用规则", "비활성 Rule ${succeeded.length}개를 생성했습니다."),
    ("${failed.length} 条规则创建失败", "Rule ${failed.length}개 생성에 실패했습니다."),
    ("返回检查", "검토로 돌아가기"),
    ("标签 JSON", "Label JSON"),
    ("注解 JSON", "Annotation JSON"),
    ("${label} 格式不正确，请输入有效的 JSON 对象", "${label} 형식이 올바르지 않습니다. 유효한 JSON Object를 입력하십시오."),
    ("请填写规则名称、${form.datasourceScope === 'specific' ? '数据源和' : ''}${form.alertType === 'log' ? ' Elasticsearch 查询语句' : ' PromQL'}", "Rule 이름, ${form.datasourceScope === 'specific' ? 'Datasource 및 ' : ''}${form.alertType === 'log' ? 'Elasticsearch Query' : 'PromQL'}을(를) 입력하십시오."),
    ("请选择通知规则", "Notification Rule을 선택하십시오."),
    ("该规则保存后会立即在全部同类型数据源上启用。请确认查询条件和阈值已经测试通过。", "이 Rule은 저장 즉시 같은 Type의 모든 Datasource에서 활성화됩니다. Query 조건과 Threshold Test가 통과했는지 확인하십시오."),
    ("确认启用全局规则", "Global Rule 활성화 확인"),
    ("确认启用", "활성화 확인"),
    ("请先填写${form.datasourceScope === 'specific' ? '数据源和' : ''}${form.alertType === 'log' ? ' Elasticsearch 查询语句' : ' PromQL'}", "먼저 ${form.datasourceScope === 'specific' ? 'Datasource 및 ' : ''}${form.alertType === 'log' ? 'Elasticsearch Query' : 'PromQL'}을(를) 입력하십시오."),
    ("规则预览失败，请检查数据源与查询语句后重试。", "Rule Preview에 실패했습니다. Datasource와 Query를 확인한 뒤 다시 시도하십시오."),
    ("禁用后规则「${row.name}」将停止评估，也不会再产生新告警。", "Rule “${row.name}”을(를) 비활성화하면 Evaluation이 중지되고 새 Alert가 발생하지 않습니다."),
    ("确认禁用规则", "Rule 비활성화 확인"),
    ("确认禁用", "비활성화 확인"),
    ("状态已更新", "상태를 업데이트했습니다."),
    ("评估任务已提交，结果稍后刷新", "Evaluation Task를 제출했습니다. 결과는 잠시 후 Refresh됩니다."),
    ("确认删除告警规则「${row.name}」吗？", "Alert Rule “${row.name}”을(를) 삭제하시겠습니까?"),
    ("确认批量${label}已选中的 ${selectedRuleIds.value.length} 条告警规则吗？", "선택한 Alert Rule ${selectedRuleIds.value.length}개를 일괄 ${label}하시겠습니까?"),
    ("已批量${label}", "일괄 ${label}을(를) 완료했습니다."),
    ("重复通知间隔需在 1 分钟到 7 天之间", "Repeat Notification Interval은 1분에서 7일 사이여야 합니다."),
    ("最大发送次数需在 0 到 1000 之间", "Maximum Send Count는 0에서 1000 사이여야 합니다."),
    ("已批量启用通知并绑定通知规则", "Notification을 일괄 활성화하고 Notification Rule을 연결했습니다."),
    ("请填写${batchTimingLabel.value}", "${batchTimingLabel.value}을(를) 입력하십시오."),
    ("已批量修改${batchTimingLabel.value}", "${batchTimingLabel.value}을(를) 일괄 변경했습니다."),
    ("配置数据源作用域、触发条件与通知策略，统一管理指标和日志告警的执行生命周期。", "Datasource Scope, Trigger Condition, Notification Policy를 구성해 Metric과 Log Alert Lifecycle을 통합 관리합니다."),
    ("本页启用", "현재 Page 활성"),
    ("评估失败", "Evaluation 실패"),
    ("从模板创建", "Template에서 생성"),
    ("新增规则", "Rule 추가"),
    ("搜索规则名称或查询语句", "Rule 이름 또는 Query 검색"),
    ("告警类型", "Alert Type"),
    ("监控告警", "Metric Alert"),
    ("ES 日志告警", "Elasticsearch Log Alert"),
    ("VictoriaLogs 日志告警", "VictoriaLogs Log Alert"),
    ("ES 日志", "Elasticsearch Log"),
    ("等级", "Severity"),
    ("规则清单", "Rule 목록"),
    ("共 {{ total }} 条规则，批量操作仅作用于当前页选中项。", "전체 {{ total }}개 Rule이며 Bulk Action은 현재 Page에서 선택한 항목에만 적용됩니다."),
    ("已选择", "선택됨"),
    ("条规则", "개 Rule"),
    ("批量启用通知", "Notification 일괄 활성화"),
    ("取消选择", "선택 해제"),
    ("数据源范围", "Datasource Scope"),
    ("全部同类数据源", "같은 Type의 전체 Datasource"),
    ("动态匹配所有已启用数据源", "활성화된 모든 Datasource 자동 Match"),
    ("指定数据源", "지정 Datasource"),
    ("触发条件", "Trigger Condition"),
    ("持续 ${row.forSeconds || 0} 秒", "Duration ${row.forSeconds || 0}초"),
    ("窗口 ${row.logTimeRangeSeconds || 300} 秒", "Window ${row.logTimeRangeSeconds || 300}초"),
    ("评估状态", "Evaluation 상태"),
    ("每 {{ row.evalIntervalSeconds }} 秒", "{{ row.evalIntervalSeconds }}초마다"),
    ("已开启", "활성"),
    ("未开启", "비활성"),
    ("更多", "더보기"),
    ("复制规则", "Rule 복제"),
    ("禁用规则", "Rule 비활성화"),
    ("启用规则", "Rule 활성화"),
    ("删除规则", "Rule 삭제"),
    ("配置执行规则", "Execution Rule 구성"),
    ("新建和复制规则默认保存为停用状态，建议先测试再启用。", "새 Rule과 복제 Rule은 기본 비활성 상태로 저장됩니다. Test 후 활성화하십시오."),
    ("选择告警模板", "Alert Template 선택"),
    ("基本信息", "기본 정보"),
    ("定义规则名称、类型与启用状态。", "Rule 이름, Type 및 활성 상태를 정의합니다."),
    ("规则名称", "Rule 이름"),
    ("例如：生产集群 Pod 异常", "예: Production Cluster Pod 이상"),
    ("规则状态", "Rule 상태"),
    ("停用 / 草稿", "비활성 / Draft"),
    ("监控告警 / PromQL", "Metric Alert / PromQL"),
    ("日志告警 / Elasticsearch", "Log Alert / Elasticsearch"),
    ("日志告警 / VictoriaLogs", "Log Alert / VictoriaLogs"),
    ("数据源与查询", "Datasource 및 Query"),
    ("明确规则作用范围并编写实际执行的查询语句。", "Rule 적용 범위를 정하고 실제 실행할 Query를 작성합니다."),
    ("匹配所有{{ alertTypeLabel }}数据源", "모든 {{ alertTypeLabel }} Datasource Match"),
    ("将对所有已启用的{{ form.alertType === 'log' ? ' Elasticsearch' : ' Prometheus / VictoriaMetrics' }}数据源分别执行规则。", "활성화된 모든 {{ form.alertType === 'log' ? 'Elasticsearch' : 'Prometheus / VictoriaMetrics' }} Datasource에서 Rule을 각각 실행합니다."),
    ("日志索引", "Log Index"),
    ("例如：logs-*、.ds-app-log-*；使用 _all 搜索全部索引", "예: logs-*, .ds-app-log-*. _all은 전체 Index를 검색합니다."),
    ("配置阈值、持续时间和评估频率。", "Threshold, Duration 및 Evaluation Frequency를 구성합니다."),
    ("比较符", "Comparator"),
    ("与阈值进行比较", "Threshold와 비교"),
    ("命中阈值", "Match Threshold"),
    ("阈值", "Threshold"),
    ("窗口内匹配日志条数", "Window 내 Match Log 수"),
    ("单条时间序列当前值", "개별 Time Series 현재 값"),
    ("查询窗口", "Query Window"),
    ("统计最近日志范围", "최근 Log 범위 집계"),
    ("连续命中后触发", "연속 Match 후 Trigger"),
    ("评估间隔", "Evaluation Interval"),
    ("系统执行规则的频率", "System Rule 실행 주기"),
    ("告警等级", "Alert Severity"),
    ("通知与上下文", "Notification 및 Context"),
    ("补充事件标签、处置说明与消息发送策略。", "Event Label, 대응 설명 및 Message Delivery Policy를 구성합니다."),
    ("例如：{\"team\":\"game\"}", "예: {\"team\":\"game\"}"),
    ("例如：{\"summary\":\"请及时处理\"}", "예: {\"summary\":\"즉시 확인 필요\"}"),
    ("消息通知", "Notification"),
    ("规则触发或恢复后，将按通知策略发送消息。", "Rule Trigger 또는 Recovery 후 Notification Policy에 따라 Message를 전송합니다."),
    ("当前未发送消息；开启后可配置通知策略。", "현재 Message를 전송하지 않습니다. 활성화하면 Notification Policy를 구성할 수 있습니다."),
    ("重复通知间隔", "Repeat Notification Interval"),
    ("最大发送次数", "Maximum Send Count"),
    ("0 表示不限制次数。", "0은 횟수 제한 없음을 의미합니다."),
    ("恢复通知", "Recovery Notification"),
    ("补充影响范围、处置建议或值班说明", "영향 범위, 대응 권고 또는 On-call 설명"),
    ("建议先执行测试，确认查询和阈值符合预期。", "먼저 Test를 실행해 Query와 Threshold가 예상과 일치하는지 확인하십시오."),
    ("测试规则", "Rule Test"),
    ("保存规则", "Rule 저장"),
    ("规则执行预览", "Rule Execution Preview"),
    ("正在执行规则预览", "Rule Preview 실행 중"),
    ("返回序列", "반환 Series"),
    ("预计告警", "예상 Alert"),
    ("查询成功", "Query 성공"),
    ("查询失败", "Query 실패"),
    ("查询成功，但没有返回时间序列", "Query는 성공했지만 Time Series가 없습니다."),
    ("是否触发", "Trigger 여부"),
    ("满足条件", "조건 충족"),
    ("未触发", "미발생"),
    ("当前值", "현재 값"),
    ("标签", "Label"),
    ("从告警模板批量创建规则", "Alert Template에서 Rule 일괄 생성"),
    ("告警模板库", "Alert Template Library"),
    ("勾选多个模板后可一次创建规则；新规则统一保存为停用状态，测试通过后再启用。", "여러 Template을 선택해 Rule을 한 번에 생성합니다. 새 Rule은 비활성 상태로 저장되며 Test 후 활성화하십시오."),
    ("搜索模板名称或查询条件", "Template 이름 또는 Query 조건 검색"),
    ("查询模板", "Template 검색"),
    ("全部模板", "전체 Template"),
    ("模板名称", "Template 이름"),
    ("基于该模板快速创建告警规则", "이 Template을 기준으로 Alert Rule 빠른 생성"),
    ("模板分组", "Template Group"),
    ("查询模板", "Query Template"),
    ("单条配置", "개별 구성"),
    ("当前条件下暂无告警模板", "현재 조건에 해당하는 Alert Template이 없습니다."),
    ("个模板", "개 Template"),
    ("清空选择", "선택 초기화"),
    ("批量创建规则", "Rule 일괄 생성"),
    ("将为已选中的 {{ selectedRuleIds.length }} 条告警规则开启消息通知，并统一应用以下通知策略。", "선택한 Alert Rule {{ selectedRuleIds.length }}개에 Notification을 활성화하고 다음 Policy를 일괄 적용합니다."),
    ("请选择通知规则", "Notification Rule을 선택하십시오."),
    ("分钟", "분"),
    ("0 表示不限制次数", "0은 횟수 제한 없음"),
    ("开启", "활성"),
    ("关闭", "비활성"),
    ("告警恢复后发送恢复消息", "Alert Recovery 후 Recovery Message 전송"),
    ("0 秒表示条件命中后立即触发；最长不超过 24 小时。", "0초는 조건 Match 즉시 Trigger를 의미하며 최대 24시간입니다."),
    ("评估间隔最短 15 秒，最长 1 小时。", "Evaluation Interval은 최소 15초, 최대 1시간입니다."),
    ("保存修改", "변경 저장"),
    ("ES 查询语句", "Elasticsearch Query"),
    ("LogsQL 查询语句", "LogsQL Query"),
    ("例如：", "예: "),
    ("成功", "성공"),
    ("失败", "실패"),
    ("执行中", "실행 중"),
    ("未执行", "미실행"),
    ("尚未评估", "미평가"),
    ("复制告警规则", "Alert Rule 복제"),
    ("编辑告警规则", "Alert Rule 수정"),
    ("新增告警规则", "Alert Rule 추가"),
    (" 天", "일"),
    (" 小时", "시간"),
    (" 分钟", "분"),
    (" 秒", "초"),
    ("未分组", "미분류"),
    (" - 副本", " - Copy"),
    ("保存成功", "저장했습니다."),
    ("删除成功", "삭제했습니다."),
    ("启用", "활성화"),
    ("禁用", "비활성화"),
    ("查询", "조회"),
    ("重置", "초기화"),
    ("刷新", "Refresh"),
    ("规则", "Rule"),
    ("数据源", "Datasource"),
    ("通知", "Notification"),
    ("运行", "실행"),
    ("编辑", "수정"),
    ("删除", "삭제"),
    ("取消", "취소"),
    ("状态", "상태"),
    ("描述", "설명"),
    ("操作", "작업"),
    ("秒", "초"),
    ("条", "개"),
]
for old, new in replacements:
    text = text.replace(old, new)
path.write_text(text, encoding="utf-8")
remaining = [(n, line) for n, line in enumerate(text.splitlines(), 1) if re.search(r'[\u3400-\u4DBF\u4E00-\u9FFF]', line)]
print(f"web batch13 left {len(remaining)} Han line(s)")
for n, line in remaining[:60]:
    print(f"REMAINING: {n}: {line.strip()}", file=sys.stderr)
raise SystemExit(1 if remaining else 0)
