#!/usr/bin/env python3
from __future__ import annotations

from pathlib import Path
import re
import sys

path = Path(__file__).resolve().parents[2] / "web/src/views/applications/AppPipelineCenter.vue"
han = re.compile(r"[\u3400-\u4DBF\u4E00-\u9FFF]")
text = path.read_text(encoding="utf-8")

# Longest and domain-specific phrases first. Generic terms at the end only fill
# short labels that are repeated throughout the component.
replacements = [
    ('请选择流水线执行节点；代码、构建、镜像和发布不会在 Ops Admin 容器内执行', 'Pipeline 실행 Node를 선택하십시오. Source, Build, Image, Deploy 작업은 Ops Admin Container에서 실행되지 않습니다.'),
    ('从代码拉取、构建、测试、制品、发布到通知，统一编排应用交付流程。', 'Source Checkout부터 Build, Test, Artifact, Deploy, Notification까지 Application Delivery Flow를 통합 Orchestration합니다.'),
    ('使用应用的 Git / SVN 仓库和执行分支拉取代码', 'Application의 Git / SVN Repository와 실행 Branch를 사용해 Source를 Checkout합니다.'),
    ('在执行节点的工作目录中执行自定义 Shell 命令', '실행 Node의 Workspace에서 사용자 정의 Shell Command를 실행합니다.'),
    ('执行自动化测试；失败时可按策略停止或继续', '자동화 Test를 실행하며 실패 시 Policy에 따라 중지하거나 계속합니다.'),
    ('定义镜像目标并在执行节点执行 docker build', 'Target Image를 정의하고 실행 Node에서 docker build를 실행합니다.'),
    ('推送前面构建出的同一镜像与版本', '앞 Stage에서 Build한 동일한 Image와 Version을 Push합니다.'),
    ('通过执行节点的 kubectl 更新目标工作负载', '실행 Node의 kubectl로 Target Workload를 업데이트합니다.'),
    ('暂停流水线，等待人工确认后继续', 'Pipeline을 일시 중지하고 Manual Approval 후 계속합니다.'),
    ('调用消息通知规则创建投递任务', 'Notification Rule을 호출해 Delivery Task를 생성합니다.'),
    ('请至少配置一个执行阶段', '실행 Stage를 하나 이상 구성하십시오.'),
    ('的标识重复，请删除后重新添加该阶段', '의 ID가 중복되었습니다. 해당 Stage를 삭제한 뒤 다시 추가하십시오.'),
    ('请选择流水线模板，或使用空白流水线', 'Pipeline Template을 선택하거나 빈 Pipeline을 사용하십시오.'),
    ('请填写流水线名称并选择所属应用', 'Pipeline 이름을 입력하고 Application을 선택하십시오.'),
    ('自定义参数需要是 JSON 对象', 'Custom Parameter는 JSON Object여야 합니다.'),
    ('请输入审批说明，确认', 'Approval 설명을 입력하고 현재 Deploy의 '),
    ('当前发布。', '을(를) 확인하십시오.'),
    ('将使用上一次成功执行的镜像版本重新执行 K8s 发布阶段，是否继续？', '마지막 성공 Run의 Image Version으로 Kubernetes Deploy Stage를 다시 실행하시겠습니까?'),
    ('确认删除流水线「', 'Pipeline “'),
    ('」及其执行记录？', '”과 해당 Run History를 삭제하시겠습니까?'),
    ('该阶段暂未产生执行日志。', '이 Stage에는 아직 실행 Log가 없습니다.'),
    ('从模板快速创建标准流水线，或从空白流水线开始。', 'Template으로 표준 Pipeline을 빠르게 생성하거나 빈 Pipeline에서 시작합니다.'),
    ('选择一个模板，后续可继续编辑全部阶段。', 'Template을 선택한 뒤 모든 Stage를 계속 수정할 수 있습니다.'),
    ('完全自定义阶段与执行顺序。', 'Stage와 실행 순서를 완전히 사용자 정의합니다.'),
    ('所有命令统一在该主机执行，不会在 Ops Admin 容器内执行。', '모든 Command는 이 Host에서 실행되며 Ops Admin Container에서는 실행되지 않습니다.'),
    ('生产环境建议加入人工确认阶段。', 'Production Environment에는 Manual Approval Stage 추가를 권장합니다.'),
    ('在执行节点的工作目录内以 Shell 方式执行', '실행 Node의 Workspace에서 Shell 방식으로 실행합니다.'),
    ('请输入要执行的 Shell 命令，例如 npm run build / go test ./...', '실행할 Shell Command를 입력하십시오. 예: npm run build / go test ./...'),
    ('构建会自动标记为：仓库地址 / 命名空间 / 应用编码 : 分支-时间', 'Build Image Tag는 Registry Address / Namespace / Application Code : Branch-Time 형식으로 자동 생성됩니다.'),
    ('引用镜像构建阶段，确保镜像地址和版本完全一致。', 'Image Build Stage를 참조해 Image Address와 Version을 동일하게 유지합니다.'),
    ('推荐使用镜像仓库凭据', 'Image Registry Credential 사용 권장'),
    ('从“镜像仓库”页面读取账号和密码；选择“执行节点已登录”时，平台不会执行 docker login。', 'Image Registry Page에서 Account와 Password를 읽습니다. “실행 Node Login 사용”을 선택하면 Platform은 docker login을 실행하지 않습니다.'),
    ('使用执行节点上的 kubectl 完成工作负载镜像更新与健康检查', '실행 Node의 kubectl로 Workload Image Update와 Health Check를 수행합니다.'),
    ('自动使用所属应用配置的 Git / SVN 仓库地址，并按本次执行选择的分支或 Tag 拉取代码。', 'Application에 구성된 Git / SVN Repository를 사용하고 이번 Run에서 선택한 Branch 또는 Tag로 Source를 Checkout합니다.'),
    ('流水线会暂停并等待审批人选择“通过”或“拒绝”；通过后才会继续后续阶段。', 'Pipeline은 중지된 뒤 Approver의 승인 또는 거부를 기다립니다. 승인된 경우에만 다음 Stage를 실행합니다.'),
    ('按所选规则创建投递任务，发送结果可在“消息通知 / 发送日志”中查看。', '선택한 Rule로 Delivery Task를 생성하며 결과는 Notification / Send Log에서 확인할 수 있습니다.'),
    ('自定义参数覆盖流水线默认参数，必须是 JSON 对象。', 'Custom Parameter는 Pipeline Default Parameter를 Override하며 JSON Object여야 합니다.'),
    ('当前执行未产生阶段记录。', '현재 Run에는 Stage Record가 없습니다.'),
    ('请从上方时间线选择一个阶段查看日志。', '위 Timeline에서 Stage를 선택해 Log를 확인하십시오.'),
    ('选择构建后的镜像仓库', 'Build 후 사용할 Image Registry 선택'),
    ('选择前面的镜像构建阶段', '이전 Image Build Stage 선택'),
    ('需要替换镜像的容器', 'Image를 교체할 Container'),
    ('默认使用应用编码', '기본값은 Application Code'),
    ('选择 CI/CD 流水线通知规则', 'CI/CD Pipeline Notification Rule 선택'),
    ('自动生成：', '자동 생성: '),
    ('流水线执行详情', 'Pipeline Run 상세'),
    ('流水线阶段时间线', 'Pipeline Stage Timeline'),
    ('下载全部日志', '전체 Log Download'),
    ('下载日志', 'Log Download'),
    ('回滚上一版本', '이전 Version Rollback'),
    ('审批通过', 'Approval 승인'),
    ('审批拒绝', 'Approval 거부'),
    ('人工审批通过', 'Manual Approval 승인'),
    ('人工审批拒绝', 'Manual Approval 거부'),
    ('回滚确认', 'Rollback 확인'),
    ('删除流水线', 'Pipeline 삭제'),
    ('立即执行流水线', 'Pipeline 즉시 실행'),
    ('开始执行', '실행 시작'),
    ('新建流水线', '새 Pipeline'),
    ('流水线列表', 'Pipeline 목록'),
    ('流水线模板', 'Pipeline Template'),
    ('空白流水线', '빈 Pipeline'),
    ('全部模板', '전체 Template'),
    ('空模板', '빈 Template'),
    ('通用模板', 'General Template'),
    ('流水线总数', '전체 Pipeline'),
    ('最近失败', '최근 실패'),
    ('执行节点已登录', '실행 Node Login 사용'),
    ('镜像仓库凭据', 'Image Registry Credential'),
    ('目标镜像仓库', 'Target Image Registry'),
    ('镜像仓库地址', 'Image Registry Address'),
    ('推送已构建镜像', 'Build Image Push'),
    ('定义镜像产物', 'Image Artifact 정의'),
    ('镜像来源', 'Image Source'),
    ('登录方式', 'Login 방식'),
    ('构建上下文', 'Build Context'),
    ('将构建为', 'Build 결과'),
    ('发布目标', 'Deploy Target'),
    ('健康检查 URL（可选）', 'Health Check URL (선택)'),
    ('人工确认关卡', 'Manual Approval Gate'),
    ('发送流水线通知', 'Pipeline Notification 전송'),
    ('通知规则', 'Notification Rule'),
    ('删除阶段', 'Stage 삭제'),
    ('阶段名称', 'Stage 이름'),
    ('阶段类型', 'Stage Type'),
    ('超时时间', 'Timeout'),
    ('失败策略', 'Failure Policy'),
    ('失败终止', '실패 시 중지'),
    ('忽略继续', '무시하고 계속'),
    ('执行脚本', '실행 Script'),
    ('工作负载类型', 'Workload Type'),
    ('工作负载名称', 'Workload 이름'),
    ('容器名称', 'Container 이름'),
    ('代码来源', 'Source'),
    ('执行环境', '실행 Environment'),
    ('镜像版本', 'Image Version'),
    ('自定义参数', 'Custom Parameter'),
    ('当前阶段', '현재 Stage'),
    ('阶段日志', 'Stage Log'),
    ('全部应用', '전체 Application'),
    ('全部环境', '전체 Environment'),
    ('全部技术栈', '전체 Tech Stack'),
    ('全部状态', '전체 상태'),
    ('搜索流水线 / 应用 / 仓库', 'Pipeline / Application / Repository 검색'),
    ('流水线名称', 'Pipeline 이름'),
    ('仓库地址', 'Repository Address'),
    ('技术栈', 'Tech Stack'),
    ('执行节点', '실행 Node'),
    ('阶段数', 'Stage 수'),
    ('最近执行', '최근 실행'),
    ('立即执行', '즉시 실행'),
    ('复制', '복제'),
    ('启用中', '활성'),
    ('已启用', '활성화됨'),
    ('已禁用', '비활성화됨'),
    ('待人工审批', 'Manual Approval 대기'),
    ('等待中', '대기 중'),
    ('执行中', '실행 중'),
    ('成功', '성공'),
    ('失败', '실패'),
    ('启用', '활성화'),
    ('禁用', '비활성화'),
    ('自定义', '사용자 정의'),
    ('应用', 'Application'),
    ('环境', 'Environment'),
    ('关键字', 'Keyword'),
    ('搜索', '검색'),
    ('重置', '초기화'),
    ('流水线', 'Pipeline'),
    ('阶段', 'Stage'),
    ('代码拉取', 'Source Checkout'),
    ('构建命令', 'Build Command'),
    ('单元测试', 'Unit Test'),
    ('Docker 镜像构建', 'Docker Image Build'),
    ('上传镜像仓库', 'Image Registry Push'),
    ('镜像构建', 'Image Build'),
    ('K8s 发布', 'Kubernetes Deploy'),
    ('人工确认', 'Manual Approval'),
    ('消息通知', 'Notification'),
    ('命令', 'Command'),
    ('测试', 'Test'),
    ('构建', 'Build'),
    ('配置当前', '현재 구성'),
    ('主机 #', 'Host #'),
    ('资产主机 #', 'Asset Host #'),
    ('未配置', '미구성'),
    ('请选择', '선택하십시오: '),
    ('请填写', '입력하십시오: '),
    ('无法执行：', '실행할 수 없음: '),
    ('保存成功', '저장했습니다.'),
    ('复制成功', '복제했습니다.'),
    ('删除成功', '삭제했습니다.'),
    ('回滚任务已创建：#', 'Rollback Task를 생성했습니다: #'),
    ('已开始执行：#', '실행을 시작했습니다: #'),
    ('请输入', '입력하십시오: '),
    ('审批说明', 'Approval 설명'),
    ('通过', '승인'),
    ('拒绝', '거부'),
    ('已', ''),
    ('确认', '확인'),
    ('是否继续？', '계속하시겠습니까?'),
    ('操作', '작업'),
    ('编辑', '수정'),
    ('删除', '삭제'),
    ('取消', '취소'),
    ('保存', '저장'),
    ('状态', '상태'),
    ('耗时', 'Duration'),
    ('当前', '현재'),
    ('日志', 'Log'),
    ('秒', '초'),
    ('分 ', '분 '),
    ('个媒介', '개 Channel'),
    ('顺序', '순서'),
    ('例如', '예'),
    ('分支', 'Branch'),
    ('命名空间', 'Namespace'),
]

for old, new in replacements:
    text = text.replace(old, new)
path.write_text(text, encoding="utf-8")
remaining = [(n, line) for n, line in enumerate(text.splitlines(), 1) if han.search(line)]
print(f"web batch10 left {len(remaining)} Han line(s)")
for n, line in remaining[:50]:
    print(f"REMAINING: {n}: {line.strip()}", file=sys.stderr)
raise SystemExit(1 if remaining else 0)
