package router

import (
	"ops-admin/backend/controller"
	"ops-admin/backend/opdef"

	"github.com/gin-gonic/gin"
	"gorm.io/gorm"
)

// registerInfra mounts the infra-domain v1 routes on the authenticated api
// group: domain (public/internal DNS + SSL certificates), the full asset
// tree (host, service, hostGroup, credential, cloudAccount, gateway,
// database), dbms, monitor and k8s. Phase A pure move from router.go —
// route statements are verbatim; only the group receiver name and one
// indentation level changed. Group construction and the group-level
// middlewares stay in router.go (plan §J1).
func registerInfra(g *gin.RouterGroup, db *gorm.DB, ctl *controller.Controller) {
	g.GET("/domain/public/accounts", opdef.Middleware(db, opdef.Must("GET", "/domain/public/accounts")), ctl.ListPublicDNSAccounts)
	g.GET("/domain/public/accounts/options", opdef.Middleware(db, opdef.Must("GET", "/domain/public/accounts/options")), ctl.PublicDNSAccountOptions)
	g.GET("/domain/public/accounts/detail", opdef.Middleware(db, opdef.Must("GET", "/domain/public/accounts/detail")), ctl.GetPublicDNSAccount)
	g.POST("/domain/public/accounts/save", opdef.Middleware(db, opdef.Must("POST", "/domain/public/accounts/save")), ctl.SavePublicDNSAccount)
	g.DELETE("/domain/public/accounts/delete", opdef.Middleware(db, opdef.Must("DELETE", "/domain/public/accounts/delete")), ctl.DeletePublicDNSAccount)
	g.POST("/domain/public/accounts/test", opdef.Middleware(db, opdef.Must("POST", "/domain/public/accounts/test")), ctl.TestPublicDNSAccount)
	g.GET("/domain/public/domains", opdef.Middleware(db, opdef.Must("GET", "/domain/public/domains")), ctl.ListPublicDomains)
	g.POST("/domain/public/domains/sync", opdef.Middleware(db, opdef.Must("POST", "/domain/public/domains/sync")), ctl.SyncPublicDomains)
	g.GET("/domain/public/records", opdef.Middleware(db, opdef.Must("GET", "/domain/public/records")), ctl.ListPublicDNSRecords)
	g.POST("/domain/public/records/mutate", opdef.Middleware(db, opdef.Must("POST", "/domain/public/records/mutate")), ctl.MutatePublicDNSRecord)
	g.POST("/domain/public/records/batch", opdef.Middleware(db, opdef.Must("POST", "/domain/public/records/batch")), ctl.BatchPublicDNSRecords)
	g.GET("/domain/internal/settings", opdef.Middleware(db, opdef.Must("GET", "/domain/internal/settings")), ctl.GetInternalDNSSettings)
	g.PUT("/domain/internal/settings", opdef.Middleware(db, opdef.Must("PUT", "/domain/internal/settings")), ctl.SaveInternalDNSSettings)
	g.GET("/domain/internal/zones", opdef.Middleware(db, opdef.Must("GET", "/domain/internal/zones")), ctl.ListInternalDNSZones)
	g.POST("/domain/internal/zones/save", opdef.Middleware(db, opdef.Must("POST", "/domain/internal/zones/save")), ctl.SaveInternalDNSZone)
	g.DELETE("/domain/internal/zones/delete", opdef.Middleware(db, opdef.Must("DELETE", "/domain/internal/zones/delete")), ctl.DeleteInternalDNSZone)
	g.GET("/domain/internal/records", opdef.Middleware(db, opdef.Must("GET", "/domain/internal/records")), ctl.ListInternalDNSRecords)
	g.POST("/domain/internal/records/save", opdef.Middleware(db, opdef.Must("POST", "/domain/internal/records/save")), ctl.SaveInternalDNSRecord)
	g.DELETE("/domain/internal/records/delete", opdef.Middleware(db, opdef.Must("DELETE", "/domain/internal/records/delete")), ctl.DeleteInternalDNSRecord)
	g.POST("/domain/internal/records/batch", opdef.Middleware(db, opdef.Must("POST", "/domain/internal/records/batch")), ctl.BatchInternalDNSRecords)
	g.POST("/domain/internal/query", opdef.Middleware(db, opdef.Must("POST", "/domain/internal/query")), ctl.TestDNSResolution)
	g.GET("/domain/audit", opdef.Middleware(db, opdef.Must("GET", "/domain/audit")), ctl.ListDNSAuditLogs)
	g.GET("/domain/public/certificates", opdef.Middleware(db, opdef.Must("GET", "/domain/public/certificates")), ctl.ListSSLCertificates)
	g.GET("/domain/public/certificates/detail", opdef.Middleware(db, opdef.Must("GET", "/domain/public/certificates/detail")), ctl.GetSSLCertificate)
	g.GET("/domain/public/certificates/domain-options", opdef.Middleware(db, opdef.Must("GET", "/domain/public/certificates/domain-options")), ctl.SSLCertificateDomainOptions)
	g.GET("/domain/public/certificates/tasks", opdef.Middleware(db, opdef.Must("GET", "/domain/public/certificates/tasks")), ctl.ListSSLCertificateTasks)
	g.GET("/domain/public/certificates/audits", opdef.Middleware(db, opdef.Must("GET", "/domain/public/certificates/audits")), ctl.ListSSLCertificateAudits)
	g.POST("/domain/public/certificates/sync", opdef.Middleware(db, opdef.Must("POST", "/domain/public/certificates/sync")), ctl.SyncSSLCertificates)
	g.POST("/domain/public/certificates/upload", opdef.Middleware(db, opdef.Must("POST", "/domain/public/certificates/upload")), ctl.UploadSSLCertificate)
	g.POST("/domain/public/certificates/apply", opdef.Middleware(db, opdef.Must("POST", "/domain/public/certificates/apply")), ctl.ApplySSLCertificate)
	g.POST("/domain/public/certificates/renew", opdef.Middleware(db, opdef.Must("POST", "/domain/public/certificates/renew")), ctl.RenewSSLCertificate)
	g.POST("/domain/public/certificates/resync", opdef.Middleware(db, opdef.Must("POST", "/domain/public/certificates/resync")), ctl.ResyncSSLCertificate)
	g.PUT("/domain/public/certificates/renew-settings", opdef.Middleware(db, opdef.Must("PUT", "/domain/public/certificates/renew-settings")), ctl.UpdateSSLCertificateRenewSettings)
	g.DELETE("/domain/public/certificates/delete", opdef.Middleware(db, opdef.Must("DELETE", "/domain/public/certificates/delete")), ctl.DeleteSSLCertificate)
	g.GET("/domain/public/certificates/download", opdef.Middleware(db, opdef.Must("GET", "/domain/public/certificates/download")), ctl.DownloadSSLCertificate)
	g.GET("/domain/public/certificates/download-private", opdef.Middleware(db, opdef.Must("GET", "/domain/public/certificates/download-private")), ctl.DownloadSSLCertificatePrivate)

	g.GET("/asset/host/list", opdef.Middleware(db, opdef.Must("GET", "/asset/host/list")), ctl.GetAssetHostList)
	g.GET("/asset/service/list", ctl.GetAssetServiceList)
	g.GET("/asset/service/info", ctl.GetAssetServiceInfo)
	g.POST("/asset/service/save", opdef.Middleware(db, opdef.Must("POST", "/asset/service/save")), ctl.SaveAssetService)
	g.DELETE("/asset/service/delete", opdef.Middleware(db, opdef.Must("DELETE", "/asset/service/delete")), ctl.DeleteAssetService)
	g.GET("/asset/service/k8s/catalog", ctl.GetAssetServiceK8sCatalog)
	g.GET("/asset/service/runtime-topology", ctl.GetAssetServiceRuntimeTopology)
	g.GET("/asset/service/workload/runtime", ctl.GetAssetServiceWorkloadRuntime)
	g.GET("/asset/service/workload/topology", ctl.GetAssetServiceWorkloadTopology)
	g.GET("/asset/service/workload/metrics", ctl.GetAssetServiceWorkloadMetrics)
	g.GET("/asset/service/workload/rollout-history", ctl.GetAssetServiceWorkloadRolloutHistory)
	g.POST("/asset/service/workload/rollback", opdef.Middleware(db, opdef.Must("POST", "/asset/service/workload/rollback")), ctl.RollbackAssetServiceWorkload)
	g.GET("/asset/service/workload/logs", opdef.Middleware(db, opdef.Must("GET", "/asset/service/workload/logs")), ctl.GetAssetServiceWorkloadLogs)
	g.GET("/asset/service/diagnosis/processes", opdef.Middleware(db, opdef.Must("GET", "/asset/service/diagnosis/processes")), ctl.GetAssetServiceDiagnosisProcesses)
	g.GET("/asset/service/diagnosis/environment", opdef.Middleware(db, opdef.Must("GET", "/asset/service/diagnosis/environment")), ctl.GetAssetServiceDiagnosisEnvironment)
	g.GET("/asset/service/diagnosis/run", opdef.Middleware(db, opdef.Must("GET", "/asset/service/diagnosis/run")), ctl.AssetServiceDiagnosisRunGone)
	g.POST("/asset/service/diagnosis/run", opdef.Middleware(db, opdef.Must("POST", "/asset/service/diagnosis/run")), ctl.RunAssetServiceDiagnosis)
	g.POST("/asset/service/diagnosis/arthas/download", opdef.Middleware(db, opdef.Must("POST", "/asset/service/diagnosis/arthas/download")), ctl.DownloadAssetServiceArthas)
	g.POST("/asset/service/diagnosis/arthas/upload", opdef.Middleware(db, opdef.Must("POST", "/asset/service/diagnosis/arthas/upload")), ctl.UploadAssetServiceArthas)
	g.GET("/asset/overview", ctl.GetAssetOverview)
	g.GET("/asset/change-log/list", ctl.GetAssetChangeLogs)
	g.GET("/asset/host/info", opdef.Middleware(db, opdef.Must("GET", "/asset/host/info")), ctl.GetAssetHostInfo)
	g.GET("/asset/host/metrics", ctl.GetAssetHostMetrics)
	g.GET("/asset/host/template", ctl.DownloadAssetHostTemplate)
	g.POST("/asset/host/add", opdef.Middleware(db, opdef.Must("POST", "/asset/host/add")), ctl.CreateAssetHost)
	g.POST("/asset/host/import", opdef.Middleware(db, opdef.Must("POST", "/asset/host/import")), ctl.ImportAssetHosts)
	g.POST("/asset/host/cloudSync", opdef.Middleware(db, opdef.Must("POST", "/asset/host/cloudSync")), ctl.SyncAssetHostsFromCloud)
	g.PUT("/asset/host/update", opdef.Middleware(db, opdef.Must("PUT", "/asset/host/update")), ctl.UpdateAssetHost)
	g.POST("/asset/host/sync", opdef.Middleware(db, opdef.Must("POST", "/asset/host/sync")), ctl.SyncAssetHost)
	g.POST("/asset/host/batch/sync", opdef.Middleware(db, opdef.Must("POST", "/asset/host/batch/sync")), ctl.BatchSyncAssetHosts)
	g.PUT("/asset/host/batch/credential", opdef.Middleware(db, opdef.Must("PUT", "/asset/host/batch/credential")), ctl.BatchReplaceAssetHostCredential)
	g.DELETE("/asset/host/group/remove", opdef.Middleware(db, opdef.Must("DELETE", "/asset/host/group/remove")), ctl.RemoveAssetHostsFromGroup)
	g.DELETE("/asset/host/delete", opdef.Middleware(db, opdef.Must("DELETE", "/asset/host/delete")), ctl.DeleteAssetHost)
	g.DELETE("/asset/host/batch/delete", opdef.Middleware(db, opdef.Must("DELETE", "/asset/host/batch/delete")), ctl.BatchDeleteAssetHosts)

	g.GET("/asset/hostGroup/list", ctl.GetAssetHostGroupList)
	g.GET("/asset/hostGroup/info", ctl.GetAssetHostGroupInfo)
	g.POST("/asset/hostGroup/add", opdef.Middleware(db, opdef.Must("POST", "/asset/hostGroup/add")), ctl.CreateAssetHostGroup)
	g.PUT("/asset/hostGroup/update", opdef.Middleware(db, opdef.Must("PUT", "/asset/hostGroup/update")), ctl.UpdateAssetHostGroup)
	g.DELETE("/asset/hostGroup/delete", opdef.Middleware(db, opdef.Must("DELETE", "/asset/hostGroup/delete")), ctl.DeleteAssetHostGroup)

	g.GET("/asset/credential/list", opdef.Middleware(db, opdef.Must("GET", "/asset/credential/list")), ctl.GetAssetCredentialList)
	g.GET("/asset/credential/options", opdef.Middleware(db, opdef.Must("GET", "/asset/credential/options")), ctl.GetAssetCredentialOptions)
	g.GET("/asset/credential/info", opdef.Middleware(db, opdef.Must("GET", "/asset/credential/info")), ctl.GetAssetCredentialInfo)
	g.POST("/asset/credential/add", opdef.Middleware(db, opdef.Must("POST", "/asset/credential/add")), ctl.CreateAssetCredential)
	g.PUT("/asset/credential/update", opdef.Middleware(db, opdef.Must("PUT", "/asset/credential/update")), ctl.UpdateAssetCredential)
	g.DELETE("/asset/credential/delete", opdef.Middleware(db, opdef.Must("DELETE", "/asset/credential/delete")), ctl.DeleteAssetCredential)

	g.GET("/asset/cloudAccount/list", opdef.Middleware(db, opdef.Must("GET", "/asset/cloudAccount/list")), ctl.GetAssetCloudAccountList)
	g.GET("/asset/cloudAccount/options", ctl.GetAssetCloudAccountOptions)
	g.GET("/asset/cloudAccount/info", opdef.Middleware(db, opdef.Must("GET", "/asset/cloudAccount/info")), ctl.GetAssetCloudAccountInfo)
	g.POST("/asset/cloudAccount/add", opdef.Middleware(db, opdef.Must("POST", "/asset/cloudAccount/add")), ctl.CreateAssetCloudAccount)
	g.PUT("/asset/cloudAccount/update", opdef.Middleware(db, opdef.Must("PUT", "/asset/cloudAccount/update")), ctl.UpdateAssetCloudAccount)
	g.DELETE("/asset/cloudAccount/delete", opdef.Middleware(db, opdef.Must("DELETE", "/asset/cloudAccount/delete")), ctl.DeleteAssetCloudAccount)
	g.GET("/asset/gateway/list", ctl.GetAssetGatewayList)
	g.GET("/asset/gateway/options", ctl.GetAssetGatewayOptions)
	g.GET("/asset/gateway/info", ctl.GetAssetGatewayInfo)
	g.POST("/asset/gateway/add", opdef.Middleware(db, opdef.Must("POST", "/asset/gateway/add")), ctl.CreateAssetGateway)
	g.PUT("/asset/gateway/update", opdef.Middleware(db, opdef.Must("PUT", "/asset/gateway/update")), ctl.UpdateAssetGateway)
	g.DELETE("/asset/gateway/delete", opdef.Middleware(db, opdef.Must("DELETE", "/asset/gateway/delete")), ctl.DeleteAssetGateway)
	g.PUT("/asset/gateway/status", opdef.Middleware(db, opdef.Must("PUT", "/asset/gateway/status")), ctl.UpdateAssetGatewayStatus)
	g.POST("/asset/gateway/test", opdef.Middleware(db, opdef.Must("POST", "/asset/gateway/test")), ctl.TestAssetGatewayConnection)

	g.GET("/asset/database/list", ctl.GetAssetDatabaseList)
	g.GET("/asset/database/info", ctl.GetAssetDatabaseInfo)
	g.GET("/asset/database/metrics", ctl.GetAssetDatabaseMetrics)
	g.POST("/asset/database/add", opdef.Middleware(db, opdef.Must("POST", "/asset/database/add")), ctl.CreateAssetDatabase)
	g.PUT("/asset/database/update", opdef.Middleware(db, opdef.Must("PUT", "/asset/database/update")), ctl.UpdateAssetDatabase)
	g.DELETE("/asset/database/delete", opdef.Middleware(db, opdef.Must("DELETE", "/asset/database/delete")), ctl.DeleteAssetDatabase)
	g.POST("/asset/database/test", opdef.Middleware(db, opdef.Must("POST", "/asset/database/test")), ctl.TestAssetDatabaseConnection)

	g.GET("/dbms/workbench", ctl.GetDatabaseWorkbench)
	g.GET("/dbms/schema/tree", ctl.GetDatabaseSchemaTree)
	g.POST("/dbms/schema/create", opdef.Middleware(db, opdef.Must("POST", "/dbms/schema/create")), ctl.CreateDatabaseSchema)
	g.GET("/dbms/charset/options", ctl.GetDatabaseCharsetOptions)
	g.GET("/dbms/table/data", ctl.GetDatabaseTableData)
	g.GET("/dbms/resource/data", ctl.GetDatabaseResourceData)
	g.POST("/dbms/sql/execute", opdef.Middleware(db, opdef.Must("POST", "/dbms/sql/execute")), ctl.ExecuteDatabaseSQL)
	g.POST("/dbms/sql/analyze", opdef.Middleware(db, opdef.Must("POST", "/dbms/sql/analyze")), ctl.AnalyzeDatabaseSQL)
	g.POST("/dbms/redis/analyze", opdef.Middleware(db, opdef.Must("POST", "/dbms/redis/analyze")), ctl.AnalyzeRedisCommand)
	g.POST("/dbms/redis/execute", opdef.Middleware(db, opdef.Must("POST", "/dbms/redis/execute")), ctl.ExecuteRedisCommand)
	g.GET("/dbms/sql/history", ctl.GetDatabaseSQLHistory)
	g.POST("/dbms/table/row/insert", opdef.Middleware(db, opdef.Must("POST", "/dbms/table/row/insert")), ctl.InsertDatabaseTableRow)
	g.PUT("/dbms/table/row/update", opdef.Middleware(db, opdef.Must("PUT", "/dbms/table/row/update")), ctl.UpdateDatabaseTableRow)
	g.DELETE("/dbms/table/row/delete", opdef.Middleware(db, opdef.Must("DELETE", "/dbms/table/row/delete")), ctl.DeleteDatabaseTableRow)
	g.POST("/dbms/task/export", opdef.Middleware(db, opdef.Must("POST", "/dbms/task/export")), ctl.CreateExportTask)
	g.POST("/dbms/task/import", opdef.Middleware(db, opdef.Must("POST", "/dbms/task/import")), ctl.CreateImportTask)
	g.POST("/dbms/task/import/precheck", opdef.Middleware(db, opdef.Must("POST", "/dbms/task/import/precheck")), ctl.PrecheckImportTask)
	g.POST("/dbms/task/batch-sql", opdef.Middleware(db, opdef.Must("POST", "/dbms/task/batch-sql")), ctl.CreateBatchSQLTask)
	g.GET("/dbms/task/list", ctl.GetTransferTaskList)
	g.GET("/dbms/task/download", opdef.Middleware(db, opdef.Must("GET", "/dbms/task/download")), ctl.DownloadTransferTask)
	g.GET("/dbms/backup/plan/list", ctl.GetDatabaseBackupPlanList)
	g.POST("/dbms/backup/plan/save", opdef.Middleware(db, opdef.Must("POST", "/dbms/backup/plan/save")), ctl.SaveDatabaseBackupPlan)
	g.DELETE("/dbms/backup/plan/delete", opdef.Middleware(db, opdef.Must("DELETE", "/dbms/backup/plan/delete")), ctl.DeleteDatabaseBackupPlan)
	g.POST("/dbms/backup/plan/run", opdef.Middleware(db, opdef.Must("POST", "/dbms/backup/plan/run")), ctl.RunDatabaseBackupPlan)
	g.POST("/dbms/backup/manual", opdef.Middleware(db, opdef.Must("POST", "/dbms/backup/manual")), ctl.RunManualDatabaseBackup)
	g.GET("/dbms/backup/record/list", ctl.GetDatabaseBackupRecordList)
	g.GET("/dbms/backup/download", opdef.Middleware(db, opdef.Must("GET", "/dbms/backup/download")), ctl.DownloadDatabaseBackup)
	g.POST("/dbms/backup/import", opdef.Middleware(db, opdef.Must("POST", "/dbms/backup/import")), ctl.CreateDatabaseBackupImportTask)

	g.GET("/monitor/overview", ctl.GetMonitorOverview)
	g.GET("/monitor/command-center", ctl.GetMonitorCommandCenter)
	g.GET("/monitor/datasource/list", opdef.Middleware(db, opdef.Must("GET", "/monitor/datasource/list")), ctl.GetMonitorDatasourceList)
	g.GET("/monitor/datasource/options", opdef.Middleware(db, opdef.Must("GET", "/monitor/datasource/options")), ctl.GetMonitorDatasourceOptions)
	g.GET("/monitor/datasource/info", opdef.Middleware(db, opdef.Must("GET", "/monitor/datasource/info")), ctl.GetMonitorDatasourceInfo)
	g.POST("/monitor/datasource/save", opdef.Middleware(db, opdef.Must("POST", "/monitor/datasource/save")), ctl.SaveMonitorDatasource)
	g.DELETE("/monitor/datasource/delete", opdef.Middleware(db, opdef.Must("DELETE", "/monitor/datasource/delete")), ctl.DeleteMonitorDatasource)
	g.POST("/monitor/datasource/test", opdef.Middleware(db, opdef.Must("POST", "/monitor/datasource/test")), ctl.TestMonitorDatasource)
	g.POST("/monitor/query/instant", opdef.Middleware(db, opdef.Must("POST", "/monitor/query/instant")), ctl.QueryMonitorPrometheus)
	g.POST("/monitor/query/range", opdef.Middleware(db, opdef.Must("POST", "/monitor/query/range")), ctl.QueryMonitorPrometheusRange)
	g.POST("/monitor/logs/query", opdef.Middleware(db, opdef.Must("POST", "/monitor/logs/query")), ctl.QueryMonitorLogs)
	g.GET("/monitor/logs/indices", ctl.GetMonitorElasticsearchIndices)
	g.GET("/monitor/logs/streams", ctl.GetMonitorVictoriaLogsStreams)
	g.GET("/monitor/logs/fields", ctl.GetMonitorLogFields)
	g.GET("/monitor/logs/field-values", ctl.GetMonitorLogFieldValues)
	g.GET("/monitor/logs/shortcuts", ctl.GetMonitorLogShortcuts)
	g.POST("/monitor/logs/shortcuts/save", opdef.Middleware(db, opdef.Must("POST", "/monitor/logs/shortcuts/save")), ctl.SaveMonitorLogShortcut)
	g.DELETE("/monitor/logs/shortcuts/delete", opdef.Middleware(db, opdef.Must("DELETE", "/monitor/logs/shortcuts/delete")), ctl.DeleteMonitorLogShortcut)
	g.GET("/monitor/traces/services", ctl.GetMonitorJaegerServices)
	g.GET("/monitor/traces/operations", ctl.GetMonitorJaegerOperations)
	g.POST("/monitor/traces/query", opdef.Middleware(db, opdef.Must("POST", "/monitor/traces/query")), ctl.QueryMonitorTraces)
	g.GET("/monitor/traces/detail", ctl.GetMonitorTrace)
	g.GET("/monitor/query/history", ctl.GetMonitorQueryHistoryList)
	g.GET("/monitor/alert/template/list", ctl.GetMonitorAlertTemplateList)
	g.GET("/monitor/alert/template/groups", ctl.GetMonitorAlertTemplateGroups)
	g.POST("/monitor/alert/template/group/save", opdef.Middleware(db, opdef.Must("POST", "/monitor/alert/template/group/save")), ctl.SaveMonitorAlertTemplateGroup)
	g.DELETE("/monitor/alert/template/group/delete", opdef.Middleware(db, opdef.Must("DELETE", "/monitor/alert/template/group/delete")), ctl.DeleteMonitorAlertTemplateGroup)
	g.GET("/monitor/alert/template/info", ctl.GetMonitorAlertTemplateInfo)
	g.POST("/monitor/alert/template/save", opdef.Middleware(db, opdef.Must("POST", "/monitor/alert/template/save")), ctl.SaveMonitorAlertTemplate)
	g.DELETE("/monitor/alert/template/delete", opdef.Middleware(db, opdef.Must("DELETE", "/monitor/alert/template/delete")), ctl.DeleteMonitorAlertTemplate)
	g.POST("/monitor/alert/template/prometheus/parse", opdef.Middleware(db, opdef.Must("POST", "/monitor/alert/template/prometheus/parse")), ctl.ParsePrometheusAlertTemplates)
	g.POST("/monitor/alert/template/prometheus/import", opdef.Middleware(db, opdef.Must("POST", "/monitor/alert/template/prometheus/import")), ctl.ImportPrometheusAlertTemplates)
	g.POST("/monitor/alert/template/prometheus/export", opdef.Middleware(db, opdef.Must("POST", "/monitor/alert/template/prometheus/export")), ctl.ExportPrometheusAlertTemplates)
	g.GET("/monitor/alert/rule/list", ctl.GetMonitorAlertRuleList)
	g.GET("/monitor/alert/rule/info", ctl.GetMonitorAlertRuleInfo)
	g.POST("/monitor/alert/rule/save", opdef.Middleware(db, opdef.Must("POST", "/monitor/alert/rule/save")), ctl.SaveMonitorAlertRule)
	g.DELETE("/monitor/alert/rule/delete", opdef.Middleware(db, opdef.Must("DELETE", "/monitor/alert/rule/delete")), ctl.DeleteMonitorAlertRule)
	g.PUT("/monitor/alert/rule/status", opdef.Middleware(db, opdef.Must("PUT", "/monitor/alert/rule/status")), ctl.UpdateMonitorAlertRuleStatus)
	g.POST("/monitor/alert/rule/batch", opdef.Middleware(db, opdef.Must("POST", "/monitor/alert/rule/batch")), ctl.BatchUpdateMonitorAlertRules)
	g.POST("/monitor/alert/rule/run", opdef.Middleware(db, opdef.Must("POST", "/monitor/alert/rule/run")), ctl.RunMonitorAlertRule)
	g.POST("/monitor/alert/rule/preview", opdef.Middleware(db, opdef.Must("POST", "/monitor/alert/rule/preview")), ctl.PreviewMonitorAlertRule)
	g.GET("/monitor/silence/rule/list", ctl.GetMonitorSilenceRuleList)
	g.GET("/monitor/silence/rule/info", ctl.GetMonitorSilenceRuleInfo)
	g.POST("/monitor/silence/rule/save", opdef.Middleware(db, opdef.Must("POST", "/monitor/silence/rule/save")), ctl.SaveMonitorSilenceRule)
	g.POST("/monitor/silence/rule/preview", opdef.Middleware(db, opdef.Must("POST", "/monitor/silence/rule/preview")), ctl.PreviewMonitorSilenceRule)
	g.DELETE("/monitor/silence/rule/delete", opdef.Middleware(db, opdef.Must("DELETE", "/monitor/silence/rule/delete")), ctl.DeleteMonitorSilenceRule)
	g.POST("/monitor/silence/rule/batch", opdef.Middleware(db, opdef.Must("POST", "/monitor/silence/rule/batch")), ctl.BatchUpdateMonitorSilenceRules)
	g.GET("/monitor/aggregation/rule/list", ctl.GetMonitorAggregationRuleList)
	g.GET("/monitor/aggregation/rule/info", ctl.GetMonitorAggregationRuleInfo)
	g.POST("/monitor/aggregation/rule/save", opdef.Middleware(db, opdef.Must("POST", "/monitor/aggregation/rule/save")), ctl.SaveMonitorAggregationRule)
	g.DELETE("/monitor/aggregation/rule/delete", opdef.Middleware(db, opdef.Must("DELETE", "/monitor/aggregation/rule/delete")), ctl.DeleteMonitorAggregationRule)
	g.POST("/monitor/aggregation/rule/batch", opdef.Middleware(db, opdef.Must("POST", "/monitor/aggregation/rule/batch")), ctl.BatchUpdateMonitorAggregationRules)
	g.GET("/monitor/alert/event/list", ctl.GetMonitorAlertEventList)
	g.GET("/monitor/alert/event/detail", ctl.GetMonitorAlertEventDetail)
	g.POST("/monitor/alert/event/claim", opdef.Middleware(db, opdef.Must("POST", "/monitor/alert/event/claim")), ctl.ClaimMonitorAlertEvent)
	g.POST("/monitor/alert/event/resolve", opdef.Middleware(db, opdef.Must("POST", "/monitor/alert/event/resolve")), ctl.ResolveMonitorAlertEvent)
	g.POST("/monitor/alert/event/batch", opdef.Middleware(db, opdef.Must("POST", "/monitor/alert/event/batch")), ctl.BatchUpdateMonitorAlertEvents)
	g.POST("/monitor/alert/event/action", opdef.Middleware(db, opdef.Must("POST", "/monitor/alert/event/action")), ctl.TriggerMonitorAlertAction)
	g.GET("/monitor/dashboard/list", ctl.GetMonitorDashboardList)
	g.GET("/monitor/dashboard/info", ctl.GetMonitorDashboardInfo)
	g.POST("/monitor/dashboard/save", opdef.Middleware(db, opdef.Must("POST", "/monitor/dashboard/save")), ctl.SaveMonitorDashboard)
	g.DELETE("/monitor/dashboard/delete", opdef.Middleware(db, opdef.Must("DELETE", "/monitor/dashboard/delete")), ctl.DeleteMonitorDashboard)
	g.POST("/monitor/dashboard/panel/save", opdef.Middleware(db, opdef.Must("POST", "/monitor/dashboard/panel/save")), ctl.SaveMonitorDashboardPanel)
	g.DELETE("/monitor/dashboard/panel/delete", opdef.Middleware(db, opdef.Must("DELETE", "/monitor/dashboard/panel/delete")), ctl.DeleteMonitorDashboardPanel)
	g.POST("/monitor/dashboard/panel/query", opdef.Middleware(db, opdef.Must("POST", "/monitor/dashboard/panel/query")), ctl.QueryMonitorDashboardPanel)
	g.GET("/k8s/cluster/list", opdef.Middleware(db, opdef.Must("GET", "/k8s/cluster/list")), ctl.GetK8sClusterList)
	g.GET("/k8s/cluster/info", opdef.Middleware(db, opdef.Must("GET", "/k8s/cluster/info")), ctl.GetK8sClusterInfo)
	g.GET("/k8s/cluster/detail", opdef.Middleware(db, opdef.Must("GET", "/k8s/cluster/detail")), ctl.GetK8sClusterDetail)
	g.GET("/k8s/node/detail", ctl.GetK8sNodeDetail)
	g.GET("/k8s/node/pods", ctl.GetK8sNodePods)
	g.GET("/k8s/namespace/detail", ctl.GetK8sNamespaceDetail)
	g.GET("/k8s/namespace/events", ctl.GetK8sNamespaceEvents)
	g.GET("/k8s/service/detail", ctl.GetK8sServiceDetail)
	g.GET("/k8s/ingress/detail", ctl.GetK8sIngressDetail)
	g.GET("/k8s/istio/detail", ctl.GetK8sIstioResourceDetail)
	g.GET("/k8s/configmap/detail", opdef.Middleware(db, opdef.Must("GET", "/k8s/configmap/detail")), ctl.GetK8sConfigMapDetail)
	g.GET("/k8s/secret/detail", opdef.Middleware(db, opdef.Must("GET", "/k8s/secret/detail")), ctl.GetK8sSecretDetail)
	g.GET("/k8s/storage/detail", ctl.GetK8sStorageDetail)
	g.GET("/k8s/pod/detail", ctl.GetK8sPodDetail)
	g.GET("/k8s/pod/metrics", ctl.GetK8sPodMetrics)
	g.GET("/k8s/workload/metrics", ctl.GetK8sWorkloadMetrics)
	g.GET("/k8s/pod/containers", ctl.GetK8sPodContainers)
	g.GET("/k8s/pod/logs", opdef.Middleware(db, opdef.Must("GET", "/k8s/pod/logs")), ctl.GetK8sPodLogs)
	g.GET("/k8s/pod/events", ctl.GetK8sPodEvents)
	g.GET("/k8s/workload/detail", ctl.GetK8sWorkloadDetail)
}
