package router

import (
	"ops-admin/backend/controller"
	"ops-admin/backend/opdef"

	"github.com/gin-gonic/gin"
	"gorm.io/gorm"
)

// registerOps mounts the ops-domain v1 routes on the authenticated api
// group: integration (navigation, AI, finops) and the ops tree (script,
// exec, schedule, job, environment, application incl. build/release/
// pipeline). Phase A pure move from router.go — route statements are
// verbatim; only the group receiver name and one indentation level changed.
// Group construction and the group-level middlewares stay in router.go
// (plan §J1).
func registerOps(g *gin.RouterGroup, db *gorm.DB, ctl *controller.Controller) {
	g.GET("/integration/navigation/group/list", opdef.Middleware(db, opdef.Must("GET", "/integration/navigation/group/list")), ctl.GetIntegrationNavigationGroupList)
	g.POST("/integration/navigation/group/save", opdef.Middleware(db, opdef.Must("POST", "/integration/navigation/group/save")), ctl.SaveIntegrationNavigationGroup)
	g.DELETE("/integration/navigation/group/delete", opdef.Middleware(db, opdef.Must("DELETE", "/integration/navigation/group/delete")), ctl.DeleteIntegrationNavigationGroup)
	g.POST("/integration/navigation/group/token", opdef.Middleware(db, opdef.Must("POST", "/integration/navigation/group/token")), ctl.RegenerateIntegrationPublicToken)
	g.GET("/integration/navigation/list", opdef.Middleware(db, opdef.Must("GET", "/integration/navigation/list")), ctl.GetIntegrationNavigationList)
	g.POST("/integration/navigation/save", opdef.Middleware(db, opdef.Must("POST", "/integration/navigation/save")), ctl.SaveIntegrationNavigation)
	g.DELETE("/integration/navigation/delete", opdef.Middleware(db, opdef.Must("DELETE", "/integration/navigation/delete")), ctl.DeleteIntegrationNavigation)
	g.GET("/integration/ai/model/list", ctl.GetIntegrationAIModelList)
	g.POST("/integration/ai/model/save", opdef.Middleware(db, opdef.Must("POST", "/integration/ai/model/save")), ctl.SaveIntegrationAIModel)
	g.DELETE("/integration/ai/model/delete", opdef.Middleware(db, opdef.Must("DELETE", "/integration/ai/model/delete")), ctl.DeleteIntegrationAIModel)
	g.POST("/integration/ai/model/test", opdef.Middleware(db, opdef.Must("POST", "/integration/ai/model/test")), ctl.TestIntegrationAIModel)
	g.GET("/integration/ai/conversation/list", ctl.GetIntegrationAIConversationList)
	g.GET("/integration/ai/conversation/detail", ctl.GetIntegrationAIConversationDetail)
	g.POST("/integration/ai/conversation/save", opdef.Middleware(db, opdef.Must("POST", "/integration/ai/conversation/save")), ctl.SaveIntegrationAIConversation)
	g.DELETE("/integration/ai/conversation/delete", opdef.Middleware(db, opdef.Must("DELETE", "/integration/ai/conversation/delete")), ctl.DeleteIntegrationAIConversation)
	g.POST("/integration/ai/chat/send", opdef.Middleware(db, opdef.Must("POST", "/integration/ai/chat/send")), ctl.SendIntegrationAIChat)
	g.GET("/integration/ai/knowledge-base/list", ctl.GetIntegrationAIKnowledgeDocumentList)
	g.POST("/integration/ai/knowledge-base/save", opdef.Middleware(db, opdef.Must("POST", "/integration/ai/knowledge-base/save")), ctl.SaveIntegrationAIKnowledgeDocument)
	g.POST("/integration/ai/knowledge-base/upload", opdef.Middleware(db, opdef.Must("POST", "/integration/ai/knowledge-base/upload")), ctl.UploadIntegrationAIKnowledgeDocument)
	g.DELETE("/integration/ai/knowledge-base/delete", opdef.Middleware(db, opdef.Must("DELETE", "/integration/ai/knowledge-base/delete")), ctl.DeleteIntegrationAIKnowledgeDocument)
	g.GET("/integration/ai/tool/list", ctl.GetIntegrationAIToolList)
	g.PUT("/integration/ai/tool/update", opdef.Middleware(db, opdef.Must("PUT", "/integration/ai/tool/update")), ctl.UpdateIntegrationAITool)
	g.POST("/integration/ai/tool/execute", opdef.Middleware(db, opdef.Must("POST", "/integration/ai/tool/execute")), ctl.ExecuteIntegrationAITool)
	g.POST("/integration/ai/action/confirm", opdef.Middleware(db, opdef.Must("POST", "/integration/ai/action/confirm")), ctl.ConfirmIntegrationAIAction)
	g.POST("/integration/ai/action/reject", opdef.Middleware(db, opdef.Must("POST", "/integration/ai/action/reject")), ctl.RejectIntegrationAIAction)
	g.GET("/integration/finops/account/list", ctl.GetFinOpsAccountList)
	g.POST("/integration/finops/account/save", opdef.Middleware(db, opdef.Must("POST", "/integration/finops/account/save")), ctl.SaveFinOpsAccount)
	g.DELETE("/integration/finops/account/delete", opdef.Middleware(db, opdef.Must("DELETE", "/integration/finops/account/delete")), ctl.DeleteFinOpsAccount)
	g.POST("/integration/finops/account/test", opdef.Middleware(db, opdef.Must("POST", "/integration/finops/account/test")), ctl.TestFinOpsAccount)
	g.GET("/integration/finops/dashboard", ctl.GetFinOpsDashboard)
	g.GET("/integration/finops/breakdown", ctl.GetFinOpsBreakdown)
	g.GET("/integration/finops/breakdown/latest-month", ctl.GetFinOpsLatestBreakdownMonth)
	g.GET("/integration/finops/resource/list", ctl.GetFinOpsResources)
	g.GET("/integration/finops/recommendation/list", ctl.GetFinOpsRecommendationList)
	g.POST("/integration/finops/recommendation/generate", opdef.Middleware(db, opdef.Must("POST", "/integration/finops/recommendation/generate")), ctl.GenerateFinOpsRecommendations)
	g.PUT("/integration/finops/recommendation/status", opdef.Middleware(db, opdef.Must("PUT", "/integration/finops/recommendation/status")), ctl.UpdateFinOpsRecommendation)
	g.DELETE("/integration/finops/recommendation/delete", opdef.Middleware(db, opdef.Must("DELETE", "/integration/finops/recommendation/delete")), ctl.DeleteFinOpsRecommendation)
	g.GET("/integration/finops/sync/logs", ctl.GetFinOpsSyncLogs)
	g.POST("/integration/finops/sync/trigger", opdef.Middleware(db, opdef.Must("POST", "/integration/finops/sync/trigger")), ctl.TriggerFinOpsSync)
	g.POST("/integration/finops/cost/import", opdef.Middleware(db, opdef.Must("POST", "/integration/finops/cost/import")), ctl.ImportFinOpsCosts)

	g.GET("/ops/script/list", ctl.GetOpsScriptList)
	g.GET("/ops/script/options", ctl.GetOpsScriptOptions)
	g.GET("/ops/script/info", ctl.GetOpsScriptInfo)
	g.POST("/ops/script/add", opdef.Middleware(db, opdef.Must("POST", "/ops/script/add")), ctl.CreateOpsScript)
	g.PUT("/ops/script/update", opdef.Middleware(db, opdef.Must("PUT", "/ops/script/update")), ctl.UpdateOpsScript)
	g.PUT("/ops/script/status", opdef.Middleware(db, opdef.Must("PUT", "/ops/script/status")), ctl.UpdateOpsScriptStatus)
	g.GET("/ops/script/versions", ctl.GetOpsScriptVersions)
	g.POST("/ops/script/rollback", opdef.Middleware(db, opdef.Must("POST", "/ops/script/rollback")), ctl.RollbackOpsScript)
	g.DELETE("/ops/script/delete", opdef.Middleware(db, opdef.Must("DELETE", "/ops/script/delete")), ctl.DeleteOpsScript)
	g.POST("/ops/exec/command", opdef.Middleware(db, opdef.Must("POST", "/ops/exec/command")), ctl.ExecuteOpsCommand)
	g.POST("/ops/exec/script", opdef.Middleware(db, opdef.Must("POST", "/ops/exec/script")), ctl.ExecuteOpsScript)
	g.POST("/ops/exec/file-dispatch", opdef.Middleware(db, opdef.Must("POST", "/ops/exec/file-dispatch")), ctl.ExecuteOpsFileDispatch)
	g.GET("/ops/exec/history", ctl.GetOpsExecTaskList)
	g.GET("/ops/exec/history/detail", ctl.GetOpsExecTaskDetail)
	g.POST("/ops/exec/retry", opdef.Middleware(db, opdef.Must("POST", "/ops/exec/retry")), ctl.RetryOpsExecTask)
	g.GET("/ops/schedule/task/list", ctl.GetOpsScheduleTaskList)
	g.GET("/ops/schedule/task/info", ctl.GetOpsScheduleTaskInfo)
	g.POST("/ops/schedule/task/add", opdef.Middleware(db, opdef.Must("POST", "/ops/schedule/task/add")), ctl.CreateOpsScheduleTask)
	g.PUT("/ops/schedule/task/update", opdef.Middleware(db, opdef.Must("PUT", "/ops/schedule/task/update")), ctl.UpdateOpsScheduleTask)
	g.PUT("/ops/schedule/task/status", opdef.Middleware(db, opdef.Must("PUT", "/ops/schedule/task/status")), ctl.UpdateOpsScheduleTaskStatus)
	g.POST("/ops/schedule/task/run", opdef.Middleware(db, opdef.Must("POST", "/ops/schedule/task/run")), ctl.RunOpsScheduleTask)
	g.DELETE("/ops/schedule/task/delete", opdef.Middleware(db, opdef.Must("DELETE", "/ops/schedule/task/delete")), ctl.DeleteOpsScheduleTask)
	g.DELETE("/ops/schedule/task/batch/delete", opdef.Middleware(db, opdef.Must("DELETE", "/ops/schedule/task/batch/delete")), ctl.BatchDeleteOpsScheduleTask)
	g.GET("/ops/schedule/log/list", ctl.GetOpsScheduleLogList)
	g.GET("/ops/schedule/log/info", ctl.GetOpsScheduleLogInfo)
	g.GET("/ops/schedule/template/list", ctl.GetOpsScheduleTemplateList)
	g.GET("/ops/schedule/template/info", ctl.GetOpsScheduleTemplateInfo)
	g.POST("/ops/schedule/template/add", opdef.Middleware(db, opdef.Must("POST", "/ops/schedule/template/add")), ctl.CreateOpsScheduleTemplate)
	g.PUT("/ops/schedule/template/update", opdef.Middleware(db, opdef.Must("PUT", "/ops/schedule/template/update")), ctl.UpdateOpsScheduleTemplate)
	g.DELETE("/ops/schedule/template/delete", opdef.Middleware(db, opdef.Must("DELETE", "/ops/schedule/template/delete")), ctl.DeleteOpsScheduleTemplate)
	g.GET("/ops/job/list", ctl.GetOpsJobList)
	g.GET("/ops/job/info", ctl.GetOpsJobInfo)
	g.POST("/ops/job/add", opdef.Middleware(db, opdef.Must("POST", "/ops/job/add")), ctl.CreateOpsJob)
	g.PUT("/ops/job/update", opdef.Middleware(db, opdef.Must("PUT", "/ops/job/update")), ctl.UpdateOpsJob)
	g.POST("/ops/job/run", opdef.Middleware(db, opdef.Must("POST", "/ops/job/run")), ctl.RunOpsJob)
	g.PUT("/ops/job/status", opdef.Middleware(db, opdef.Must("PUT", "/ops/job/status")), ctl.UpdateOpsJobStatus)
	g.DELETE("/ops/job/delete", opdef.Middleware(db, opdef.Must("DELETE", "/ops/job/delete")), ctl.DeleteOpsJob)
	g.GET("/ops/job/history/list", ctl.GetOpsJobHistoryList)
	g.GET("/ops/job/history/detail", ctl.GetOpsJobHistoryDetail)
	g.POST("/ops/job/history/approve", opdef.Middleware(db, opdef.Must("POST", "/ops/job/history/approve")), ctl.ApproveOpsJobHistory)
	g.POST("/ops/job/history/reject", opdef.Middleware(db, opdef.Must("POST", "/ops/job/history/reject")), ctl.RejectOpsJobHistory)
	g.GET("/ops/job/template/list", ctl.GetOpsJobTemplateList)
	g.GET("/ops/job/template/options", ctl.GetOpsJobTemplateOptions)
	g.GET("/ops/job/template/info", ctl.GetOpsJobTemplateInfo)
	g.POST("/ops/job/template/add", opdef.Middleware(db, opdef.Must("POST", "/ops/job/template/add")), ctl.CreateOpsJobTemplate)
	g.PUT("/ops/job/template/update", opdef.Middleware(db, opdef.Must("PUT", "/ops/job/template/update")), ctl.UpdateOpsJobTemplate)
	g.PUT("/ops/job/template/status", opdef.Middleware(db, opdef.Must("PUT", "/ops/job/template/status")), ctl.UpdateOpsJobTemplateStatus)
	g.DELETE("/ops/job/template/delete", opdef.Middleware(db, opdef.Must("DELETE", "/ops/job/template/delete")), ctl.DeleteOpsJobTemplate)
	g.GET("/ops/environment/list", ctl.GetOpsEnvironmentList)
	g.POST("/ops/environment/save", opdef.Middleware(db, opdef.Must("POST", "/ops/environment/save")), ctl.SaveOpsEnvironment)
	g.DELETE("/ops/environment/delete", opdef.Middleware(db, opdef.Must("DELETE", "/ops/environment/delete")), ctl.DeleteOpsEnvironment)
	g.GET("/ops/application/list", ctl.GetOpsApplicationList)
	g.GET("/ops/application/options", ctl.GetOpsApplicationOptions)
	g.GET("/ops/application/info", ctl.GetOpsApplicationInfo)
	g.GET("/ops/application/bindings", ctl.GetOpsApplicationBindings)
	g.POST("/ops/application/save", opdef.Middleware(db, opdef.Must("POST", "/ops/application/save")), ctl.SaveOpsApplication)
	g.DELETE("/ops/application/delete", opdef.Middleware(db, opdef.Must("DELETE", "/ops/application/delete")), ctl.DeleteOpsApplication)
	g.GET("/ops/application/build-task/list", ctl.GetOpsAppBuildTaskList)
	g.GET("/ops/application/build-task/info", ctl.GetOpsAppBuildTaskInfo)
	g.POST("/ops/application/build-task/save", opdef.Middleware(db, opdef.Must("POST", "/ops/application/build-task/save")), ctl.SaveOpsAppBuildTask)
	g.PUT("/ops/application/build-task/status", opdef.Middleware(db, opdef.Must("PUT", "/ops/application/build-task/status")), ctl.UpdateOpsAppBuildTaskStatus)
	g.DELETE("/ops/application/build-task/delete", opdef.Middleware(db, opdef.Must("DELETE", "/ops/application/build-task/delete")), ctl.DeleteOpsAppBuildTask)
	g.POST("/ops/application/build-task/run", opdef.Middleware(db, opdef.Must("POST", "/ops/application/build-task/run")), ctl.RunOpsAppBuildTask)
	g.POST("/ops/application/release/run", opdef.Middleware(db, opdef.Must("POST", "/ops/application/release/run")), ctl.RunOpsAppRelease)
	g.POST("/ops/application/release/retry", opdef.Middleware(db, opdef.Must("POST", "/ops/application/release/retry")), ctl.RetryOpsAppRelease)
	g.GET("/ops/application/release/list", ctl.GetOpsAppReleaseList)
	g.GET("/ops/application/release/info", ctl.GetOpsAppReleaseInfo)
	g.GET("/ops/application/artifact/list", ctl.GetOpsAppArtifactList)
	g.GET("/ops/application/image-registry/list", ctl.GetOpsImageRegistryList)
	g.POST("/ops/application/image-registry/save", opdef.Middleware(db, opdef.Must("POST", "/ops/application/image-registry/save")), ctl.SaveOpsImageRegistry)
	g.DELETE("/ops/application/image-registry/delete", opdef.Middleware(db, opdef.Must("DELETE", "/ops/application/image-registry/delete")), ctl.DeleteOpsImageRegistry)
	g.GET("/ops/application/pipeline/template/list", ctl.GetOpsAppPipelineTemplateList)
	g.GET("/ops/application/pipeline/list", ctl.GetOpsAppPipelineList)
	g.GET("/ops/application/pipeline/info", ctl.GetOpsAppPipelineInfo)
	g.POST("/ops/application/pipeline/save", opdef.Middleware(db, opdef.Must("POST", "/ops/application/pipeline/save")), ctl.SaveOpsAppPipeline)
	g.PUT("/ops/application/pipeline/status", opdef.Middleware(db, opdef.Must("PUT", "/ops/application/pipeline/status")), ctl.UpdateOpsAppPipelineStatus)
	g.DELETE("/ops/application/pipeline/delete", opdef.Middleware(db, opdef.Must("DELETE", "/ops/application/pipeline/delete")), ctl.DeleteOpsAppPipeline)
	g.POST("/ops/application/pipeline/copy", opdef.Middleware(db, opdef.Must("POST", "/ops/application/pipeline/copy")), ctl.CopyOpsAppPipeline)
	g.POST("/ops/application/pipeline/run", opdef.Middleware(db, opdef.Must("POST", "/ops/application/pipeline/run")), ctl.RunOpsAppPipeline)
	g.GET("/ops/application/pipeline/run/list", ctl.GetOpsAppPipelineRunList)
	g.GET("/ops/application/pipeline/run/info", ctl.GetOpsAppPipelineRunInfo)
	g.POST("/ops/application/pipeline/run/approve", opdef.Middleware(db, opdef.Must("POST", "/ops/application/pipeline/run/approve")), ctl.ApproveOpsAppPipelineRun)
	g.POST("/ops/application/pipeline/run/rollback", opdef.Middleware(db, opdef.Must("POST", "/ops/application/pipeline/run/rollback")), ctl.RollbackOpsAppPipelineRun)
}
