import http from './http'

export const queryDNSAccounts = (params) => http.get('/api/v1/domain/public/accounts', { params })
export const queryDNSAccountOptions = () => http.get('/api/v1/domain/public/accounts/options')
export const getDNSAccount = (id) => http.get('/api/v1/domain/public/accounts/detail', { params: { id } })
export const saveDNSAccount = (data) => http.post('/api/v1/domain/public/accounts/save', data)
export const deleteDNSAccount = (id) => http.delete('/api/v1/domain/public/accounts/delete', { data: { id } })
export const testDNSAccount = (id) => http.post('/api/v1/domain/public/accounts/test', { id }, { timeout: 30000 })
export const queryPublicDomains = (params) => http.get('/api/v1/domain/public/domains', { params })
export const syncPublicDomains = (accountId = 0) => http.post('/api/v1/domain/public/domains/sync', { accountId }, { timeout: 60000 })
export const queryPublicRecords = (params) => http.get('/api/v1/domain/public/records', { params, timeout: 30000 })
export const mutatePublicRecord = (data) => http.post('/api/v1/domain/public/records/mutate', data, { timeout: 30000 })
export const batchPublicRecords = (data) => http.post('/api/v1/domain/public/records/batch', data, { timeout: 120000 })

export const getInternalDNSSettings = () => http.get('/api/v1/domain/internal/settings')
export const saveInternalDNSSettings = (data) => http.put('/api/v1/domain/internal/settings', data)
export const queryInternalZones = (params) => http.get('/api/v1/domain/internal/zones', { params })
export const saveInternalZone = (data) => http.post('/api/v1/domain/internal/zones/save', data)
export const deleteInternalZone = (id) => http.delete('/api/v1/domain/internal/zones/delete', { data: { id } })
export const queryInternalRecords = (params) => http.get('/api/v1/domain/internal/records', { params })
export const saveInternalRecord = (data) => http.post('/api/v1/domain/internal/records/save', data)
export const deleteInternalRecord = (id) => http.delete('/api/v1/domain/internal/records/delete', { data: { id } })
export const batchInternalRecords = (data) => http.post('/api/v1/domain/internal/records/batch', data)
export const testDNSResolution = (data) => http.post('/api/v1/domain/internal/query', data, { timeout: 10000 })
export const queryDNSAudit = (params) => http.get('/api/v1/domain/audit', { params })

export const querySSLCertificates = (params) => http.get('/api/v1/domain/public/certificates', { params })
export const getSSLCertificate = (id) => http.get('/api/v1/domain/public/certificates/detail', { params: { id } })
export const querySSLCertificateDomainOptions = () => http.get('/api/v1/domain/public/certificates/domain-options')
export const syncSSLCertificates = (accountId = 0) => http.post('/api/v1/domain/public/certificates/sync', { accountId })
export const uploadSSLCertificate = (data) => http.post('/api/v1/domain/public/certificates/upload', data, { timeout: 30000 })
export const applySSLCertificate = (data) => http.post('/api/v1/domain/public/certificates/apply', data)
export const renewSSLCertificate = (id) => http.post('/api/v1/domain/public/certificates/renew', { id })
export const resyncSSLCertificate = (id) => http.post('/api/v1/domain/public/certificates/resync', { id })
export const updateSSLCertificateRenewSettings = (data) => http.put('/api/v1/domain/public/certificates/renew-settings', data)
export const deleteSSLCertificate = (data) => http.delete('/api/v1/domain/public/certificates/delete', { data })
export const querySSLCertificateTasks = (params) => http.get('/api/v1/domain/public/certificates/tasks', { params })
export const querySSLCertificateAudits = (limit = 100) => http.get('/api/v1/domain/public/certificates/audits', { params: { limit } })
export const downloadSSLCertificate = (id, type = 'certificate', sensitive = false) => http.get(`/api/v1/domain/public/certificates/${sensitive ? 'download-private' : 'download'}`, { params: { id, type }, responseType: 'blob', timeout: 30000 })
