<script setup>
import { onBeforeUnmount, onMounted, reactive, ref } from 'vue'
import { ElMessage } from 'element-plus'
import { queryAssetHostGroupList, queryAssetHostList } from '../../api/asset'
import { executeOpsCommand, queryOpsExecHistoryDetail } from '../../api/ops'
import OpsTargetSelector from './components/OpsTargetSelector.vue'
import OpsExecutionResultDialog from './components/OpsExecutionResultDialog.vue'
import { confirmRiskOperation } from '../../composables/useRiskConfirm'
import { ot } from '../../utils/ops-i18n'

const submitting = ref(false)
const hostOptions = ref([])
const groupOptions = ref([])
const resultVisible = ref(false)
const resultLoading = ref(false)
const resultTask = ref(null)
const resultRows = ref([])
let pollTimer = null

const form = reactive({
  title: '',
  commandText: '',
  hostIds: [],
  groupId: undefined,
  concurrency: 5,
  timeoutSeconds: 10
})

async function loadOptions() {
  const [hosts, groups] = await Promise.all([
    queryAssetHostList({ pageNum: 1, pageSize: 1000 }),
    queryAssetHostGroupList()
  ])
  hostOptions.value = hosts.list || []
  groupOptions.value = groups.tree || []
}

async function submit() {
  if (!form.commandText.trim()) {
    ElMessage.warning(ot('commandRequired'))
    return
  }
  if (!form.hostIds.length && !form.groupId) {
    ElMessage.warning(ot('targetRequired'))
    return
  }
  const highRisk = /rm\s+-rf|mkfs|shutdown|reboot|init\s+[06]|dd\s+if=|iptables\s+-f|systemctl\s+stop|userdel|drop\s+database|truncate\s+table/i.test(form.commandText)
  const selectedHosts = hostOptions.value.filter((host) => {
    if (form.groupId) {
      return Number(host.groupId) === Number(form.groupId) || (host.hostGroups || []).some((group) => Number(group.id) === Number(form.groupId))
    }
    return form.hostIds.map(Number).includes(Number(host.id))
  })
  const includesProduction = selectedHosts.some((host) => ['prod', 'production'].includes(String(host.environment || '').toLowerCase()) || String(host.environment || '').includes('\u751f\u4ea7'))
  const confirmationRequired = highRisk || includesProduction
  if (confirmationRequired) {
    await confirmRiskOperation({
      operation: ot('batchCommandExecution'),
      targetSummary: selectedHosts.length ? selectedHosts.map((host) => host.hostName || host.sshIp || host.id).slice(0, 4).join(', ') : ot('selectedHostGroup'),
      targetCount: selectedHosts.length,
      production: includesProduction,
      destructive: highRisk
    })
  }
  submitting.value = true
  resultVisible.value = true
  resultLoading.value = true
  resultTask.value = {
    title: form.title || ot('commandTask'),
    taskType: 'command',
    status: 'running',
    summary: ot('executingPleaseWait')
  }
  resultRows.value = []
  try {
    const data = await executeOpsCommand({
      title: form.title,
      commandText: form.commandText,
      hostIds: form.hostIds,
      groupIds: form.groupId ? [form.groupId] : [],
      concurrency: form.concurrency,
      timeoutSeconds: form.timeoutSeconds,
      riskConfirmed: confirmationRequired
    })
    resultTask.value = data.task || null
    resultRows.value = data.results || []
    startPolling()
  } finally {
    submitting.value = false
  }
}

async function refreshTaskDetail() {
  if (!resultTask.value?.id) return
  const data = await queryOpsExecHistoryDetail(resultTask.value.id)
  resultTask.value = data.task || null
  resultRows.value = data.results || []
  resultLoading.value = false
  if (resultTask.value?.status && resultTask.value.status !== 'running') {
    stopPolling()
  }
}

function startPolling() {
  stopPolling()
  refreshTaskDetail().catch(() => {})
  pollTimer = setInterval(() => {
    refreshTaskDetail().catch(() => {})
  }, 1200)
}

function stopPolling() {
  if (pollTimer) {
    clearInterval(pollTimer)
    pollTimer = null
  }
}

function handleResultClosed() {
  stopPolling()
  if (resultTask.value?.id) {
    ElMessage.info(ot('resultSavedToHistory'))
  }
}

onMounted(loadOptions)
onBeforeUnmount(stopPolling)
</script>

<template>
  <div class="page-card ops-page">
    <div class="page-header">
      <div>
        <h2 class="page-title">{{ ot('commandExecution') }}</h2>
        <p class="page-desc">{{ ot('commandExecutionDesc') }}</p>
      </div>
    </div>

    <el-form label-width="110px">
      <el-form-item :label="ot('taskName')">
        <el-input v-model="form.title" :placeholder="ot('optionalAutoGenerated')" />
      </el-form-item>
      <el-form-item :label="ot('command')" required>
        <el-input v-model="form.commandText" type="textarea" :rows="10" :placeholder="ot('commandExample')" />
      </el-form-item>
      <OpsTargetSelector
        :host-options="hostOptions"
        :group-options="groupOptions"
        :host-ids="form.hostIds"
        :group-id="form.groupId"
        @update:host-ids="form.hostIds = $event"
        @update:group-id="form.groupId = $event"
      />
      <el-form-item :label="ot('concurrency')">
        <el-input-number v-model="form.concurrency" :min="1" :max="10" />
      </el-form-item>
      <el-form-item :label="ot('timeout')">
        <el-input-number v-model="form.timeoutSeconds" :min="10" :max="3600" />
        <span class="inline-hint">{{ ot('timeoutHint') }}</span>
      </el-form-item>
      <el-form-item>
        <el-button type="primary" :loading="submitting" @click="submit">{{ ot('executeNow') }}</el-button>
      </el-form-item>
    </el-form>
    <OpsExecutionResultDialog
      v-model="resultVisible"
      :loading="resultLoading"
      :task="resultTask"
      :results="resultRows"
      @closed="handleResultClosed"
    />
  </div>
</template>

<style scoped>
.ops-page { display: flex; flex-direction: column; gap: 18px; }
.page-title { margin: 0 0 8px; font-size: 22px; font-weight: 700; color: #14213d; }
.page-desc { margin: 0; color: #7282a0; }
.inline-hint { margin-left: 12px; color: #7282a0; font-size: 13px; }
</style>
