<script setup>
import { onMounted, reactive, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { getInternalDNSSettings, saveInternalDNSSettings } from '../../api/domain'
const loading=ref(false),saving=ref(false),status=ref({}),form=reactive({enabled:false,listenAddress:'0.0.0.0',listenPort:53,upstreams:['223.5.5.5','119.29.29.29','180.76.76.76','114.114.114.114','223.112.112.112'],timeoutSeconds:2})
async function load(){loading.value=true;try{const data=await getInternalDNSSettings();Object.assign(form,data.settings||{});form.listenPort=53;status.value=data.status||{}}finally{loading.value=false}}
async function save(){form.listenPort=53;if(form.enabled){await ElMessageBox.confirm(`启用后将监听 ${form.listenAddress}:53 的 UDP 与 TCP 端口。`,'确认启用内网 DNS',{type:'warning'})}saving.value=true;try{await saveInternalDNSSettings(form);ElMessage.success(form.enabled?'内网 DNS 已启用':'DNS 设置已保存');await load()}catch(error){ElMessage.error(`DNS 启动失败：${error.message}`)}finally{saving.value=false}}
onMounted(load)
</script>
<template><section v-loading="loading" class="domain-page domain-panel page-card">
  <div class="domain-page-head"><div><div class="domain-eyebrow">DNS RUNTIME SETTINGS</div><h2>内网 DNS 设置</h2><p>默认关闭。启用时同时监听 UDP 与 TCP；端口占用或权限不足会明确报错并保持关闭。</p></div><span class="dns-state" :class="{'is-running':status.running,'is-error':status.lastError}">{{status.running?'Running':status.lastError?'启动失败':'Stopped'}}</span></div>
  <el-alert v-if="status.lastError" type="error" :closable="false" show-icon :title="status.lastError"/>
  <div class="domain-settings-grid"><el-form label-position="top"><el-form-item label="启用内网 DNS"><el-switch v-model="form.enabled" active-text="启用" inactive-text="关闭"/></el-form-item><div class="settings-row"><el-form-item label="监听地址"><el-input v-model="form.listenAddress" placeholder="0.0.0.0"/></el-form-item><el-form-item label="监听端口"><el-input model-value="53" readonly><template #suffix><span class="fixed-port-label">固定端口</span></template></el-input></el-form-item></div><el-form-item label="上游 DNS"><el-select v-model="form.upstreams" multiple filterable allow-create default-first-option style="width:100%" placeholder="输入 IP 后回车"><el-option label="阿里公共 DNS 223.5.5.5" value="223.5.5.5"/><el-option label="DNSPod 119.29.29.29" value="119.29.29.29"/><el-option label="百度云 180.76.76.76" value="180.76.76.76"/><el-option label="电信 114.114.114.114" value="114.114.114.114"/><el-option label="移动 223.112.112.112" value="223.112.112.112"/></el-select><div class="domain-form-tip">按顺序尝试；第一个超时或失败时自动切换下一个。</div></el-form-item><el-form-item label="单个上游请求超时"><el-input-number v-model="form.timeoutSeconds" :min="1" :max="30"/><span style="margin-left:8px;color:#64748b">秒</span></el-form-item><el-button type="primary" :loading="saving" @click="save">保存 DNS 设置</el-button></el-form>
    <aside class="runtime-card"><h3>运行状态</h3><dl><div><dt>UDP</dt><dd><span class="dns-state" :class="{'is-running':status.udpRunning}">{{status.udpRunning?'Running':'Stopped'}}</span></dd></div><div><dt>TCP</dt><dd><span class="dns-state" :class="{'is-running':status.tcpRunning}">{{status.tcpRunning?'Running':'Stopped'}}</span></dd></div><div><dt>监听地址</dt><dd class="domain-mono">{{status.listenAddress||`${form.listenAddress}:${form.listenPort}`}}</dd></div><div><dt>Zone / 记录</dt><dd>{{status.zoneCount||0}} / {{status.recordCount||0}}</dd></div><div><dt>缓存刷新</dt><dd>{{status.lastCacheRefresh||'—'}}</dd></div></dl><el-alert type="info" :closable="false" title="Linux 监听 53 端口请为平台二进制配置 CAP_NET_BIND_SERVICE，无需让整个进程以 root 运行。"/></aside>
  </div>
</section></template>
<style scoped>.domain-settings-grid{display:grid;grid-template-columns:minmax(0,1fr) 360px;gap:24px}.settings-row{display:grid;grid-template-columns:1fr 180px;gap:12px}.fixed-port-label{color:#64748b;font-size:12px}.runtime-card{padding:18px;border:1px solid #e4ecfc;border-radius:12px;background:#f8faff}.runtime-card h3{margin:0 0 14px}.runtime-card dl{display:grid;gap:12px;margin:0 0 18px}.runtime-card dl div{display:flex;justify-content:space-between;gap:12px}.runtime-card dt{color:#64748b}.runtime-card dd{margin:0;color:#0f172a;font-weight:650;text-align:right}@media(max-width:900px){.domain-settings-grid{grid-template-columns:1fr}}@media(max-width:520px){.settings-row{grid-template-columns:1fr}}</style>
