<script setup>
import { computed, onMounted, reactive, ref } from 'vue'
import { useRouter } from 'vue-router'
import { ElMessage, ElMessageBox } from 'element-plus'
import { deleteInternalZone, getInternalDNSSettings, queryInternalZones, saveInternalZone } from '../../api/domain'
import { dt } from '../../utils/domain-i18n'
const router=useRouter(),loading=ref(false),zones=ref([]),dialogVisible=ref(false),saving=ref(false),runtime=ref({}),settings=ref({enabled:false}),settingsReady=ref(false),query=reactive({keyword:''}),form=reactive({id:0,name:'',description:'',status:1})
const dnsEnabled=computed(()=>Boolean(runtime.value.running))
async function loadZones(){loading.value=true;try{zones.value=(await queryInternalZones(query))||[]}finally{loading.value=false}}
async function loadSettings(){try{const data=await getInternalDNSSettings();settings.value=data.settings||{enabled:false};runtime.value=data.status||{}}finally{settingsReady.value=true}}
async function load(){await Promise.allSettled([loadZones(),loadSettings()])}
function create(){Object.assign(form,{id:0,name:'',description:'',status:1});dialogVisible.value=true}
function edit(row){Object.assign(form,row);dialogVisible.value=true}
async function save(){if(!form.name.trim()){ElMessage.warning(dt('zoneNameRequired'));return}saving.value=true;try{await saveInternalZone(form);ElMessage.success(dt('zoneSaved'));dialogVisible.value=false;await loadZones()}finally{saving.value=false}}
async function remove(row){await ElMessageBox.confirm(dt('deleteZoneConfirm',{name:row.name}),dt('deleteZoneTitle'),{type:'warning'});await deleteInternalZone(row.id);ElMessage.success(dt('zoneDeleted'));await loadZones()}
onMounted(load)
</script>
<template><section class="domain-page domain-panel page-card">
  <div class="domain-page-head"><div><div class="domain-eyebrow">PRIVATE DNS ZONES</div><h2>{{dt('zoneManagement')}}</h2><p>{{dt('zoneManagementDesc')}}</p></div><div><el-button @click="router.push('/domains/internal/settings')">{{dt('dnsSettings')}}</el-button><el-button v-permission="'domains:internal:zone:add'" type="primary" @click="create">{{dt('createZone')}}</el-button></div></div>
  <div class="domain-stat-grid"><div class="domain-stat"><div class="domain-stat__label">{{dt('dnsStatus')}}</div><div style="margin-top:12px"><span class="dns-state" :class="{'is-running':runtime.running,'is-error':runtime.lastError}">{{!settingsReady?dt('checking'):runtime.running?'Running':runtime.lastError?dt('startFailed'):dt('stopped')}}</span></div></div><div class="domain-stat"><div class="domain-stat__label">{{dt('listenAddress')}}</div><div class="domain-stat__value domain-mono" style="font-size:18px">{{runtime.listenAddress||'0.0.0.0:53'}}</div></div><div class="domain-stat"><div class="domain-stat__label">{{dt('zoneCount')}}</div><div class="domain-stat__value">{{runtime.zoneCount||zones.length}}</div></div><div class="domain-stat"><div class="domain-stat__label">{{dt('enabledRecords')}}</div><div class="domain-stat__value">{{runtime.recordCount||0}}</div></div></div>
  <el-alert v-if="runtime.lastError" type="error" :closable="false" :title="runtime.lastError" show-icon/>
  <div v-if="settingsReady&&!dnsEnabled&&!runtime.lastError" class="dns-setup-notice" role="status"><div><strong>{{settings.enabled?dt('dnsNotRunning'):dt('enableDnsFirst')}}</strong><p>{{settings.enabled?dt('dnsNotRunningDesc'):dt('enableDnsFirstDesc')}}</p></div><el-button type="primary" @click="router.push('/domains/internal/settings')">{{dt('goToDnsSettings')}}</el-button></div>
  <div class="domain-toolbar" role="search"><div class="domain-toolbar__filters"><el-input v-model="query.keyword" clearable :placeholder="dt('searchZone')" style="width:260px" @keyup.enter="loadZones"/><el-button @click="loadZones">{{dt('search')}}</el-button></div><div class="domain-toolbar__actions"><el-button :disabled="!dnsEnabled" @click="router.push('/domains/query-test')">{{dt('resolutionTest')}}</el-button></div></div>
  <div class="domain-table-wrap"><el-table v-loading="loading" :data="zones" border><el-table-column prop="name" :label="dt('zoneName')" min-width="230"><template #default="{row}"><el-button link type="primary" class="domain-mono" @click="router.push(`/domains/internal/zones/${row.id}/records`)">{{row.name}}</el-button></template></el-table-column><el-table-column prop="description" :label="dt('description')" min-width="220"/><el-table-column prop="recordCount" :label="dt('recordCount')" width="110"/><el-table-column :label="dt('status')" width="100"><template #default="{row}"><el-tag :type="row.status===1?'success':'info'">{{row.status===1?dt('enabled'):dt('disabled')}}</el-tag></template></el-table-column><el-table-column prop="updatedAt" :label="dt('updatedAt')" width="180"/><el-table-column :label="dt('actions')" width="190" fixed="right"><template #default="{row}"><el-button link type="primary" @click="router.push(`/domains/internal/zones/${row.id}/records`)">{{dt('dnsRecords')}}</el-button><el-button v-permission="'domains:internal:zone:edit'" link @click="edit(row)">{{dt('edit')}}</el-button><el-button v-permission="'domains:internal:zone:delete'" link type="danger" @click="remove(row)">{{dt('delete')}}</el-button></template></el-table-column><template #empty><div class="domain-empty"><strong>{{dt('noZones')}}</strong><p>{{dnsEnabled?dt('noZonesEnabledDesc'):dt('noZonesDisabledDesc')}}</p><el-button v-permission="'domains:internal:zone:add'" type="primary" @click="create">{{dt('createZone')}}</el-button></div></template></el-table></div>
  <el-dialog v-model="dialogVisible" :title="form.id?dt('editZone'):dt('createZone')" width="min(560px, calc(100vw - 32px))"><el-form label-width="92px"><el-form-item :label="dt('zoneName')" required><el-input v-model="form.name" placeholder="ops.internal"/><div class="domain-form-tip">{{dt('normalizeZoneHint')}}</div></el-form-item><el-form-item :label="dt('description')"><el-input v-model="form.description" type="textarea" :rows="3"/></el-form-item><el-form-item :label="dt('status')"><el-switch v-model="form.status" :active-value="1" :inactive-value="2" :active-text="dt('enable')" :inactive-text="dt('disable')"/></el-form-item></el-form><template #footer><el-button @click="dialogVisible=false">{{dt('cancel')}}</el-button><el-button type="primary" :loading="saving" @click="save">{{dt('saveZone')}}</el-button></template></el-dialog>
</section></template>
