<script setup>
import { computed, onMounted, reactive, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { ElMessage, ElMessageBox } from 'element-plus'
import { batchPublicRecords, mutatePublicRecord, queryPublicRecords } from '../../api/domain'
import { dt } from '../../utils/domain-i18n'
const route=useRoute(),router=useRouter(),loading=ref(false),dialogVisible=ref(false),saving=ref(false),records=ref([]),selection=ref([]),batchVisible=ref(false),batchResult=ref(null)
const accountId=computed(()=>Number(route.params.accountId)),domain=computed(()=>decodeURIComponent(route.params.domain))
const batchActionLabel=computed(()=>({enable:dt('batchEnable'),disable:dt('batchDisable'),delete:dt('batchDelete'),ttl:dt('batchTtl'),value:dt('batchValue')}[batch.action]||dt('batchActions')))
const query=reactive({keyword:'',type:''});const form=reactive({recordId:'',host:'',type:'A',value:'',ttl:600,line:'default'});const batch=reactive({action:'disable',ttl:600,value:''})
const filtered=computed(()=>records.value.filter(item=>(!query.keyword||`${item.host} ${item.value}`.toLowerCase().includes(query.keyword.toLowerCase()))&&(!query.type||item.type===query.type)))
async function load(){loading.value=true;try{records.value=await queryPublicRecords({accountId:accountId.value,domain:domain.value})}finally{loading.value=false}}
function openCreate(){Object.assign(form,{recordId:'',host:'',type:'A',value:'',ttl:600,line:'default'});dialogVisible.value=true}
function openEdit(row){Object.assign(form,{recordId:row.id,host:row.host,type:row.type,value:row.value,ttl:row.ttl,line:row.line});dialogVisible.value=true}
async function save(){if(!form.host.trim()||!form.value.trim()){ElMessage.warning(dt('hostValueRequired'));return}saving.value=true;try{await mutatePublicRecord({accountId:accountId.value,action:form.recordId?'update':'create',record:{...form,domain:domain.value}});ElMessage.success(dt('recordSaved'));dialogVisible.value=false;await load()}finally{saving.value=false}}
async function action(row,name){if(name==='delete')await ElMessageBox.confirm(dt('deleteRecordConfirm',{host:row.host,domain:domain.value}),dt('deleteDnsRecord'),{type:'warning'});await mutatePublicRecord({accountId:accountId.value,action:name,record:{...row,recordId:row.id,domain:domain.value}});ElMessage.success(dt('operationCompleted'));await load()}
async function runBatch(){const payload={accountId:accountId.value,domain:domain.value,action:batch.action,ttl:batch.ttl,value:batch.value,records:selection.value.map(row=>({...row,recordId:row.id}))};const result=await batchPublicRecords(payload);batchResult.value=result;ElMessage[result.failureCount?'warning':'success'](dt('batchResult',{success:result.successCount,failure:result.failureCount}));await load()}
onMounted(load)
</script>
<template><section class="domain-page domain-panel page-card">
  <div class="domain-page-head"><div><div class="domain-eyebrow">PUBLIC DNS RECORDS</div><h2 class="domain-mono">{{domain}}</h2><p>{{dt('publicRecordDesc')}}</p></div><div><el-button @click="router.push('/domains/public')">{{dt('backToDomainList')}}</el-button><el-button v-permission="'domains:public:record'" type="primary" @click="openCreate">{{dt('addDnsRecord')}}</el-button></div></div>
  <div class="domain-toolbar" role="search"><div class="domain-toolbar__filters"><el-input v-model="query.keyword" clearable :placeholder="dt('searchHostValue')" style="width:260px"/><el-select v-model="query.type" clearable :placeholder="dt('recordType')" style="width:140px"><el-option v-for="type in ['A','AAAA','CNAME','MX','TXT','SRV','NS','CAA']" :key="type" :label="type" :value="type"/></el-select><el-button :loading="loading" @click="load">{{dt('refresh')}}</el-button></div></div>
  <div v-if="selection.length" v-permission="'domains:public:batch'" class="domain-batch-bar"><strong>{{dt('selectedRecords',{count:selection.length})}}</strong><div><el-button @click="batch.action='enable';batchVisible=true">{{dt('batchEnable')}}</el-button><el-button @click="batch.action='disable';batchVisible=true">{{dt('batchDisable')}}</el-button><el-button @click="batch.action='ttl';batchVisible=true">{{dt('batchTtl')}}</el-button><el-button @click="batch.action='value';batchVisible=true">{{dt('batchValue')}}</el-button><el-button type="danger" @click="batch.action='delete';batchVisible=true">{{dt('batchDelete')}}</el-button></div></div>
  <div class="domain-table-wrap"><el-table v-loading="loading" :data="filtered" border @selection-change="selection=$event"><el-table-column type="selection" width="48"/><el-table-column prop="host" :label="dt('hostRecord')" min-width="150"><template #default="{row}"><span class="domain-mono">{{row.host}}</span></template></el-table-column><el-table-column prop="type" :label="dt('type')" width="90"/><el-table-column prop="value" :label="dt('recordValue')" min-width="260"><template #default="{row}"><span class="domain-mono">{{row.value}}</span></template></el-table-column><el-table-column prop="ttl" label="TTL" width="90"/><el-table-column prop="line" :label="dt('line')" width="130"/><el-table-column :label="dt('status')" width="100"><template #default="{row}"><el-tag :type="['enable','enabled'].includes(row.status)?'success':'info'">{{['enable','enabled'].includes(row.status)?dt('enabled'):dt('disabled')}}</el-tag></template></el-table-column><el-table-column :label="dt('actions')" width="220" fixed="right"><template #default="{row}"><span v-permission="'domains:public:record'"><el-button link type="primary" @click="openEdit(row)">{{dt('edit')}}</el-button><el-button link :type="['enable','enabled'].includes(row.status)?'warning':'success'" @click="action(row,['enable','enabled'].includes(row.status)?'disable':'enable')">{{['enable','enabled'].includes(row.status)?dt('disable'):dt('enable')}}</el-button><el-button link type="danger" @click="action(row,'delete')">{{dt('delete')}}</el-button></span></template></el-table-column></el-table></div>
  <el-dialog v-model="dialogVisible" :title="form.recordId?dt('editDnsRecord'):dt('addDnsRecord')" width="min(620px, calc(100vw - 32px))"><el-form label-width="96px"><el-form-item :label="dt('domain')"><el-input :model-value="domain" disabled/></el-form-item><el-form-item :label="dt('hostRecord')" required><el-input v-model="form.host" :placeholder="dt('exampleHost')"/></el-form-item><el-form-item :label="dt('recordType')" required><el-select v-model="form.type" style="width:100%"><el-option v-for="type in ['A','AAAA','CNAME','MX','TXT','SRV','NS','CAA']" :key="type" :label="type" :value="type"/></el-select></el-form-item><el-form-item :label="dt('recordValue')" required><el-input v-model="form.value" type="textarea" :rows="2"/></el-form-item><el-form-item label="TTL"><el-input-number v-model="form.ttl" :min="1" :max="86400" style="width:100%"/></el-form-item><el-form-item :label="dt('line')"><el-input v-model="form.line" :placeholder="dt('linePlaceholder')"/></el-form-item></el-form><template #footer><el-button @click="dialogVisible=false">{{dt('cancel')}}</el-button><el-button type="primary" :loading="saving" @click="save">{{dt('saveRecord')}}</el-button></template></el-dialog>
  <el-dialog v-model="batchVisible" :title="dt('batchActions')" width="min(560px, calc(100vw - 32px))"><el-alert v-if="batch.action==='delete'" type="warning" :closable="false" :title="dt('deleteBatchWarning')"/><el-form label-width="110px" style="margin-top:16px"><el-form-item :label="dt('operation')"><strong>{{batchActionLabel}}</strong></el-form-item><el-form-item v-if="batch.action==='ttl'" :label="dt('newTtl')"><el-input-number v-model="batch.ttl" :min="1" :max="86400"/></el-form-item><el-form-item v-if="batch.action==='value'" :label="dt('newRecordValue')"><el-input v-model="batch.value"/></el-form-item></el-form><div v-if="batchResult" class="domain-result-list"><div v-for="item in batchResult.results" :key="item.recordId" class="domain-result-item"><span>{{item.host}}</span><el-tag :type="item.success?'success':'danger'">{{item.success?dt('success'):item.error}}</el-tag></div></div><template #footer><el-button @click="batchVisible=false">{{dt('close')}}</el-button><el-button type="primary" @click="runBatch">{{dt('executeRecords',{count:selection.length})}}</el-button></template></el-dialog>
</section></template>
