<script setup>
import { computed, onMounted, reactive, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { ElMessage, ElMessageBox } from 'element-plus'
import { batchPublicRecords, mutatePublicRecord, queryPublicRecords } from '../../api/domain'
const route=useRoute(),router=useRouter(),loading=ref(false),dialogVisible=ref(false),saving=ref(false),records=ref([]),selection=ref([]),batchVisible=ref(false),batchResult=ref(null)
const accountId=computed(()=>Number(route.params.accountId)),domain=computed(()=>decodeURIComponent(route.params.domain))
const batchActionLabel=computed(()=>({enable:'批量启用',disable:'批量禁用',delete:'批量删除',ttl:'批量修改 TTL',value:'批量修改记录值'}[batch.action]||'批量操作'))
const query=reactive({keyword:'',type:''});const form=reactive({recordId:'',host:'',type:'A',value:'',ttl:600,line:'default'});const batch=reactive({action:'disable',ttl:600,value:''})
const filtered=computed(()=>records.value.filter(item=>(!query.keyword||`${item.host} ${item.value}`.toLowerCase().includes(query.keyword.toLowerCase()))&&(!query.type||item.type===query.type)))
async function load(){loading.value=true;try{records.value=await queryPublicRecords({accountId:accountId.value,domain:domain.value})}finally{loading.value=false}}
function openCreate(){Object.assign(form,{recordId:'',host:'',type:'A',value:'',ttl:600,line:'default'});dialogVisible.value=true}
function openEdit(row){Object.assign(form,{recordId:row.id,host:row.host,type:row.type,value:row.value,ttl:row.ttl,line:row.line});dialogVisible.value=true}
async function save(){if(!form.host.trim()||!form.value.trim()){ElMessage.warning('请填写主机记录和记录值');return}saving.value=true;try{await mutatePublicRecord({accountId:accountId.value,action:form.recordId?'update':'create',record:{...form,domain:domain.value}});ElMessage.success('解析记录已保存');dialogVisible.value=false;await load()}finally{saving.value=false}}
async function action(row,name){if(name==='delete')await ElMessageBox.confirm(`确认删除 ${row.host}.${domain.value}？`,'删除解析记录',{type:'warning'});await mutatePublicRecord({accountId:accountId.value,action:name,record:{...row,recordId:row.id,domain:domain.value}});ElMessage.success('操作完成');await load()}
async function runBatch(){const payload={accountId:accountId.value,domain:domain.value,action:batch.action,ttl:batch.ttl,value:batch.value,records:selection.value.map(row=>({...row,recordId:row.id}))};const result=await batchPublicRecords(payload);batchResult.value=result;ElMessage[result.failureCount?'warning':'success'](`成功 ${result.successCount} 条，失败 ${result.failureCount} 条`);await load()}
onMounted(load)
</script>
<template><section class="domain-page domain-panel page-card">
  <div class="domain-page-head"><div><div class="domain-eyebrow">PUBLIC DNS RECORDS</div><h2 class="domain-mono">{{domain}}</h2><p>记录变更直接提交到云厂商 API；批量任务会保留每一条成功或失败结果。</p></div><div><el-button @click="router.push('/domains/public')">返回域名列表</el-button><el-button v-permission="'domains:public:record'" type="primary" @click="openCreate">新增解析记录</el-button></div></div>
  <div class="domain-toolbar" role="search"><div class="domain-toolbar__filters"><el-input v-model="query.keyword" clearable placeholder="搜索主机记录 / 记录值" style="width:260px"/><el-select v-model="query.type" clearable placeholder="记录类型" style="width:140px"><el-option v-for="type in ['A','AAAA','CNAME','MX','TXT','SRV','NS','CAA']" :key="type" :label="type" :value="type"/></el-select><el-button :loading="loading" @click="load">刷新</el-button></div></div>
  <div v-if="selection.length" v-permission="'domains:public:batch'" class="domain-batch-bar"><strong>已选择 {{selection.length}} 条记录</strong><div><el-button @click="batch.action='enable';batchVisible=true">批量启用</el-button><el-button @click="batch.action='disable';batchVisible=true">批量禁用</el-button><el-button @click="batch.action='ttl';batchVisible=true">修改 TTL</el-button><el-button @click="batch.action='value';batchVisible=true">修改记录值</el-button><el-button type="danger" @click="batch.action='delete';batchVisible=true">批量删除</el-button></div></div>
  <div class="domain-table-wrap"><el-table v-loading="loading" :data="filtered" border @selection-change="selection=$event"><el-table-column type="selection" width="48"/><el-table-column prop="host" label="主机记录" min-width="150"><template #default="{row}"><span class="domain-mono">{{row.host}}</span></template></el-table-column><el-table-column prop="type" label="类型" width="90"/><el-table-column prop="value" label="记录值" min-width="260"><template #default="{row}"><span class="domain-mono">{{row.value}}</span></template></el-table-column><el-table-column prop="ttl" label="TTL" width="90"/><el-table-column prop="line" label="线路" width="130"/><el-table-column label="状态" width="100"><template #default="{row}"><el-tag :type="['enable','enabled'].includes(row.status)?'success':'info'">{{['enable','enabled'].includes(row.status)?'启用':'禁用'}}</el-tag></template></el-table-column><el-table-column label="操作" width="220" fixed="right"><template #default="{row}"><span v-permission="'domains:public:record'"><el-button link type="primary" @click="openEdit(row)">编辑</el-button><el-button link :type="['enable','enabled'].includes(row.status)?'warning':'success'" @click="action(row,['enable','enabled'].includes(row.status)?'disable':'enable')">{{['enable','enabled'].includes(row.status)?'禁用':'启用'}}</el-button><el-button link type="danger" @click="action(row,'delete')">删除</el-button></span></template></el-table-column></el-table></div>
  <el-dialog v-model="dialogVisible" :title="form.recordId?'编辑解析记录':'新增解析记录'" width="min(620px, calc(100vw - 32px))"><el-form label-width="96px"><el-form-item label="域名"><el-input :model-value="domain" disabled/></el-form-item><el-form-item label="主机记录" required><el-input v-model="form.host" placeholder="例如 www 或 @"/></el-form-item><el-form-item label="记录类型" required><el-select v-model="form.type" style="width:100%"><el-option v-for="type in ['A','AAAA','CNAME','MX','TXT','SRV','NS','CAA']" :key="type" :label="type" :value="type"/></el-select></el-form-item><el-form-item label="记录值" required><el-input v-model="form.value" type="textarea" :rows="2"/></el-form-item><el-form-item label="TTL"><el-input-number v-model="form.ttl" :min="1" :max="86400" style="width:100%"/></el-form-item><el-form-item label="线路"><el-input v-model="form.line" placeholder="default / 默认"/></el-form-item></el-form><template #footer><el-button @click="dialogVisible=false">取消</el-button><el-button type="primary" :loading="saving" @click="save">保存记录</el-button></template></el-dialog>
  <el-dialog v-model="batchVisible" title="批量操作" width="min(560px, calc(100vw - 32px))"><el-alert v-if="batch.action==='delete'" type="warning" :closable="false" title="删除后无法恢复，将逐条提交云厂商。"/><el-form label-width="110px" style="margin-top:16px"><el-form-item label="操作"><strong>{{batchActionLabel}}</strong></el-form-item><el-form-item v-if="batch.action==='ttl'" label="新 TTL"><el-input-number v-model="batch.ttl" :min="1" :max="86400"/></el-form-item><el-form-item v-if="batch.action==='value'" label="新记录值"><el-input v-model="batch.value"/></el-form-item></el-form><div v-if="batchResult" class="domain-result-list"><div v-for="item in batchResult.results" :key="item.recordId" class="domain-result-item"><span>{{item.host}}</span><el-tag :type="item.success?'success':'danger'">{{item.success?'成功':item.error}}</el-tag></div></div><template #footer><el-button @click="batchVisible=false">关闭</el-button><el-button type="primary" @click="runBatch">执行 {{selection.length}} 条</el-button></template></el-dialog>
</section></template>
