import { currentLocale } from './i18n-runtime'

const ko = {
  selectServiceWorkloadForLogs: 'Service와 Workload를 선택한 뒤 Pod Log를 확인하십시오.', podLogs: 'Pod Log', podLogsHint: '기본값은 최근 200줄이며 최대 최근 1000줄까지 조회할 수 있습니다.', recentLines: '최근 {count}줄', refreshLogs: 'Log 새로고침', noLogContent: '표시할 Log 내용이 없습니다.', selectPodForLogs: 'Pod를 선택하면 최근 200줄의 Log를 불러옵니다.', noDatabaseConnection: '사용 가능한 Database 연결이 없습니다. Database 목록에서 연결을 먼저 구성하십시오.', enteringDatabaseWorkbench: 'DBMS Workbench로 이동하고 있습니다...', unassignedEnvironment: '환경 미지정', searchDatabaseConnection: 'Database 연결 검색', refreshConnections: '연결 새로고침', refresh: '새로고침', readOnly: '읽기 전용', readWrite: '읽기/쓰기', noDatabaseConnections: 'Database 연결이 없습니다.',
  serviceResourceDetail: 'Service Resource 상세', refreshStatus: '상태 새로고침', selectServiceWorkloadDetail: 'Service와 Workload를 선택한 뒤 Runtime Resource 상세를 확인하십시오.', noMatchingService: '일치하는 Service가 없습니다.', statefulServiceHint: 'Headless Service / Pod DNS를 통해 검색할 수 있습니다.', selectorMismatch: 'Service selector가 Workload label과 일치하지 않습니다.', noStatefulRuntime: 'StatefulSet Runtime 데이터가 없습니다.', currentVersion: '현재 Version', rollbackTarget: '이 Version으로 Rollback', current: '현재', noReplicaSetRuntime: 'ReplicaSet Runtime 데이터가 없습니다.', noStatefulPods: 'StatefulSet Pod가 없습니다.', noRunningPods: '실행 중인 Pod가 없습니다.', rollbackTitle: 'Version Rollback 확인', rollbackConfirm: '{workload}을 ReplicaSet {replicaSet} (revision {revision})으로 Rollback합니다. Kubernetes는 새 Deployment Revision을 생성합니다. 계속하시겠습니까?', confirmRollback: 'Rollback 확인', cancel: '취소', rollbackSubmitted: 'Revision {revision}으로 Rollback을 요청했습니다.'
}

const en = {
  selectServiceWorkloadForLogs: 'Select a service and workload to view Pod logs.', podLogs: 'Pod Logs', podLogsHint: 'The default is the latest 200 lines; up to 1000 recent lines can be retrieved.', recentLines: 'Latest {count} lines', refreshLogs: 'Refresh Logs', noLogContent: 'No log content available.', selectPodForLogs: 'Select a Pod to load the latest 200 log lines.', noDatabaseConnection: 'No database connection is available. Configure a connection in the database list first.', enteringDatabaseWorkbench: 'Opening DBMS Workbench...', unassignedEnvironment: 'Unassigned Environment', searchDatabaseConnection: 'Search database connections', refreshConnections: 'Refresh Connections', refresh: 'Refresh', readOnly: 'Read Only', readWrite: 'Read/Write', noDatabaseConnections: 'No database connections.',
  serviceResourceDetail: 'Service Resource Detail', refreshStatus: 'Refresh Status', selectServiceWorkloadDetail: 'Select a service and workload to view runtime resource details.', noMatchingService: 'No matching Service', statefulServiceHint: 'Discoverable through a Headless Service or Pod DNS.', selectorMismatch: 'The Service selector does not match the workload labels.', noStatefulRuntime: 'No StatefulSet runtime data.', currentVersion: 'Current Version', rollbackTarget: 'Rollback to this version', current: 'Current', noReplicaSetRuntime: 'No ReplicaSet runtime data.', noStatefulPods: 'No StatefulSet Pods.', noRunningPods: 'No running Pods.', rollbackTitle: 'Confirm Version Rollback', rollbackConfirm: 'Rollback {workload} to ReplicaSet {replicaSet} (revision {revision}). Kubernetes will create a new deployment revision. Continue?', confirmRollback: 'Confirm Rollback', cancel: 'Cancel', rollbackSubmitted: 'Rollback to revision {revision} submitted.'
}

export function at(key, params = {}) {
  const dict = currentLocale.value === 'en-US' ? en : ko
  let text = dict[key] || en[key] || key
  Object.entries(params).forEach(([name, value]) => { text = text.replaceAll(`{${name}}`, String(value)) })
  return text
}
