import { currentLocale } from './i18n-runtime'

const ko = {
  selectServiceWorkloadForLogs: 'Service와 Workload를 선택한 뒤 Pod Log를 확인하십시오.', podLogs: 'Pod Log', podLogsHint: '기본값은 최근 200줄이며 최대 최근 1000줄까지 조회할 수 있습니다.', recentLines: '최근 {count}줄', refreshLogs: 'Log 새로고침', noLogContent: '표시할 Log 내용이 없습니다.', selectPodForLogs: 'Pod를 선택하면 최근 200줄의 Log를 불러옵니다.', noDatabaseConnection: '사용 가능한 Database 연결이 없습니다. Database 목록에서 연결을 먼저 구성하십시오.', enteringDatabaseWorkbench: 'DBMS Workbench로 이동하고 있습니다...', unassignedEnvironment: '환경 미지정', searchDatabaseConnection: 'Database 연결 검색', refreshConnections: '연결 새로고침', refresh: '새로고침', readOnly: '읽기 전용', readWrite: '읽기/쓰기', noDatabaseConnections: 'Database 연결이 없습니다.',
  serviceResourceDetail: 'Service Resource 상세', refreshStatus: '상태 새로고침', selectServiceWorkloadDetail: 'Service와 Workload를 선택한 뒤 Runtime Resource 상세를 확인하십시오.', noMatchingService: '일치하는 Service가 없습니다.', statefulServiceHint: 'Headless Service / Pod DNS를 통해 검색할 수 있습니다.', selectorMismatch: 'Service selector가 Workload label과 일치하지 않습니다.', noStatefulRuntime: 'StatefulSet Runtime 데이터가 없습니다.', currentVersion: '현재 Version', rollbackTarget: '이 Version으로 Rollback', current: '현재', noReplicaSetRuntime: 'ReplicaSet Runtime 데이터가 없습니다.', noStatefulPods: 'StatefulSet Pod가 없습니다.', noRunningPods: '실행 중인 Pod가 없습니다.', rollbackTitle: 'Version Rollback 확인', rollbackConfirm: '{workload}을 ReplicaSet {replicaSet} (revision {revision})으로 Rollback합니다. Kubernetes는 새 Deployment Revision을 생성합니다. 계속하시겠습니까?', confirmRollback: 'Rollback 확인', cancel: '취소', rollbackSubmitted: 'Revision {revision}으로 Rollback을 요청했습니다.',
  podMonitoring: 'Pod Monitoring', podMonitoringDesc: 'Pod별 CPU Core와 Memory 사용량을 비교합니다.', lastHour: '최근 1시간', last6Hours: '최근 6시간', last24Hours: '최근 24시간', cpuCoreUsage: 'Pod CPU Core 사용량', cpuUnit: '단위: Core', memoryUsage: 'Pod Memory 사용량', workingSet: 'Working Set', memoryRss: 'RSS', memoryUsageRate: 'Pod Memory 사용률', workingSetLimit: 'Working Set / Memory Limit', networkBandwidth: 'Pod 초당 Network Bandwidth', inboundOutbound: 'Inbound / Outbound Traffic', inbound: 'In', outbound: 'Out', unknownPod: 'Unknown Pod', coreUnit: '{value} Core', trend: '{title} Trend', noMetricsDatasource: '이 Service의 Cluster에 Prometheus 또는 VictoriaMetrics Datasource가 연결되지 않았습니다.', noPodMetrics: '표시할 Pod Monitoring 데이터가 없습니다.',
  dbMetrics: 'Runtime Metrics', dbMetricsDesc: '활성화하면 Database native query로 직접 수집하며 30초마다 갱신합니다. Metric은 이 플랫폼에만 유지됩니다.', last3Hours: '최근 3시간', last12Hours: '최근 12시간', lastDay: '최근 1일', last3Days: '최근 3일', last7Days: '최근 7일', last14Days: '최근 14일', qps: '초당 Query 수', connections: 'Connection 수', runningThreads: 'Running Thread', inboundTraffic: 'Inbound Traffic', outboundTraffic: 'Outbound Traffic', slowQueriesPerSecond: 'Slow Query / sec', uptime: 'Uptime', cacheHitRate: 'Cache Hit Rate', networkTrafficPerSecond: '초당 Network Traffic', slowQueryTrend: 'Slow Query Trend', daysHours: '{days}일 {hours}시간', hoursMinutes: '{hours}시간 {minutes}분', minutes: '{minutes}분', metricCollectionFailed: 'Metric 수집 실패: {message}', start: '시작', end: '종료', monitoringDashboardDisabled: 'Monitoring Dashboard가 비활성화되어 있습니다.', monitoringDashboardDisabledDesc: 'Database 편집 화면에서 Monitoring Dashboard를 활성화하십시오. 활성화하면 저장된 Connection으로 Runtime Metric을 실시간 조회합니다.', databaseMetricsUnavailable: 'Database Metric을 현재 수집할 수 없습니다.'
}

const en = {
  selectServiceWorkloadForLogs: 'Select a service and workload to view Pod logs.', podLogs: 'Pod Logs', podLogsHint: 'The default is the latest 200 lines; up to 1000 recent lines can be retrieved.', recentLines: 'Latest {count} lines', refreshLogs: 'Refresh Logs', noLogContent: 'No log content available.', selectPodForLogs: 'Select a Pod to load the latest 200 log lines.', noDatabaseConnection: 'No database connection is available. Configure a connection in the database list first.', enteringDatabaseWorkbench: 'Opening DBMS Workbench...', unassignedEnvironment: 'Unassigned Environment', searchDatabaseConnection: 'Search database connections', refreshConnections: 'Refresh Connections', refresh: 'Refresh', readOnly: 'Read Only', readWrite: 'Read/Write', noDatabaseConnections: 'No database connections.',
  serviceResourceDetail: 'Service Resource Detail', refreshStatus: 'Refresh Status', selectServiceWorkloadDetail: 'Select a service and workload to view runtime resource details.', noMatchingService: 'No matching Service', statefulServiceHint: 'Discoverable through a Headless Service or Pod DNS.', selectorMismatch: 'The Service selector does not match the workload labels.', noStatefulRuntime: 'No StatefulSet runtime data.', currentVersion: 'Current Version', rollbackTarget: 'Rollback to this version', current: 'Current', noReplicaSetRuntime: 'No ReplicaSet runtime data.', noStatefulPods: 'No StatefulSet Pods.', noRunningPods: 'No running Pods.', rollbackTitle: 'Confirm Version Rollback', rollbackConfirm: 'Rollback {workload} to ReplicaSet {replicaSet} (revision {revision}). Kubernetes will create a new deployment revision. Continue?', confirmRollback: 'Confirm Rollback', cancel: 'Cancel', rollbackSubmitted: 'Rollback to revision {revision} submitted.',
  podMonitoring: 'Pod Monitoring', podMonitoringDesc: 'Compare CPU core and memory usage across Pods.', lastHour: 'Last 1 Hour', last6Hours: 'Last 6 Hours', last24Hours: 'Last 24 Hours', cpuCoreUsage: 'Pod CPU Core Usage', cpuUnit: 'Unit: Core', memoryUsage: 'Pod Memory Usage', workingSet: 'Working Set', memoryRss: 'RSS', memoryUsageRate: 'Pod Memory Usage Rate', workingSetLimit: 'Working Set / Memory Limit', networkBandwidth: 'Pod Network Bandwidth per Second', inboundOutbound: 'Inbound / Outbound Traffic', inbound: 'In', outbound: 'Out', unknownPod: 'Unknown Pod', coreUnit: '{value} Core', trend: '{title} Trend', noMetricsDatasource: 'The service cluster is not bound to a Prometheus or VictoriaMetrics datasource.', noPodMetrics: 'No Pod monitoring data is available.',
  dbMetrics: 'Runtime Metrics', dbMetricsDesc: 'When enabled, metrics are collected directly through native database queries and refreshed every 30 seconds. Metrics remain local to this platform.', last3Hours: 'Last 3 Hours', last12Hours: 'Last 12 Hours', lastDay: 'Last 1 Day', last3Days: 'Last 3 Days', last7Days: 'Last 7 Days', last14Days: 'Last 14 Days', qps: 'Queries per Second', connections: 'Connections', runningThreads: 'Running Threads', inboundTraffic: 'Inbound Traffic', outboundTraffic: 'Outbound Traffic', slowQueriesPerSecond: 'Slow Queries / sec', uptime: 'Uptime', cacheHitRate: 'Cache Hit Rate', networkTrafficPerSecond: 'Network Traffic per Second', slowQueryTrend: 'Slow Query Trend', daysHours: '{days}d {hours}h', hoursMinutes: '{hours}h {minutes}m', minutes: '{minutes}m', metricCollectionFailed: 'Metric collection failed: {message}', start: 'Start', end: 'End', monitoringDashboardDisabled: 'Monitoring Dashboard is disabled.', monitoringDashboardDisabledDesc: 'Enable Monitoring Dashboard on the database edit page. Runtime metrics will then be read through the configured connection.', databaseMetricsUnavailable: 'Database metrics are temporarily unavailable.'
}

export function at(key, params = {}) {
  const dict = currentLocale.value === 'en-US' ? en : ko
  let text = dict[key] || en[key] || key
  Object.entries(params).forEach(([name, value]) => { text = text.replaceAll(`{${name}}`, String(value)) })
  return text
}
