import { currentLocale } from './i18n-runtime'

const ko = {
  auditTitle: '도메인 작업 감사', auditDesc: 'Public/Internal DNS의 작업자, Source, Object, 이전 값, 새 값과 실행 결과를 기록합니다.', refresh: '새로고침', time: '시간', operator: '작업 사용자', sourceIp: 'Source IP', actionType: '작업 유형', domain: '도메인', type: '유형', change: '변경', result: '결과', operationSuccess: '작업 성공', success: '성공', failure: '실패',
  queryTestTitle: 'DNS 조회 테스트', queryTestDesc: '현재 플랫폼의 메모리 snapshot과 upstream forwarding 경로를 사용해 Internal/Public Domain을 테스트하며 MySQL hot path를 읽지 않습니다.', startResolution: '조회 시작', resolutionSuccess: '조회 성공', resolutionFailure: '조회 실패', responseCode: '응답 코드', noAnswers: 'DNS record가 반환되지 않았습니다.', waitingResolution: '조회 대기', waitingResolutionDesc: '결과에 Record Value, TTL, Response Time과 DNS Server를 표시합니다.',
  internalSettingsTitle: 'Internal DNS 설정', internalSettingsDesc: '기본값은 비활성입니다. 활성화하면 UDP/TCP를 동시에 listen하며, port 충돌이나 권한 부족은 명시적으로 오류를 반환하고 비활성 상태를 유지합니다.', enableConfirm: '활성화하면 {address}:53의 UDP/TCP port를 listen합니다.', enableConfirmTitle: 'Internal DNS 활성화 확인', dnsEnabled: 'Internal DNS를 활성화했습니다.', dnsSaved: 'DNS 설정을 저장했습니다.', dnsStartFailed: 'DNS 시작 실패: {message}', startFailed: '시작 실패', stopped: 'Stopped', enableInternalDns: 'Internal DNS 활성화', enable: '활성화', disable: '비활성화', listenAddress: 'Listen Address', listenPort: 'Listen Port', fixedPort: '고정 Port', upstreamDns: 'Upstream DNS', upstreamPlaceholder: 'IP를 입력하고 Enter를 누르십시오.', aliyunPublicDns: 'Aliyun Public DNS 223.5.5.5', baiduCloudDns: 'Baidu Cloud 180.76.76.76', telecomDns: 'Telecom 114.114.114.114', mobileDns: 'Mobile 223.112.112.112', upstreamHint: '순서대로 요청하며 첫 upstream이 timeout 또는 실패하면 다음 upstream으로 전환합니다.', upstreamTimeout: 'Upstream 요청 Timeout', seconds: '초', saveDnsSettings: 'DNS 설정 저장', runtimeStatus: 'Runtime 상태', zoneRecords: 'Zone / Record', cacheRefresh: 'Cache Refresh', capabilityHint: 'Linux에서 53 port를 listen하려면 플랫폼 binary에 CAP_NET_BIND_SERVICE를 설정하십시오. 전체 process를 root로 실행할 필요는 없습니다.',
  publicDomainsTitle: 'Public Domain', publicDomainsDesc: '도메인은 Cloud Provider 공식 API에서만 동기화하며 로컬 수동 생성은 제공하지 않습니다.', syncedDomains: '동기화된 Domain', enabledAccounts: '활성 Account', supportedProviders: '지원 Provider', dataSource: 'Data Source', officialApi: 'Official API', searchDomain: '도메인 검색', cloudAccount: 'Cloud Account', provider: 'Provider', refreshFromCloud: 'Cloud Provider에서 새로고침', syncedCount: '{count}개 도메인을 동기화했습니다.', manageDnsAccounts: 'DNS Account 관리', account: 'Account', recordCount: 'Record 수', status: '상태', healthy: '정상', lastSync: '마지막 동기화', actions: '작업', dnsRecords: 'DNS Record', noSyncedDomains: '동기화된 도메인이 없습니다.', noSyncedDomainsDesc: 'DNS Account를 먼저 설정한 뒤 Cloud Provider에서 도메인 목록을 새로고침하십시오.', configureDnsAccount: 'DNS Account 설정', aliyunDns: 'Aliyun DNS', tencentDnspod: 'Tencent Cloud DNSPod',
  zoneManagement: 'Zone 관리', zoneManagementDesc: 'Internal authoritative Zone과 DNS Record를 통합 관리합니다. Zone 안에서 일치하지 않는 이름은 NXDOMAIN을 반환하며 Public DNS로 유출하지 않습니다.', dnsSettings: 'DNS 설정', createZone: 'Zone 생성', dnsStatus: 'DNS 상태', checking: '확인 중', zoneCount: 'Zone 수', enabledRecords: '활성 Record', dnsNotRunning: 'Internal DNS Service가 현재 실행 중이 아닙니다.', enableDnsFirst: 'Internal DNS Service를 먼저 활성화하십시오.', dnsNotRunningDesc: 'Listen Port와 Runtime 설정을 확인한 뒤 Service를 다시 시작하십시오.', enableDnsFirstDesc: 'Listen Address와 Upstream DNS를 설정하고 Service를 활성화해야 Internal Domain Resolution을 제공할 수 있습니다.', goToDnsSettings: 'DNS 설정으로 이동', searchZone: 'Zone 검색', resolutionTest: 'Resolution Test', zoneName: 'Zone 이름', description: '설명', updatedAt: 'Updated At', edit: '수정', delete: '삭제', noZones: 'Internal Zone이 없습니다.', noZonesEnabledDesc: '첫 Zone을 생성하십시오. 예: ops.internal.', noZonesDisabledDesc: 'Zone은 미리 생성할 수 있습니다. DNS Service를 활성화하면 Record가 즉시 적용됩니다.', editZone: 'Zone 수정', saveZone: 'Zone 저장', zoneNameRequired: 'Zone 이름을 입력하십시오.', zoneSaved: 'Zone을 저장하고 Resolution Cache를 즉시 갱신했습니다.', deleteZoneTitle: 'Zone 삭제', deleteZoneConfirm: 'Zone “{name}”을 삭제하면 모든 DNS Record도 함께 삭제됩니다. 계속하시겠습니까?', zoneDeleted: 'Zone을 삭제했으며 Resolution이 즉시 비활성화되었습니다.', normalizeZoneHint: '저장 시 소문자로 정규화하고 끝의 점을 제거합니다.', cancel: '취소',
  search: '조회', save: '저장', test: '테스트', enabled: '활성', disabled: '비활성'
}

const en = {
  auditTitle: 'Domain Operation Audit', auditDesc: 'Records operators, sources, objects, previous values, new values, and per-item execution results for public and internal DNS changes.', refresh: 'Refresh', time: 'Time', operator: 'Operator', sourceIp: 'Source IP', actionType: 'Action Type', domain: 'Domain', type: 'Type', change: 'Change', result: 'Result', operationSuccess: 'Operation succeeded', success: 'Success', failure: 'Failure',
  queryTestTitle: 'DNS Query Test', queryTestDesc: 'Tests internal or public domains using the platform memory snapshot and upstream forwarding path without reading the MySQL hot path.', startResolution: 'Start Resolution', resolutionSuccess: 'Resolution Succeeded', resolutionFailure: 'Resolution Failed', responseCode: 'Response Code', noAnswers: 'No DNS records were returned.', waitingResolution: 'Waiting for Resolution', waitingResolutionDesc: 'Results show record values, TTL, response time, and the DNS server.',
  internalSettingsTitle: 'Internal DNS Settings', internalSettingsDesc: 'Disabled by default. When enabled, the runtime listens on UDP and TCP; port conflicts or insufficient privileges return explicit errors and keep the service disabled.', enableConfirm: 'Enabling this service will listen on UDP and TCP port {address}:53.', enableConfirmTitle: 'Confirm Internal DNS Enablement', dnsEnabled: 'Internal DNS enabled.', dnsSaved: 'DNS settings saved.', dnsStartFailed: 'DNS startup failed: {message}', startFailed: 'Startup Failed', stopped: 'Stopped', enableInternalDns: 'Enable Internal DNS', enable: 'Enable', disable: 'Disable', listenAddress: 'Listen Address', listenPort: 'Listen Port', fixedPort: 'Fixed Port', upstreamDns: 'Upstream DNS', upstreamPlaceholder: 'Enter an IP address and press Enter.', aliyunPublicDns: 'Aliyun Public DNS 223.5.5.5', baiduCloudDns: 'Baidu Cloud 180.76.76.76', telecomDns: 'Telecom 114.114.114.114', mobileDns: 'Mobile 223.112.112.112', upstreamHint: 'Upstreams are tried in order; a timeout or failure automatically moves to the next server.', upstreamTimeout: 'Upstream Request Timeout', seconds: 'seconds', saveDnsSettings: 'Save DNS Settings', runtimeStatus: 'Runtime Status', zoneRecords: 'Zone / Records', cacheRefresh: 'Cache Refresh', capabilityHint: 'On Linux, configure CAP_NET_BIND_SERVICE on the platform binary to listen on port 53. The entire process does not need to run as root.',
  publicDomainsTitle: 'Public Domains', publicDomainsDesc: 'Domains are synchronized only from official cloud provider APIs; local manual creation is not available.', syncedDomains: 'Synced Domains', enabledAccounts: 'Enabled Accounts', supportedProviders: 'Supported Providers', dataSource: 'Data Source', officialApi: 'Official API', searchDomain: 'Search domains', cloudAccount: 'Cloud Account', provider: 'Provider', refreshFromCloud: 'Refresh from Cloud Provider', syncedCount: 'Synchronized {count} domain(s).', manageDnsAccounts: 'Manage DNS Accounts', account: 'Account', recordCount: 'Record Count', status: 'Status', healthy: 'Healthy', lastSync: 'Last Sync', actions: 'Actions', dnsRecords: 'DNS Records', noSyncedDomains: 'No synchronized domains', noSyncedDomainsDesc: 'Configure a DNS account first, then refresh the domain list from the cloud provider.', configureDnsAccount: 'Configure DNS Account', aliyunDns: 'Aliyun DNS', tencentDnspod: 'Tencent Cloud DNSPod',
  zoneManagement: 'Zone Management', zoneManagementDesc: 'Centrally manage internal authoritative zones and DNS records. Names not found inside a zone return NXDOMAIN and are not leaked to public DNS.', dnsSettings: 'DNS Settings', createZone: 'Create Zone', dnsStatus: 'DNS Status', checking: 'Checking', zoneCount: 'Zone Count', enabledRecords: 'Enabled Records', dnsNotRunning: 'The Internal DNS service is not running.', enableDnsFirst: 'Enable the Internal DNS service first.', dnsNotRunningDesc: 'Check the listen port and runtime configuration, then restart the service.', enableDnsFirstDesc: 'Configure the listen address and upstream DNS, then enable the service before serving internal domain resolution.', goToDnsSettings: 'Go to DNS Settings', searchZone: 'Search zones', resolutionTest: 'Resolution Test', zoneName: 'Zone Name', description: 'Description', updatedAt: 'Updated At', edit: 'Edit', delete: 'Delete', noZones: 'No internal zones have been created.', noZonesEnabledDesc: 'Create the first zone, for example ops.internal.', noZonesDisabledDesc: 'Zones can be created in advance. Records become active immediately after the DNS service is enabled.', editZone: 'Edit Zone', saveZone: 'Save Zone', zoneNameRequired: 'Enter a zone name.', zoneSaved: 'Zone saved and the resolution cache refreshed immediately.', deleteZoneTitle: 'Delete Zone', deleteZoneConfirm: 'Deleting zone “{name}” also deletes all of its DNS records. Continue?', zoneDeleted: 'Zone deleted and resolution invalidated immediately.', normalizeZoneHint: 'The name is normalized to lowercase and any trailing dot is removed on save.', cancel: 'Cancel',
  search: 'Search', save: 'Save', test: 'Test', enabled: 'Enabled', disabled: 'Disabled'
}

export function dt(key, params = {}) {
  const dict = currentLocale.value === 'en-US' ? en : ko
  let text = dict[key] || en[key] || key
  Object.entries(params).forEach(([name, value]) => { text = text.replaceAll(`{${name}}`, String(value)) })
  return text
}
