import { currentLocale } from './i18n-runtime'

const ko = {
  selectAccountRange: 'Cloud Account와 시작/종료 날짜를 먼저 선택하십시오.', resourceBreakdown: 'Resource 비용 분석', resourceBreakdownDesc: 'Cloud Account와 날짜 범위를 선택하면 Resource별 Billing 비용을 집계합니다.', selectCloudAccount: 'Cloud Account 선택', startDate: '시작 날짜', endDate: '종료 날짜', startBreakdown: '분석 시작', filterHint: 'Cloud Account와 날짜 범위를 선택하면 자동으로 조회합니다.', resourceCostDetail: 'Resource 비용 상세', resourceCount: '총 {count}개 Resource', allRegions: '전체 Region', allResourceTypes: '전체 Resource Type', resourceName: 'Resource 이름', unlinkedResource: '연결되지 않은 Resource', resourceType: 'Resource Type', uncategorized: '미분류', resourceConfig: 'Resource 구성', cloudProvider: 'Cloud Provider', region: 'Region', unavailable: '미제공', originalPrice: '원가', discount: '할인', actualPayment: '실제 결제', billingEntries: 'Billing 항목', noResourceCost: '현재 필터 조건에 Resource 비용이 없습니다.',
  costBreakdownTitle: '비용 분석 — {year}년 {month}월', costBreakdownDesc: '모든 통계는 선택한 자연월 범위에서 집계 결과를 표시합니다.', allAccounts: '전체 Account', query: '조회', monthlyTotal: '월 비용 합계', groupedByProductRegion: 'Product 및 Region 기준 집계', byCloudProduct: 'Cloud Product별 분석', topProducts: '이번 달 주요 Product 비용', noMonthlyCost: '해당 월의 비용 데이터가 없습니다.', byRegion: 'Region별 분석', regionalCost: '이번 달 Region 비용 분포', noRegionalCost: '해당 월의 Region Billing 데이터가 없습니다.', advancedBreakdown: '고급 차원 분석', advancedBreakdownDesc: 'Account, Resource 또는 Tag 기준으로 이번 달 비용을 분석합니다.', byCloudAccount: 'Cloud Account 기준', byResource: 'Resource 기준', byTag: 'Tag 기준', noDimensionCost: '선택한 차원에서 집계 가능한 데이터가 없습니다.',
  billingSync: 'Billing 동기화', billingSyncDesc: '월별로 순차 동기화하며 한 달이 실패해도 다른 월의 동기화는 계속됩니다. 기본 범위는 현재 월을 포함한 최근 6개월입니다.', selectCloudAccountShort: 'Cloud Account 선택', startBillingMonth: '시작 Billing Month', endBillingMonth: '종료 Billing Month', to: '부터', syncNow: '지금 동기화', quickRange: '빠른 범위', recentMonths: '최근 {count}개월', aliyunEstimateHint: 'Aliyun은 현재 월 단위 Instance Billing을 사용하고 일평균 통계를 생성합니다. 비용 분석에서는 해당 값이 Estimate임을 명확히 표시합니다.', syncResult: '이번 동기화 결과', finalSnapshot: '최종 저장 Snapshot', billingMonth: 'Billing Month', status: '상태', success: '성공', failure: '실패', running: '실행 중', sourceRecords: 'Source Records', storedRecords: 'Stored Records', storedAmount: 'Stored Amount', dedupOverwrite: 'Dedup / Overwrite', errorInfo: 'Error', recordsUnit: '{count}건', manualImport: 'Billing 수동 Import', manualImportDesc: 'billingDate, service, resourceId, resourceName, resourceType, region, amount, currency, tags 필드를 지원합니다.', importBilling: 'Billing Import', syncHistory: '동기화 History', syncHistoryDesc: '최근 200개의 월별 Billing 동기화 기록입니다. Stored Records와 Stored Amount는 비용 Dashboard와 동일한 최종 Snapshot을 사용합니다.', refreshRecords: '기록 새로고침', oldSyncHint: '기존 동기화 기록은 Source 기준만 저장했습니다. 해당 Billing Month를 다시 동기화하면 최종 Snapshot과 Dedup 수를 표시합니다.', cloudAccount: 'Cloud Account', triggerType: 'Trigger Type', sourceAmount: 'Source Amount', pendingResync: '재동기화 필요', oldRecordPending: '기존 기록 검증 필요', deduplicated: 'Dedup', executionDuration: 'Execution Duration', executionInfo: 'Execution Info / Error', startedAt: 'Started At', finishedAt: 'Finished At', noSyncHistory: 'Billing 동기화 기록이 없습니다.', selectAccountFirst: '먼저 Cloud Account를 선택하십시오.', selectSyncRange: '동기화 Billing Month 범위를 선택하십시오.', syncCompleted: '동기화를 완료했습니다.', syncCompletedWithFailures: '동기화를 완료했으며 {count}개월이 실패했습니다.', invalidBillingJson: 'Billing JSON 형식이 올바르지 않습니다.', billingMustArray: 'Billing 내용은 JSON 배열이어야 합니다.', importedRecords: 'Billing {count}건을 Import했습니다.', seconds: '{count}초', minutesSeconds: '{minutes}분 {seconds}초',
  dashboardTitle: '비용 Dashboard', dashboardDesc: '{range} Multi-Cloud 비용 개요입니다. 현재 월 비용은 오늘까지의 값입니다.', timeRange: '기간', last3Months: '최근 3개월', last6Months: '최근 6개월', last12Months: '최근 12개월', refresh: '새로고침', cumulativeCost: '{range} 누적 비용', includedBills: '{account} · Billing {count}건 포함', currentMonthCost: '이번 달 비용', throughToday: '오늘까지', previousMonthCost: '지난달 비용', monthOverMonth: '전월 대비', latestSyncTime: '최근 동기화', cloudAccountsCount: 'Cloud Account {count}개', costTrend: '{range} 비용 추이', cnyNoBillMonthsZero: '단위: CNY · Billing이 없는 월은 0으로 표시', monthly: '월별', actualCost: '실제 비용', monthsWithBills: '· {count}개월 Billing 존재', monthlyCostTrend: '월별 비용 추이', costComposition: '비용 구성', cloudProvidersCount: 'Cloud Provider {count}개', totalCost: '총 비용', noCostData: '현재 기간에는 비용 데이터가 없습니다.', allCloudAccounts: '전체 Cloud Account', recentMonthsIncludingCurrent: '최근 {count}개월(현재 월 포함)', monthLabel: '{month}월'
}

const en = {
  selectAccountRange: 'Select a cloud account, start date, and end date first.', resourceBreakdown: 'Resource Cost Breakdown', resourceBreakdownDesc: 'Select a cloud account and date range to aggregate billing costs by resource.', selectCloudAccount: 'Select Cloud Account', startDate: 'Start Date', endDate: 'End Date', startBreakdown: 'Start Breakdown', filterHint: 'The query runs automatically after a cloud account and date range are selected.', resourceCostDetail: 'Resource Cost Details', resourceCount: '{count} resources', allRegions: 'All Regions', allResourceTypes: 'All Resource Types', resourceName: 'Resource Name', unlinkedResource: 'Unlinked Resource', resourceType: 'Resource Type', uncategorized: 'Uncategorized', resourceConfig: 'Resource Configuration', cloudProvider: 'Cloud Provider', region: 'Region', unavailable: 'Unavailable', originalPrice: 'Original Price', discount: 'Discount', actualPayment: 'Actual Payment', billingEntries: 'Billing Entries', noResourceCost: 'No resource cost data matches the current filters.',
  costBreakdownTitle: 'Cost Breakdown — {year}-{month}', costBreakdownDesc: 'All statistics are constrained to the selected calendar month and show aggregated breakdown results.', allAccounts: 'All Accounts', query: 'Query', monthlyTotal: 'Monthly Cost Total', groupedByProductRegion: 'Grouped by product and region', byCloudProduct: 'By Cloud Product', topProducts: 'Primary product costs for the month', noMonthlyCost: 'No cost data is available for this month.', byRegion: 'By Region', regionalCost: 'Regional cost distribution for the month', noRegionalCost: 'No regional billing data is available for this month.', advancedBreakdown: 'Advanced Dimension Breakdown', advancedBreakdownDesc: 'View this month by account, resource, or tag.', byCloudAccount: 'By Cloud Account', byResource: 'By Resource', byTag: 'By Tag', noDimensionCost: 'No aggregatable data is available for this dimension.',
  billingSync: 'Billing Sync', billingSyncDesc: 'Synchronizes month by month; a failure in one month does not block the others. The default range is the latest six calendar months including the current month.', selectCloudAccountShort: 'Select Cloud Account', startBillingMonth: 'Start Billing Month', endBillingMonth: 'End Billing Month', to: 'to', syncNow: 'Sync Now', quickRange: 'Quick Range', recentMonths: 'Latest {count} Months', aliyunEstimateHint: 'Aliyun currently uses monthly instance billing and derives daily averages. Cost breakdowns clearly mark these values as estimates.', syncResult: 'Current Sync Result', finalSnapshot: 'Final Stored Snapshot', billingMonth: 'Billing Month', status: 'Status', success: 'Success', failure: 'Failure', running: 'Running', sourceRecords: 'Source Records', storedRecords: 'Stored Records', storedAmount: 'Stored Amount', dedupOverwrite: 'Dedup / Overwrite', errorInfo: 'Error', recordsUnit: '{count} records', manualImport: 'Manual Billing Import', manualImportDesc: 'Supports billingDate, service, resourceId, resourceName, resourceType, region, amount, currency, and tags fields.', importBilling: 'Import Billing', syncHistory: 'Sync History', syncHistoryDesc: 'The latest 200 monthly billing synchronization records. Stored records and amounts use the same final snapshot as the cost dashboard.', refreshRecords: 'Refresh Records', oldSyncHint: 'Legacy synchronization records stored only source-side values. Re-sync the billing month to show the final stored snapshot and deduplication count.', cloudAccount: 'Cloud Account', triggerType: 'Trigger Type', sourceAmount: 'Source Amount', pendingResync: 'Pending Re-sync', oldRecordPending: 'Legacy Record Pending Verification', deduplicated: 'Deduplicated', executionDuration: 'Execution Duration', executionInfo: 'Execution Info / Error', startedAt: 'Started At', finishedAt: 'Finished At', noSyncHistory: 'No billing synchronization records.', selectAccountFirst: 'Select a cloud account first.', selectSyncRange: 'Select a billing month range.', syncCompleted: 'Synchronization completed.', syncCompletedWithFailures: 'Synchronization completed with {count} failed month(s).', invalidBillingJson: 'The billing JSON is invalid.', billingMustArray: 'Billing content must be a JSON array.', importedRecords: 'Imported {count} billing records.', seconds: '{count}s', minutesSeconds: '{minutes}m {seconds}s',
  dashboardTitle: 'Cost Dashboard', dashboardDesc: '{range} multi-cloud cost overview. Current-month cost is partial through today.', timeRange: 'Time Range', last3Months: 'Last 3 Months', last6Months: 'Last 6 Months', last12Months: 'Last 12 Months', refresh: 'Refresh', cumulativeCost: '{range} Cumulative Cost', includedBills: '{account} · {count} billing records included', currentMonthCost: 'Current Month Cost', throughToday: 'Through Today', previousMonthCost: 'Previous Month Cost', monthOverMonth: 'Month over Month', latestSyncTime: 'Latest Sync Time', cloudAccountsCount: '{count} Cloud Accounts', costTrend: '{range} Cost Trend', cnyNoBillMonthsZero: 'Unit: CNY · Months without billing are shown as zero', monthly: 'Monthly', actualCost: 'Actual Cost', monthsWithBills: '· {count} months with billing', monthlyCostTrend: 'Monthly Cost Trend', costComposition: 'Cost Composition', cloudProvidersCount: '{count} Cloud Providers', totalCost: 'Total Cost', noCostData: 'No cost data is available for the current range.', allCloudAccounts: 'All Cloud Accounts', recentMonthsIncludingCurrent: 'Last {count} Months (including current)', monthLabel: '{month}'
}

export function ft(key, params = {}) {
  const dict = currentLocale.value === 'en-US' ? en : ko
  let text = dict[key] || en[key] || key
  Object.entries(params).forEach(([name, value]) => { text = text.replaceAll(`{${name}}`, String(value)) })
  return text
}
