import { currentLocale } from './i18n-runtime'

const ko = {
  toolRegistry: 'Tool Registry', toolRegistryDesc: 'AI가 호출할 수 있는 플랫폼 기능을 관리합니다. Read Tool은 자동 실행할 수 있고 모든 Kubernetes Write 작업은 반드시 수동 승인을 거칩니다.', enabledCount: '활성 / {total}', capabilityCount: '{count}개 기능', write: '변경', readOnly: '읽기 전용', debug: '디버그', cancel: '취소', executeReadOnly: 'Read Tool 실행', toolUpdated: 'Tool 설정을 업데이트했습니다.', toolResult: 'Tool 실행 결과', debugTool: 'Tool 디버그 · {name}', cloudCost: '클라우드 비용', assets: '자산', monitoring: '모니터링', grafana: 'Grafana', kubernetes: 'Kubernetes', conversations: 'AI 대화', publicNavigation: 'Public Navigation',
  conversationManagement: '대화 관리', conversationManagementDesc: 'Multi-turn 대화, Model Source와 최근 활동을 한곳에서 확인하고 기존 Context로 다시 전환할 수 있습니다.', newConversation: '새 대화 시작', searchConversationTitle: '대화 제목 검색', search: '검색', conversation: '대화', createdBy: '생성: {name}', currentUser: '현재 사용자', model: 'Model', messageCount: '메시지 수', recentActivity: '최근 활동', status: '상태', resumable: '이어하기 가능', actions: '작업', continueConversation: '대화 이어하기', unpin: '고정 해제', pin: '고정', delete: '삭제', conversationUnpinned: '고정을 해제했습니다.', conversationPinned: '고정했습니다.', deleteConversation: '대화 삭제', deleteConversationConfirm: '대화 “{title}”을(를) 삭제하시겠습니까?', conversationDeleted: '대화를 삭제했습니다.',
  publicNavigationSuffix: 'Public Navigation', loadingNavigation: 'Navigation을 불러오는 중...', publicNavigationUnavailable: 'Public Navigation을 사용할 수 없습니다.', publicNavigationUnavailableDesc: '링크가 만료되었거나 해당 Navigation Group의 공개 설정이 중지되었습니다.', integrationPublicNavigation: 'Integration Center Public Navigation', commonSystems: '자주 사용하는 시스템 및 Tool 바로가기', searchSystemToolAddress: '시스템, Tool 또는 주소 검색', entryCount: '{count}개 Entry', allNavigation: '전체 Navigation', openConfiguredWindow: 'Entry를 선택하면 설정된 Window에서 엽니다.', noEntryDescription: 'Entry 설명이 없습니다.', noMatchingNavigation: '일치하는 Navigation이 없습니다.', providedByIntegrationCenter: 'Ops Admin Integration Center 제공',
  knowledgeManagement: 'Knowledge Base 관리', knowledgeManagementDesc: '로컬 Markdown 문서를 Upload하거나 온라인에서 관리합니다. 활성화된 문서는 Knowledge Search Tool을 통해 AI Assistant가 사용할 수 있습니다.', uploadMarkdown: '.md Upload', newMarkdown: '새 .md', localKnowledgeDocuments: '로컬 Knowledge 문서', activeDocuments: '활성 {active} / 전체 {total}개 · 활성 문서만 AI Search 대상입니다.', searchDocumentName: '문서 이름 검색', document: '문서', contentSummary: '내용 요약', source: 'Source', upload: 'Upload', create: '생성', updatedAt: 'Updated At', edit: '수정', noMarkdownDocuments: 'Markdown 문서가 없습니다.', documentRequired: '문서 이름과 Markdown 내용을 입력하십시오.', documentSaved: 'Knowledge 문서를 저장했습니다.', deleteDocument: '문서 삭제', deleteDocumentConfirm: 'Knowledge 문서 “{name}”을(를) 삭제하시겠습니까?', documentDeleted: '문서를 삭제했습니다.', markdownOnly: '.md 파일만 Upload할 수 있습니다.', markdownMax2mb: 'Markdown 파일은 2MB를 초과할 수 없습니다.', markdownImported: 'Markdown 문서를 Import했습니다.', noContent: '내용이 없습니다.', editKnowledgeDocument: 'Knowledge 문서 수정', newKnowledgeDocument: 'Knowledge 문서 생성', knowledgeEditorDesc: '팀이 검색할 Markdown 내용을 관리합니다. 저장된 내용은 AI Assistant가 필요할 때 참조할 수 있습니다.', uploadedDocument: 'Upload 문서', onlineEdit: '온라인 편집', documentInfo: '문서 정보', documentName: '문서 이름', documentNameExample: '예: Production Release Standard', fileName: '파일 이름', defaultFileName: '기본값: 문서이름.md', markdownContent: 'Markdown 내용', characters: '{count}자', preview: '미리보기', markdownPlaceholder: '# Title\n\nKnowledge Base 내용을 작성하십시오...', aiRetrieval: 'AI Search', aiRetrievalDesc: '활성화하면 Knowledge Search Tool이 관련 문서 조각을 AI Conversation에 제공합니다.', enabled: '활성화', disabled: '비활성화', localDatabaseOnly: '플랫폼 Local Database에만 저장', saveDocument: '문서 저장',
  assistantChat: 'AI Operations Assistant', assistantChatDesc: '로컬 Monitoring, Kubernetes, 동기화된 Cloud Billing 데이터를 조회합니다. 모든 변경 작업은 수동 확인이 필요합니다.', selectModel: 'Model 선택', newChat: '새 대화', recentConversations: '최근 대화', modelNotConfigured: 'Model 미설정', modelManagement: 'Model 관리', newConversationShort: '새 대화', toolsEnabled: 'Tool 호출 활성화', pinConversation: '대화 고정', deleteConversationTitle: '대화 삭제', deleteConversationAllConfirm: '삭제하면 해당 대화의 Message와 대기 중인 작업도 함께 제거됩니다. 계속하시겠습니까?', configureModelFirst: '먼저 Model 관리에서 사용할 Model을 구성하고 활성화하십시오.', changeK8sResourceConfirm: '이 작업은 Kubernetes Resource를 변경합니다. Target Cluster와 Parameter를 확인하십시오.', confirmChangeExecution: '변경 실행 확인', confirmExecution: '실행 확인', actionCompleted: '작업을 실행했습니다.', actionRejected: '실행을 거부했습니다.', whatToInvestigate: '무엇을 점검할까요?', assistantCapabilities: 'Monitoring, Grafana, Kubernetes 및 로컬에 동기화된 Cloud Billing 데이터를 조회할 수 있습니다.', me: '나', you: '사용자', operationsAssistant: 'Operations Assistant', pendingChange: '확인이 필요한 변경 작업', reject: '거부', analyzingPlatformData: '플랫폼 데이터를 분석하고 있습니다.', composerPlaceholder: '현상, Resource 범위 또는 원하는 작업을 입력하십시오. Enter로 전송하고 Shift + Enter로 줄바꿈합니다.', localBillingOnly: '비용 분석은 로컬에 동기화된 Billing만 조회하며 Cloud Provider API를 직접 호출하지 않습니다.', send: '전송', suggestionCostTrend: '최근 6개월 Cloud 비용 추세 조회', suggestionCostDistribution: '이번 달 Cloud 비용의 Product 및 Region 분포 분석', suggestionK8sHealth: '현재 Kubernetes Cluster 상태 점검', suggestionPodRestart: 'Pod 반복 Restart 원인 분석'
}

const en = {
  toolRegistry: 'Tool Registry', toolRegistryDesc: 'Manage platform capabilities callable by AI. Read tools may run automatically; every Kubernetes write operation requires explicit human confirmation.', enabledCount: 'Enabled / {total}', capabilityCount: '{count} capabilities', write: 'Write', readOnly: 'Read Only', debug: 'Debug', cancel: 'Cancel', executeReadOnly: 'Execute Read Tool', toolUpdated: 'Tool configuration updated.', toolResult: 'Tool Result', debugTool: 'Debug Tool · {name}', cloudCost: 'Cloud Cost', assets: 'Assets', monitoring: 'Monitoring', grafana: 'Grafana', kubernetes: 'Kubernetes', conversations: 'AI Conversations', publicNavigation: 'Public Navigation',
  conversationManagement: 'Conversation Management', conversationManagementDesc: 'Review multi-turn conversations, model sources, and recent activity in one place, then return to historical context at any time.', newConversation: 'Start New Conversation', searchConversationTitle: 'Search conversation titles', search: 'Search', conversation: 'Conversation', createdBy: 'Created by {name}', currentUser: 'Current User', model: 'Model', messageCount: 'Messages', recentActivity: 'Recent Activity', status: 'Status', resumable: 'Resumable', actions: 'Actions', continueConversation: 'Continue', unpin: 'Unpin', pin: 'Pin', delete: 'Delete', conversationUnpinned: 'Conversation unpinned.', conversationPinned: 'Conversation pinned.', deleteConversation: 'Delete Conversation', deleteConversationConfirm: 'Delete conversation “{title}”?', conversationDeleted: 'Conversation deleted.',
  publicNavigationSuffix: 'Public Navigation', loadingNavigation: 'Loading navigation...', publicNavigationUnavailable: 'Public Navigation Unavailable', publicNavigationUnavailableDesc: 'The link may have expired or the navigation group is no longer public.', integrationPublicNavigation: 'Integration Center Public Navigation', commonSystems: 'Quick access to commonly used systems and tools', searchSystemToolAddress: 'Search systems, tools, or addresses', entryCount: '{count} entries', allNavigation: 'All Navigation', openConfiguredWindow: 'Selecting an entry opens it using its configured window mode.', noEntryDescription: 'No entry description.', noMatchingNavigation: 'No matching navigation entries.', providedByIntegrationCenter: 'Provided by Ops Admin Integration Center',
  knowledgeManagement: 'Knowledge Base Management', knowledgeManagementDesc: 'Upload or maintain local Markdown documents online. Enabled documents can be supplied to the AI Assistant through the Knowledge Search tool.', uploadMarkdown: 'Upload .md', newMarkdown: 'New .md', localKnowledgeDocuments: 'Local Knowledge Documents', activeDocuments: '{active} active / {total} total · Only enabled content is searched by AI.', searchDocumentName: 'Search document names', document: 'Document', contentSummary: 'Content Summary', source: 'Source', upload: 'Upload', create: 'Create', updatedAt: 'Updated At', edit: 'Edit', noMarkdownDocuments: 'No Markdown documents have been added.', documentRequired: 'Enter a document name and Markdown content.', documentSaved: 'Knowledge document saved.', deleteDocument: 'Delete Document', deleteDocumentConfirm: 'Delete knowledge document “{name}”?', documentDeleted: 'Document deleted.', markdownOnly: 'Only .md files are supported.', markdownMax2mb: 'Markdown files must not exceed 2MB.', markdownImported: 'Markdown document imported.', noContent: 'No content.', editKnowledgeDocument: 'Edit Knowledge Document', newKnowledgeDocument: 'New Knowledge Document', knowledgeEditorDesc: 'Maintain searchable Markdown content for the team. Saved content can be referenced by the AI Assistant when needed.', uploadedDocument: 'Uploaded Document', onlineEdit: 'Online Edit', documentInfo: 'Document Information', documentName: 'Document Name', documentNameExample: 'e.g. Production Release Standard', fileName: 'File Name', defaultFileName: 'Default: document-name.md', markdownContent: 'Markdown Content', characters: '{count} characters', preview: 'Preview', markdownPlaceholder: '# Title\n\nWrite knowledge base content here...', aiRetrieval: 'AI Search', aiRetrievalDesc: 'When enabled, the Knowledge Search tool can provide relevant document fragments to AI conversations.', enabled: 'Enabled', disabled: 'Disabled', localDatabaseOnly: 'Stored only in the platform local database', saveDocument: 'Save Document',
  assistantChat: 'AI Operations Assistant', assistantChatDesc: 'Query local monitoring, Kubernetes, and synchronized cloud billing data. Every change operation requires explicit human confirmation.', selectModel: 'Select Model', newChat: 'New Conversation', recentConversations: 'Recent Conversations', modelNotConfigured: 'Model Not Configured', modelManagement: 'Model Management', newConversationShort: 'New Conversation', toolsEnabled: 'Tool Calls Enabled', pinConversation: 'Pin Conversation', deleteConversationTitle: 'Delete Conversation', deleteConversationAllConfirm: 'Deleting this conversation also removes its messages and pending actions. Continue?', configureModelFirst: 'Configure and enable a model in Model Management first.', changeK8sResourceConfirm: 'This action changes Kubernetes resources. Confirm the target cluster and parameters.', confirmChangeExecution: 'Confirm Change Execution', confirmExecution: 'Confirm Execution', actionCompleted: 'Action completed.', actionRejected: 'Action rejected.', whatToInvestigate: 'What would you like to investigate?', assistantCapabilities: 'I can query monitoring, Grafana, Kubernetes, and locally synchronized cloud billing data.', me: 'Me', you: 'You', operationsAssistant: 'Operations Assistant', pendingChange: 'Pending Change Action', reject: 'Reject', analyzingPlatformData: 'Analyzing platform data', composerPlaceholder: 'Describe the symptom, resource scope, or desired operation. Press Enter to send and Shift + Enter for a newline.', localBillingOnly: 'Cost analysis queries only locally synchronized billing data and does not call cloud provider APIs directly.', send: 'Send', suggestionCostTrend: 'Query the cloud cost trend for the last six months', suggestionCostDistribution: 'Analyze this month’s cloud cost distribution by product and region', suggestionK8sHealth: 'Check the current Kubernetes cluster health', suggestionPodRestart: 'Analyze troubleshooting steps for repeatedly restarting Pods'
}

export function it(key, params = {}) {
  const dict = currentLocale.value === 'en-US' ? en : ko
  let text = dict[key] || en[key] || key
  Object.entries(params).forEach(([name, value]) => { text = text.replaceAll(`{${name}}`, String(value)) })
  return text
}

const legacyCategoryFragments = [['\u4e91\u8d39\u7528', 'cloudCost'], ['\u8d44\u4ea7', 'assets'], ['\u76d1\u63a7', 'monitoring']]
export function integrationCategoryLabel(value = '') { let result = String(value); for (const [legacy, key] of legacyCategoryFragments) result = result.replaceAll(legacy, it(key)); return result }
export function integrationCategoryKind(value = '') { const name = String(value); if (name.includes('\u4e91\u8d39\u7528') || name.includes('\u8d44\u4ea7') || /cloud|cost|asset/i.test(name)) return 'cost'; if (name.includes('\u76d1\u63a7') || /monitor|metric|alert/i.test(name)) return 'monitor'; if (/grafana/i.test(name)) return 'grafana'; if (/kubernetes|k8s/i.test(name)) return 'kubernetes'; return 'integration' }
