import { currentLocale } from './i18n-runtime'

const ko = {
  traceSearch: 'Trace 조회', traceSearchDesc: 'Jaeger에서 Distributed Trace를 조회해 Service 호출 지연과 오류 Span을 분석합니다.', noJaegerDatasource: 'Jaeger Datasource가 구성되지 않았습니다.', noJaegerDatasourceDesc: 'Datasource 관리에서 Jaeger Query Service 주소를 추가하고 연결을 확인하십시오.', selectJaegerDatasource: 'Jaeger Datasource 선택', selectService: 'Service 선택', selectOperationOptional: 'Operation 선택 (선택 사항)', last15Minutes: '최근 15분', lastHour: '최근 1시간', last6Hours: '최근 6시간', last24Hours: '최근 24시간', last7Days: '최근 7일', customTime: '사용자 지정', startTime: '시작 시간', endTime: '종료 시간', to: '부터', tagJsonExample: 'Tag JSON, 예: {"http.status_code":"500"}', traceIdDirect: 'Trace ID (직접 조회 가능)', query: '조회', currentDatasourceHint: '현재 Datasource: {name}. Tag Filter는 Jaeger 형식의 JSON Object를 사용합니다.', selectServiceOrTrace: 'Service를 선택해 조회하거나 Trace ID를 입력해 호출 흐름을 직접 찾으십시오.', servicePath: 'Service Path', status: '상태', startedAt: 'Started At', totalDuration: 'Total Duration', spanCount: 'Span 수', actions: '작업', detail: '상세', pageSize: '페이지당 {count}건', success: '성공', abnormal: '오류', selectServiceWarning: 'Service를 선택하거나 Trace ID를 직접 입력하십시오.', selectFullTimeRange: '시작 시간과 종료 시간을 모두 선택하십시오.', configureJaegerFirst: '먼저 Datasource 관리에서 Jaeger Datasource를 구성하십시오.',
  unitDay: '일', unitCount: '개', unitHost: '대', unitTimes: '회', off: '꺼짐',
  inspectionPageDesc: 'Inspection Checklist 방식으로 PromQL Panel 상태를 점검하고 Inspection Report PDF Export를 지원합니다.', gridPageDesc: 'Grid Dashboard 방식으로 Metric Card, Trend, Ranking, Gauge를 표시하며 대형 화면 관제에 적합합니다.', inspectionLayoutHint: '현재 Layout: Inspection List. 일상 Troubleshooting과 항목별 점검에 적합합니다.', gridLayoutHint: '현재 Layout: Grid Dashboard. 대형 화면 표시와 전체 관제에 적합합니다.',
  tplBlankName: '빈 Dashboard', tplBlankDesc: '빈 Dashboard를 생성하고 PromQL Panel을 직접 추가합니다.', tplHostDesc: 'Node Exporter Dashboard를 기준으로 Online 상태, CPU, Memory, Disk, Network, System Load를 표시합니다.', tplK8sDesc: 'Kubernetes Dashboard 스타일로 Cluster Resource, Capacity, Workload, Network Metric을 표시합니다.',
  tplAllHosts: '전체 Host', tplAvgCpuUsage: '평균 CPU 사용률', tplAvgMemoryUsage: '평균 Memory 사용률', tplAvgDiskUsage: '평균 Disk 사용률', tplCpuUsageTop: 'CPU 사용률 Top', tplMemoryUsageTop: 'Memory 사용률 Top', tplDiskUsageTop: 'Disk 사용률 Top', tplNetworkReceiveTop: 'Network 수신 Rate Top', tplNetworkTransmitTop: 'Network 송신 Rate Top', tplCpuTrend: 'CPU 사용 Trend', tplMemoryTrend: 'Memory 사용 Trend', tplFileHandleUsage: 'File Handle 사용률', tplRunningProcesses: '실행 Process 수', tplSystemUptimeTop: 'System Uptime Top', tplHostInfo: 'Host 정보',
  tplCpuRequestUsage: 'CPU Request 사용률', tplMemoryRequestUsage: 'Memory Request 사용률',
  tplPodCount: 'Pod 수', tplAbnormalPods: '이상 Pod', tplPodsByNamespace: 'Namespace별 Pod 분포', tplPodsByNode: 'Node별 Pod 분포', tplReplicaAvailability: 'Workload Replica 가용률', tplAbnormalReasonTop: '이상 Reason Top', tplTotalRestartsTop: 'Pod 누적 Restart Top', tplRestartIncreaseTop: '최근 1시간 Pod Restart 증가 Top', tplContainerCpuTrend: 'Container CPU 사용 Trend', tplContainerMemoryTrend: 'Container Memory 사용 Trend', tplPodNetworkReceive: 'Pod Network 수신 Rate', tplPodNetworkTransmit: 'Pod Network 송신 Rate', tplPodDetail: 'Pod 상세',
  healthNotSelected: '미선택', healthErrorsAbove: '{count} 개 이상', healthOk: '정상', datasourceNotSelected: 'Datasource 미선택', stateDisabled: '비활성화됨', stateQueryFailed: 'Query 실패', stateNoData: 'Data 없음', stateLive: '실시간',
  createTitle: '{title} 생성', editTitle: '{title} 수정', deleteTitle: '{title} 삭제', titleEmpty: '{title} 없음',
  panelCountTotal: '{count} 개Panel', activePanelCount: '{count} 개활성 Panel', seriesCount: '{count} 개 Series', filterAllCount: '전체 {count}', filterProblemCount: '이상 {count}', filterReviewCount: '검토 필요 {count}', filterHealthyCount: '정상 {count}', needCheckCount: '확인 필요 {count}', disabledCount: '비활성 {count}', inspectionDisplayHint: '이상 항목 우선 정렬 · 현재 {count}개 표시', lastUpdated: '최근 업데이트 {time}', lastRefresh: '최근 Refresh {time}',
  selectDatasource: 'Datasource 선택', autoRefreshOff: '자동 Refresh 끄기', refresh10s: '10초 Refresh', refresh30s: '30초 Refresh', refresh60s: '60초 Refresh', refreshAll: '전체 Refresh', exitFullscreen: '전체 화면 종료', fullscreenDashboard: 'Dashboard 전체 화면', addPanel: 'Panel 추가', editPanel: 'Panel 수정', panelCount: 'Panel 수', activePanels: '활성 Panel', problemPanels: '이상 Panel', refreshInterval: 'Refresh 주기', dashboardStatus: 'Dashboard 상태', noDashboardsYet: 'Monitoring Dashboard가 없습니다. 먼저 생성하십시오.', noPanelsYet: '현재 Dashboard에 Panel이 없습니다. Panel을 추가하거나 Template으로 생성하십시오.', reinspectProblems: '이상 재검토', runInspection: 'Inspection 실행', inspectionHeadDesc: 'Panel별 Query 상태, 현재 값, 반환 Series, PromQL을 확인하며 일상 Troubleshooting Inspection에 적합합니다.', noFilteredPanels: '현재 Filter 조건에 해당하는 Panel이 없습니다.', noDescription: '설명 없음', returnedSeries: '반환 Series', currentValue: '현재 값', minLabel: '최소', avgLabel: '평균', maxLabel: '최대', startLabel: '시작', nowLabel: '현재', liveSampling: '실시간 Sampling',
  nameLabel: '이름', namePlaceholder: '예: Production {title}', enabledOption: '활성화', disabledOption: '비활성화', descriptionLabel: '설명', titleLabel: '제목', unitPlaceholder: '%, ms, 개', promqlPlaceholder: '예: up 또는 sum(rate(http_requests_total[5m]))', cancel: '취소', save: '저장', create: '생성', edit: '수정', delete: '삭제',
  selectInspectionFirst: 'Inspection Dashboard를 먼저 선택하십시오.', popupBlocked: 'Browser가 Report Window를 차단했습니다. Popup을 허용한 뒤 다시 시도하십시오.', enterTitleName: '{title} 이름을 입력하십시오.', createDatasourceFirst: 'Prometheus Datasource를 먼저 생성한 뒤 Template으로 Dashboard를 생성하십시오.', savedMsg: '저장했습니다.', deletedMsg: '삭제했습니다.', deleteDashboardConfirm: '{title} “{name}”을(를) 삭제하시겠습니까? 연결된 Panel도 함께 삭제됩니다.', confirmTitle: '확인', deletePanelConfirm: 'Panel “{name}”을(를) 삭제하시겠습니까?', selectOrCreateDashboard: 'Monitoring Dashboard를 생성하거나 선택하십시오.', enterPanelRequired: 'Panel 제목, Datasource 및 PromQL을 입력하십시오.', configureDatasourceFirst: 'Datasource 관리에서 Prometheus 또는 VictoriaMetrics Datasource를 먼저 구성하십시오.', noProblemPanels: '현재 재검토할 이상 Panel이 없습니다.', promqlCopied: 'PromQL을 복사했습니다.', promqlCopyFailed: '복사에 실패했습니다. PromQL을 직접 복사하십시오.',
  printPdf: '인쇄 / PDF 저장', pdfCreatedAt: '생성 시각: {time}', pdfDashboardStatus: 'Dashboard 상태: {status}', pdfRefreshInterval: 'Refresh 주기: {interval}', noInspectionPanels: 'Inspection Panel이 없습니다.',
  commandCenterEyebrow: '지능형 운영 관제 센터', resourceSituation: '리소스 현황', physicalHost: '물리 호스트', monitoring: '모니터링', activeAlert: '활성 Alert', authRate: '인증률', topFive: '상위 5개', topCount: '상위 {count}개'
}

const en = {
  traceSearch: 'Trace Search', traceSearchDesc: 'Search distributed traces in Jaeger to analyze service latency and failing spans.', noJaegerDatasource: 'No Jaeger Datasource Configured', noJaegerDatasourceDesc: 'Add and verify a Jaeger Query service endpoint in Datasource Management first.', selectJaegerDatasource: 'Select Jaeger Datasource', selectService: 'Select Service', selectOperationOptional: 'Select Operation (Optional)', last15Minutes: 'Last 15 Minutes', lastHour: 'Last 1 Hour', last6Hours: 'Last 6 Hours', last24Hours: 'Last 24 Hours', last7Days: 'Last 7 Days', customTime: 'Custom Time', startTime: 'Start Time', endTime: 'End Time', to: 'to', tagJsonExample: 'Tag JSON, e.g. {"http.status_code":"500"}', traceIdDirect: 'Trace ID (Direct Lookup)', query: 'Query', currentDatasourceHint: 'Current datasource: {name}. Tag filters must use a Jaeger-format JSON object.', selectServiceOrTrace: 'Select a service and query, or enter a Trace ID to locate a trace directly.', servicePath: 'Service Path', status: 'Status', startedAt: 'Started At', totalDuration: 'Total Duration', spanCount: 'Span Count', actions: 'Actions', detail: 'Detail', pageSize: '{count} per page', success: 'Success', abnormal: 'Error', selectServiceWarning: 'Select a service or enter a Trace ID directly.', selectFullTimeRange: 'Select both start and end time.', configureJaegerFirst: 'Configure a Jaeger datasource in Datasource Management first.',
  unitDay: 'd', unitCount: ' count', unitHost: ' units', unitTimes: ' times', off: 'Off',
  inspectionPageDesc: 'Checks PromQL panel status as an inspection checklist and supports inspection report PDF export.', gridPageDesc: 'Shows metric cards, trends, rankings, and gauges in a grid dashboard suited to large-screen monitoring.', inspectionLayoutHint: 'Current layout: Inspection List. Suited to day-to-day troubleshooting and per-item checks.', gridLayoutHint: 'Current layout: Grid Dashboard. Suited to large-screen display and overall monitoring.',
  tplBlankName: 'Blank Dashboard', tplBlankDesc: 'Create an empty dashboard and add PromQL panels directly.', tplHostDesc: 'Shows online status, CPU, memory, disk, network, and system load based on a Node Exporter dashboard.', tplK8sDesc: 'Shows cluster resources, capacity, workloads, and network metrics in a Kubernetes dashboard style.',
  tplAllHosts: 'All Hosts', tplAvgCpuUsage: 'Avg CPU Usage Rate', tplAvgMemoryUsage: 'Avg Memory Usage Rate', tplAvgDiskUsage: 'Avg Disk Usage Rate', tplCpuUsageTop: 'Top CPU Usage Rate', tplMemoryUsageTop: 'Top Memory Usage Rate', tplDiskUsageTop: 'Top Disk Usage Rate', tplNetworkReceiveTop: 'Top Network Receive Rate', tplNetworkTransmitTop: 'Top Network Transmit Rate', tplCpuTrend: 'CPU Usage Trend', tplMemoryTrend: 'Memory Usage Trend', tplFileHandleUsage: 'File Handle Usage Rate', tplRunningProcesses: 'Running Processes', tplSystemUptimeTop: 'Top System Uptime', tplHostInfo: 'Host Info',
  tplCpuRequestUsage: 'CPU Request Usage Rate', tplMemoryRequestUsage: 'Memory Request Usage Rate',
  tplPodCount: 'Pod Count', tplAbnormalPods: 'Abnormal Pods', tplPodsByNamespace: 'Pods by Namespace', tplPodsByNode: 'Pods by Node', tplReplicaAvailability: 'Workload Replica Availability', tplAbnormalReasonTop: 'Top Waiting Reasons', tplTotalRestartsTop: 'Top Cumulative Pod Restarts', tplRestartIncreaseTop: 'Top Pod Restart Increase (1h)', tplContainerCpuTrend: 'Container CPU Usage Trend', tplContainerMemoryTrend: 'Container Memory Usage Trend', tplPodNetworkReceive: 'Pod Network Receive Rate', tplPodNetworkTransmit: 'Pod Network Transmit Rate', tplPodDetail: 'Pod Details',
  healthNotSelected: 'Not Selected', healthErrorsAbove: '{count}+', healthOk: 'Healthy', datasourceNotSelected: 'No Datasource Selected', stateDisabled: 'Disabled', stateQueryFailed: 'Query Failed', stateNoData: 'No Data', stateLive: 'Live',
  createTitle: 'Create {title}', editTitle: 'Edit {title}', deleteTitle: 'Delete {title}', titleEmpty: 'No {title}',
  panelCountTotal: '{count} panels', activePanelCount: '{count} active panels', seriesCount: '{count} series', filterAllCount: 'All {count}', filterProblemCount: 'Problem {count}', filterReviewCount: 'Review {count}', filterHealthyCount: 'Healthy {count}', needCheckCount: 'Needs Check {count}', disabledCount: 'Disabled {count}', inspectionDisplayHint: 'Problems sorted first · showing {count}', lastUpdated: 'Updated {time}', lastRefresh: 'Last refresh {time}',
  selectDatasource: 'Select Datasource', autoRefreshOff: 'Auto Refresh Off', refresh10s: '10s Refresh', refresh30s: '30s Refresh', refresh60s: '60s Refresh', refreshAll: 'Refresh All', exitFullscreen: 'Exit Fullscreen', fullscreenDashboard: 'Dashboard Fullscreen', addPanel: 'Add Panel', editPanel: 'Edit Panel', panelCount: 'Panel Count', activePanels: 'Active Panels', problemPanels: 'Problem Panels', refreshInterval: 'Refresh Interval', dashboardStatus: 'Dashboard Status', noDashboardsYet: 'No monitoring dashboards yet. Create one first.', noPanelsYet: 'No panels in this dashboard yet. Add panels or create them from a template.', reinspectProblems: 'Re-inspect Problems', runInspection: 'Run Inspection', inspectionHeadDesc: 'Reviews per-panel query status, current value, returned series, and PromQL — suited to routine troubleshooting inspections.', noFilteredPanels: 'No panels match the current filter.', noDescription: 'No description', returnedSeries: 'Returned Series', currentValue: 'Current Value', minLabel: 'Min', avgLabel: 'Avg', maxLabel: 'Max', startLabel: 'Start', nowLabel: 'Now', liveSampling: 'Live Sampling',
  nameLabel: 'Name', namePlaceholder: 'e.g. Production {title}', enabledOption: 'Enabled', disabledOption: 'Disabled', descriptionLabel: 'Description', titleLabel: 'Title', unitPlaceholder: '%, ms, count', promqlPlaceholder: 'e.g. up or sum(rate(http_requests_total[5m]))', cancel: 'Cancel', save: 'Save', create: 'Create', edit: 'Edit', delete: 'Delete',
  selectInspectionFirst: 'Select an Inspection Dashboard first.', popupBlocked: 'The browser blocked the report window. Allow popups and try again.', enterTitleName: 'Enter the {title} name.', createDatasourceFirst: 'Create a Prometheus datasource first, then create the dashboard from a template.', savedMsg: 'Saved successfully.', deletedMsg: 'Deleted successfully.', deleteDashboardConfirm: 'Delete {title} “{name}”? Connected panels will also be deleted.', confirmTitle: 'Confirm', deletePanelConfirm: 'Delete panel “{name}”?', selectOrCreateDashboard: 'Create or select a monitoring dashboard.', enterPanelRequired: 'Enter the panel title, datasource, and PromQL.', configureDatasourceFirst: 'Configure a Prometheus or VictoriaMetrics datasource in Datasource Management first.', noProblemPanels: 'No problem panels to re-inspect.', promqlCopied: 'PromQL copied.', promqlCopyFailed: 'Copy failed. Copy the PromQL manually.',
  printPdf: 'Print / Save PDF', pdfCreatedAt: 'Created at: {time}', pdfDashboardStatus: 'Dashboard status: {status}', pdfRefreshInterval: 'Refresh interval: {interval}', noInspectionPanels: 'No inspection panels.',
  commandCenterEyebrow: 'Ops Admin Intelligent Operations Center', resourceSituation: 'Resource Situation', physicalHost: 'Physical Host', monitoring: 'Monitoring', activeAlert: 'Active Alert', authRate: 'Authentication Rate', topFive: 'Top 5', topCount: 'Top {count}'
}

export function mt(key, params = {}) {
  const dict = currentLocale.value === 'en-US' ? en : ko
  let text = dict[key] || en[key] || key
  Object.entries(params).forEach(([name, value]) => { text = text.replaceAll(`{${name}}`, String(value)) })
  return text
}
