import { currentLocale } from './i18n-runtime'

const ko = {
  targetHosts: 'Target Host', selectHosts: 'Host 선택', clear: '초기화', hostGroup: 'Host Group', selectHostGroup: 'Host Group 선택', targetPreview: 'Target Preview', noTargetHosts: '선택한 Target Host가 없습니다.', selectTargetHosts: 'Target Host 선택', hostName: 'Host 이름', sshUser: 'SSH User', cancel: '취소', confirm: '확인',
  executionResult: '실행 결과', executionStatus: '실행 상태', success: '성공', failure: '실패', pending: '대기', running: '실행 중', host: 'Host', message: 'Message', duration: 'Duration', stdout: 'Standard Output', stderr: 'Standard Error', close: '닫기',
  targetSelection: 'Target 선택', environment: 'Environment', allEnvironments: '전체 Environment', searchHosts: 'Host 검색', selectedCount: '{count}개 선택', noHosts: '사용 가능한 Host가 없습니다.', matchedHosts: '{count}개 Host 일치',
  executeTask: 'Task 실행', taskName: 'Task 이름', taskType: 'Task Type', executionSummary: 'Execution Summary', executionProgress: 'Execution Progress', exitCode: 'Exit Code', durationMs: 'Duration (ms)', errorOutput: 'Error Output', errorInfo: 'Error Information',
  second: '초', minute: '분', hour: '시', day: '일', month: '월', week: '요일', everyMinute: '매 1분', every5Minutes: '매 5분', every10Minutes: '매 10분', hourly: '매시 정각', daily2am: '매일 02:00', weeklyMonday2am: '매주 월요일 02:00', executes: '{label} 실행', everySeconds: '매 {count}초 실행', cronDescription: '현재 6-field Cron Expression에 따라 실행', commonSchedules: '자주 쓰는 Schedule', generatedExpression: '생성된 Expression', cronHelp: '*는 모든 값을 의미하며 */5는 5단위마다 실행합니다. 여러 값은 comma로 구분할 수 있습니다.',
  commandRequired: '실행할 Command를 입력하십시오.', targetRequired: 'Target Host 또는 Host Group을 선택하십시오.', batchCommandExecution: 'Batch Command 실행', selectedHostGroup: '선택한 Host Group', commandTask: 'Command 실행 Task', executingPleaseWait: '실행 중입니다. 잠시 기다려 주십시오.', resultSavedToHistory: '실행 결과를 Quick Execution History에 저장했습니다.', commandExecution: 'Command 실행', commandExecutionDesc: 'Command를 직접 입력해 SSH로 여러 Target Host에 실행합니다. Host와 Host Group은 동시에 선택할 수 없습니다.', optionalAutoGenerated: '선택 사항. 비워두면 자동 생성합니다.', command: '실행 Command', commandExample: '예: systemctl restart nginx', concurrency: 'Concurrency', timeout: 'Timeout', timeoutHint: '초. 초과하면 실행을 자동 종료합니다.', executeNow: '지금 실행'
}

const en = {
  targetHosts: 'Target Hosts', selectHosts: 'Select Hosts', clear: 'Clear', hostGroup: 'Host Group', selectHostGroup: 'Select Host Group', targetPreview: 'Target Preview', noTargetHosts: 'No target hosts selected.', selectTargetHosts: 'Select Target Hosts', hostName: 'Host Name', sshUser: 'SSH User', cancel: 'Cancel', confirm: 'Confirm',
  executionResult: 'Execution Result', executionStatus: 'Execution Status', success: 'Success', failure: 'Failure', pending: 'Pending', running: 'Running', host: 'Host', message: 'Message', duration: 'Duration', stdout: 'Standard Output', stderr: 'Standard Error', close: 'Close',
  targetSelection: 'Target Selection', environment: 'Environment', allEnvironments: 'All Environments', searchHosts: 'Search Hosts', selectedCount: '{count} selected', noHosts: 'No hosts are available.', matchedHosts: '{count} hosts matched',
  executeTask: 'Execute Task', taskName: 'Task Name', taskType: 'Task Type', executionSummary: 'Execution Summary', executionProgress: 'Execution Progress', exitCode: 'Exit Code', durationMs: 'Duration (ms)', errorOutput: 'Error Output', errorInfo: 'Error Information',
  second: 'Second', minute: 'Minute', hour: 'Hour', day: 'Day', month: 'Month', week: 'Weekday', everyMinute: 'Every 1 Minute', every5Minutes: 'Every 5 Minutes', every10Minutes: 'Every 10 Minutes', hourly: 'Hourly', daily2am: 'Daily at 02:00', weeklyMonday2am: 'Monday at 02:00', executes: 'Runs {label}', everySeconds: 'Every {count} Seconds', cronDescription: 'Runs according to the current six-field Cron expression', commonSchedules: 'Common Schedules', generatedExpression: 'Generated Expression', cronHelp: '* means any value; */5 means every five units. Multiple values can be separated by commas.',
  commandRequired: 'Enter a command to execute.', targetRequired: 'Select target hosts or a host group.', batchCommandExecution: 'Batch Command Execution', selectedHostGroup: 'Selected Host Group', commandTask: 'Command Execution Task', executingPleaseWait: 'Execution is in progress. Please wait...', resultSavedToHistory: 'The execution result was saved to Quick Execution History.', commandExecution: 'Command Execution', commandExecutionDesc: 'Enter a command manually and execute it on multiple target hosts over SSH. Hosts and host groups are mutually exclusive.', optionalAutoGenerated: 'Optional. Generated automatically when left blank.', command: 'Command', commandExample: 'e.g. systemctl restart nginx', concurrency: 'Concurrency', timeout: 'Timeout', timeoutHint: 'seconds. Execution is terminated automatically after the limit.', executeNow: 'Execute Now'
}

export function ot(key, params = {}) {
  const dict = currentLocale.value === 'en-US' ? en : ko
  let text = dict[key] || en[key] || key
  Object.entries(params).forEach(([name, value]) => { text = text.replaceAll(`{${name}}`, String(value)) })
  return text
}
