package store

import (
	"ops-admin/backend/model"

	"gorm.io/gorm"
)

func AutoMigrate(db *gorm.DB) error {
	return db.AutoMigrate(
		&model.Dept{},
		&model.Post{},
		&model.Role{},
		&model.Menu{},
		&model.Admin{},
		&model.AdminRole{},
		&model.RoleMenu{},
		&model.LoginLog{},
		&model.OperationLog{},
		&model.SystemConfig{},
		&model.AssetHostGroup{},
		&model.AssetHostGroupRelation{},
		&model.AssetCredential{},
		&model.AssetCloudAccount{},
		&model.AssetGateway{},
		&model.AssetHost{},
		&model.AssetDatabase{},
		&model.AssetChangeLog{},
		&model.DatabaseSQLHistory{},
		&model.DatabaseTransferTask{},
		&model.DatabaseBackupPlan{},
		&model.DatabaseBackupRecord{},
		&model.K8sCluster{},
		&model.OpsScript{},
		&model.OpsScriptVersion{},
		&model.OpsExecTask{},
		&model.OpsExecTargetResult{},
		&model.OpsScheduleTemplate{},
		&model.OpsScheduleTask{},
		&model.OpsScheduleTaskLog{},
		&model.OpsJobTemplate{},
		&model.OpsJob{},
		&model.OpsJobHistory{},
		&model.OpsJobHistoryStep{},
		&model.OpsEnvironment{},
		&model.OpsApplication{},
		&model.OpsApplicationEnvironmentBinding{},
		&model.OpsAppBuildTask{},
		&model.OpsAppRelease{},
		&model.OpsAppArtifact{},
		&model.OpsAppPipeline{},
		&model.OpsAppPipelineRun{},
		&model.OpsAppPipelineRunStage{},
		&model.NotifyTemplate{},
		&model.NotifyChannel{},
		&model.NotifyRule{},
		&model.NotifySendLog{},
		&model.MonitorDatasource{},
		&model.MonitorLogShortcut{},
		&model.MonitorAlertRule{},
		&model.MonitorAlertEvent{},
		&model.MonitorAlertEventTimeline{},
		&model.MonitorAlertAction{},
		&model.MonitorSilenceRule{},
		&model.MonitorAggregationRule{},
		&model.MonitorQueryHistory{},
		&model.MonitorDashboard{},
		&model.MonitorDashboardPanel{},
	)
}
