<script setup>
import { computed, onMounted, ref } from 'vue'
import { ElMessage } from 'element-plus'
import { importFinOpsCosts, queryFinOpsAccounts, queryFinOpsSyncLogs, triggerFinOpsSync } from '../../../api/integration'
import './finops.css'

const accounts = ref([]), logs = ref([]), accountId = ref(''), importing = ref(false), syncing = ref(false), rawRecords = ref('[]'), syncRange = ref([]), syncResult = ref(null)
const money = value => Number(value || 0).toLocaleString('zh-CN', { minimumFractionDigits: 2, maximumFractionDigits: 2 })
const dateTime = value => value ? new Date(value).toLocaleString('zh-CN', { hour12: false }) : '-'
const duration = value => value === null || value === undefined ? '-' : value < 60 ? `${value} 秒` : `${Math.floor(value / 60)} 分 ${value % 60} 秒`
const syncRangeReady = computed(() => syncRange.value?.length === 2)
const monthKey = date => `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}`
function setRecentMonths(size) { const now = new Date(); syncRange.value = [monthKey(new Date(now.getFullYear(), now.getMonth() - size + 1, 1)), monthKey(now)] }
async function loadAccounts() { accounts.value = await queryFinOpsAccounts() || [] }
async function loadLogs() { logs.value = await queryFinOpsSyncLogs(accountId.value ? { accountId: accountId.value } : {}) || [] }
async function trigger() { if (!accountId.value) return ElMessage.warning('请先选择云账号'); if (!syncRangeReady.value) return ElMessage.warning('请选择同步账期范围'); syncing.value = true; syncResult.value = null; try { syncResult.value = await triggerFinOpsSync({ accountId: accountId.value, start_month: syncRange.value[0], end_month: syncRange.value[1] }); const failed = syncResult.value?.months?.filter(item => item.status !== 'success').length || 0; ElMessage[failed ? 'warning' : 'success'](failed ? `同步完成，${failed} 个月失败` : '同步完成'); await loadLogs() } finally { syncing.value = false } }
async function importRecords() { if (!accountId.value) return ElMessage.warning('请先选择云账号'); let records; try { records = JSON.parse(rawRecords.value) } catch (_) { return ElMessage.error('账单 JSON 格式无效') } if (!Array.isArray(records)) return ElMessage.warning('账单内容必须是 JSON 数组'); importing.value = true; try { const result = await importFinOpsCosts({ accountId: accountId.value, records }); ElMessage.success(`已导入 ${result?.recordCount || 0} 条账单`); await loadLogs() } finally { importing.value = false } }
onMounted(async () => { setRecentMonths(6); await loadAccounts(); await loadLogs() })
</script>

<template>
  <div class="finops-page finops-sync-page">
    <section class="finops-panel"><div class="finops-head"><div><h2>账单同步</h2><p>按月逐月同步；单月失败不会阻断其他月份。默认范围为含当前月的最近 6 个自然月。</p></div><div class="finops-actions"><el-select v-model="accountId" clearable placeholder="选择云账号" style="width:200px" @change="loadLogs"><el-option v-for="item in accounts" :key="item.id" :label="`${item.name} · ${item.provider}`" :value="item.id" /></el-select><el-date-picker v-model="syncRange" type="monthrange" value-format="YYYY-MM" format="YYYY-MM" :clearable="false" range-separator="至" start-placeholder="开始账期" end-placeholder="结束账期"/><el-button :loading="syncing" type="primary" @click="trigger">立即同步</el-button></div></div><div class="sync-presets"><span>快捷范围：</span><el-button size="small" @click="setRecentMonths(3)">最近 3 个月</el-button><el-button size="small" @click="setRecentMonths(6)">最近 6 个月</el-button><el-button size="small" @click="setRecentMonths(12)">最近 12 个月</el-button></div><el-alert type="info" :closable="false" show-icon title="阿里云当前使用月度实例账单并生成日均摊统计；费用拆分会清楚标记为“估算”。" /></section>
    <section v-if="syncResult" class="finops-panel finops-sync-result"><div class="finops-card-title"><div><h2>本次同步结果</h2><p>{{ syncResult.startMonth }} 至 {{ syncResult.endMonth }} · {{ syncResult.status }} · 最终入库快照</p></div><b class="finops-money">¥ {{ money(syncResult.totalAmount) }}</b></div><el-table :data="syncResult.months" size="small" stripe><el-table-column prop="month" label="账期" width="110"/><el-table-column label="状态" width="100"><template #default="{row}"><el-tag size="small" :type="row.status === 'success' ? 'success' : 'danger'">{{ row.status === 'success' ? '成功' : '失败' }}</el-tag></template></el-table-column><el-table-column prop="sourceRecordCount" label="来源记录" width="100"/><el-table-column prop="recordCount" label="入库记录" width="100"/><el-table-column label="入库金额" width="160"><template #default="{row}">¥ {{ money(row.totalAmount) }}</template></el-table-column><el-table-column label="去重 / 覆盖" width="110"><template #default="{row}">{{ row.deduplicatedCount || 0 }} 条</template></el-table-column><el-table-column prop="error" label="错误信息" min-width="260"><template #default="{row}">{{ row.error || '-' }}</template></el-table-column></el-table></section>
    <section class="finops-panel"><div class="finops-head"><div><h2>手动导入账单</h2><p>支持 billingDate、service、resourceId、resourceName、resourceType、region、amount、currency、tags 字段。</p></div><el-button :loading="importing" type="primary" @click="importRecords">导入账单</el-button></div><textarea v-model="rawRecords" class="finops-import" spellcheck="false" /></section>
    <section class="finops-panel finops-sync-history"><div class="finops-head"><div><h2>同步历史</h2><p>最近 200 条按月账单同步记录。入库记录和入库金额与费用看板使用同一份最终快照。</p></div><el-button @click="loadLogs">刷新记录</el-button></div><el-alert type="info" :closable="false" show-icon title="旧同步记录仅保存了来源口径；重新同步对应账期后，将显示最终入库快照及去重数量。" /><el-table :data="logs" stripe><el-table-column prop="accountName" label="云账号" min-width="150"><template #default="{row}"><b>{{ row.accountName || `账号 #${row.accountId}` }}</b><small class="subline">{{ row.provider || '-' }}</small></template></el-table-column><el-table-column prop="trigger" label="触发方式" width="100"/><el-table-column prop="billingMonth" label="账期" width="100"><template #default="{row}">{{ row.billingMonth || '-' }}</template></el-table-column><el-table-column label="状态" width="90"><template #default="{row}"><el-tag :type="row.status === 'success' ? 'success' : row.status === 'running' ? 'warning' : 'danger'">{{ row.status === 'success' ? '成功' : row.status === 'running' ? '执行中' : '失败' }}</el-tag></template></el-table-column><el-table-column label="来源记录" width="95" align="right"><template #default="{row}">{{ row.snapshotVerified ? row.sourceRecordCount : row.recordCount }}</template></el-table-column><el-table-column label="来源金额" width="125" align="right"><template #default="{row}">¥ {{ money(row.snapshotVerified ? row.sourceTotalAmount : row.totalAmount) }}</template></el-table-column><el-table-column label="入库记录" width="100" align="right"><template #default="{row}">{{ row.snapshotVerified ? row.recordCount : '待重同步' }}</template></el-table-column><el-table-column label="入库金额" width="145" align="right"><template #default="{row}"><span v-if="row.snapshotVerified">¥ {{ money(row.totalAmount) }}</span><el-tag v-else size="small" type="warning">旧记录待核对</el-tag></template></el-table-column><el-table-column label="去重" width="75" align="right"><template #default="{row}">{{ row.snapshotVerified ? `${row.deduplicatedCount || 0} 条` : '-' }}</template></el-table-column><el-table-column label="执行耗时" width="100"><template #default="{row}">{{ duration(row.durationSeconds) }}</template></el-table-column><el-table-column prop="message" label="执行信息 / 错误原因" min-width="230" show-overflow-tooltip/><el-table-column label="开始时间" width="175"><template #default="{row}">{{ dateTime(row.startedAt) }}</template></el-table-column><el-table-column label="完成时间" width="175"><template #default="{row}">{{ dateTime(row.finishedAt) }}</template></el-table-column></el-table><el-empty v-if="!logs.length" description="暂无账单同步记录" /></section>
  </div>
</template>

<style scoped>
.subline{display:block;margin-top:4px;color:#8291a8;font-weight:400}.finops-sync-history{overflow:hidden}.sync-presets{display:flex;align-items:center;gap:8px;margin:0 0 16px;color:#64748b}.finops-sync-result{border-color:#cde9dc}
</style>
