<script setup>
import { computed, ref, watch } from 'vue'
import { queryK8sPodMetrics } from '../../../api/k8s'
import { at } from '../../../utils/asset-i18n'
import { currentLocale } from '../../../utils/i18n-runtime'

const props = defineProps({ pod: { type: Object, required: true }, clusterId: { type: Number, required: true } })
const range = ref('1h'), loading = ref(false), status = ref('idle'), cpuPoints = ref([]), memoryPoints = ref([]), cpuHover = ref({ visible: false }), memoryHover = ref({ visible: false })
const cpuChart = computed(() => buildChart(cpuPoints.value)), memoryChart = computed(() => buildChart(memoryPoints.value)), latestCPU = computed(() => cpuPoints.value.at(-1)?.[1]), latestMemory = computed(() => memoryPoints.value.at(-1)?.[1]), hasData = computed(() => cpuPoints.value.length || memoryPoints.value.length)

function toPoints(series) { return (series?.points || []).map((point) => [Number(point.timestamp) / 1000, Number(point.value)]).filter(([time, value]) => Number.isFinite(time) && Number.isFinite(value)).sort((left, right) => left[0] - right[0]) }
function buildChart(points) {
  if (!points.length) return { path: '', min: 0, max: 1, start: 0, end: 0 }
  const values = points.map((item) => item[1]), min = Math.min(...values), rawMax = Math.max(...values), max = rawMax === min ? min + Math.max(1, Math.abs(min) * 0.08) : rawMax, start = points[0][0], end = points.at(-1)[0]
  const path = points.map(([time, value], index) => `${index ? 'L' : 'M'}${(10 + (time - start) / (end - start || 1) * 480).toFixed(2)},${(10 + (1 - (value - min) / (max - min || 1)) * 120).toFixed(2)}`).join(' ')
  return { path, min, max, start, end }
}
function formatCPU(value) { const number = Number(value); if (!Number.isFinite(number)) return '--'; return number < 1 ? `${(number * 1000).toFixed(number * 1000 >= 10 ? 0 : 1)} m` : at('coreUnit', { value: number.toFixed(2) }) }
function formatBytes(value) { const number = Number(value); if (!Number.isFinite(number)) return '--'; const units = ['B', 'KiB', 'MiB', 'GiB', 'TiB']; let index = 0, current = number; while (current >= 1024 && index < units.length - 1) { current /= 1024; index += 1 } return `${current.toFixed(current >= 10 || index === 0 ? 0 : 1)} ${units[index]}` }
function timeText(timestamp) { return timestamp ? new Date(timestamp * 1000).toLocaleTimeString(currentLocale.value === 'en-US' ? 'en-US' : 'ko-KR', { hour: '2-digit', minute: '2-digit', hour12: false }) : '--' }
function chartY(chart, value) { return 10 + (1 - (value - chart.min) / (chart.max - chart.min || 1)) * 120 }
function closestPoint(points, timestamp) { return points.reduce((closest, point) => !closest || Math.abs(point[0] - timestamp) < Math.abs(closest[0] - timestamp) ? point : closest, null) }
function updateHover(kind, event, chart, points) { if (!points.length) return; const rect = event.currentTarget.getBoundingClientRect(), ratio = Math.max(0, Math.min(1, (event.clientX - rect.left) / rect.width)), time = chart.start + (chart.end - chart.start) * ratio, point = closestPoint(points, time), target = kind === 'cpu' ? cpuHover : memoryHover; target.value = { visible: true, x: Math.max(12, Math.min(88, ratio * 100)), chartX: 10 + ratio * 480, time: point?.[0] || time, value: point?.[1], y: point ? chartY(chart, point[1]) : 0 } }
function clearHover(kind) { (kind === 'cpu' ? cpuHover : memoryHover).value = { visible: false } }
async function loadMetrics() {
  const namespace = String(props.pod?.namespace || '').trim(), podName = String(props.pod?.name || '').trim(); if (!namespace || !podName) return
  loading.value = true; status.value = 'loading'; cpuPoints.value = []; memoryPoints.value = []
  try { const data = await queryK8sPodMetrics(props.clusterId, namespace, podName, range.value); cpuPoints.value = toPoints(data?.metrics?.cpu); memoryPoints.value = toPoints(data?.metrics?.memory); status.value = data?.status || (hasData.value ? 'available' : 'unavailable') }
  catch (error) { console.warn('Failed to load pod metrics', error); status.value = 'unavailable' }
  finally { loading.value = false }
}
watch(() => [props.clusterId, props.pod?.namespace, props.pod?.name, range.value], loadMetrics, { immediate: true })
</script>

<template>
  <section class="pod-monitor-section" :aria-label="at('podMonitoring')">
    <div class="pod-monitor-head"><div><strong>{{ at('podMonitoring') }}</strong><span>CPU / {{ at('memoryUsage') }}</span></div><div class="pod-monitor-actions"><el-select v-model="range" size="small" :aria-label="at('podMonitoring')"><el-option :label="at('lastHour')" value="1h" /><el-option :label="at('last6Hours')" value="6h" /><el-option :label="at('last24Hours')" value="24h" /></el-select><el-button size="small" :loading="loading" @click="loadMetrics">{{ at('refresh') }}</el-button></div></div>
    <div v-loading="loading" class="pod-monitor-body"><div v-if="hasData" class="pod-monitor-charts">
      <article class="pod-monitor-card cpu"><div class="pod-monitor-card-head"><span>CPU</span><b>{{ formatCPU(latestCPU) }}</b></div><div class="pod-chart-wrap"><svg viewBox="0 0 500 140" preserveAspectRatio="none" role="img" :aria-label="at('trend',{title:'Pod CPU'})" @mousemove="updateHover('cpu',$event,cpuChart,cpuPoints)" @mouseleave="clearHover('cpu')"><line v-for="line in 4" :key="line" x1="10" x2="490" :y1="10 + (line - 1) * 40" :y2="10 + (line - 1) * 40" /><path :d="cpuChart.path" /><template v-if="cpuHover.visible"><line class="hover-line" :x1="cpuHover.chartX" :x2="cpuHover.chartX" y1="10" y2="130" /><circle :cx="cpuHover.chartX" :cy="cpuHover.y" r="3.5" /></template></svg><div v-if="cpuHover.visible" class="pod-chart-tooltip" :style="{left:`${cpuHover.x}%`}"><strong>{{timeText(cpuHover.time)}}</strong><span>CPU</span><b>{{formatCPU(cpuHover.value)}}</b></div></div><div class="pod-monitor-axis"><span>{{timeText(cpuChart.start)}}</span><span>{{timeText(cpuChart.end)}}</span></div></article>
      <article class="pod-monitor-card memory"><div class="pod-monitor-card-head"><span>{{ at('memoryUsage') }}</span><b>{{formatBytes(latestMemory)}}</b></div><div class="pod-chart-wrap"><svg viewBox="0 0 500 140" preserveAspectRatio="none" role="img" :aria-label="at('trend',{title:'Pod Memory'})" @mousemove="updateHover('memory',$event,memoryChart,memoryPoints)" @mouseleave="clearHover('memory')"><line v-for="line in 4" :key="line" x1="10" x2="490" :y1="10 + (line - 1) * 40" :y2="10 + (line - 1) * 40" /><path :d="memoryChart.path" /><template v-if="memoryHover.visible"><line class="hover-line" :x1="memoryHover.chartX" :x2="memoryHover.chartX" y1="10" y2="130" /><circle :cx="memoryHover.chartX" :cy="memoryHover.y" r="3.5" /></template></svg><div v-if="memoryHover.visible" class="pod-chart-tooltip" :style="{left:`${memoryHover.x}%`}"><strong>{{timeText(memoryHover.time)}}</strong><span>{{ at('memoryUsage') }}</span><b>{{formatBytes(memoryHover.value)}}</b></div></div><div class="pod-monitor-axis"><span>{{timeText(memoryChart.start)}}</span><span>{{timeText(memoryChart.end)}}</span></div></article>
    </div><el-empty v-else :image-size="52" :description="status==='not-configured'?at('noMetricsDatasource'):at('noPodMetrics')" /></div>
  </section>
</template>

<style scoped>
.pod-monitor-section{padding:16px;border:1px solid #dfe8f7;border-radius:10px;background:linear-gradient(135deg,#fbfdff,#f5f8ff)}.pod-monitor-head,.pod-monitor-actions,.pod-monitor-card-head,.pod-monitor-axis{display:flex;align-items:center}.pod-monitor-head{justify-content:space-between;gap:16px}.pod-monitor-head>div:first-child{display:flex;align-items:baseline;gap:10px}.pod-monitor-head strong{color:#173d72;font-size:16px}.pod-monitor-head span{color:#7a8aa3;font-size:12px}.pod-monitor-actions{gap:8px}.pod-monitor-actions .el-select{width:118px}.pod-monitor-body{min-height:180px}.pod-monitor-charts{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px;margin-top:14px}.pod-monitor-card{padding:12px;border:1px solid #e4eaf5;border-radius:8px;background:#fff}.pod-monitor-card-head{justify-content:space-between;color:#60728c;font-size:13px}.pod-monitor-card-head b{color:#1e3b67;font-size:16px}.pod-chart-wrap{position:relative}.pod-monitor-card svg{display:block;width:100%;height:132px;margin-top:8px;cursor:crosshair}.pod-monitor-card line{stroke:#e8eef7;stroke-width:1;vector-effect:non-scaling-stroke}.pod-monitor-card .hover-line{stroke:#7d8fa9;stroke-dasharray:3 3}.pod-monitor-card path{fill:none;stroke-width:2.4;vector-effect:non-scaling-stroke}.pod-monitor-card circle{stroke:#fff;stroke-width:1.5}.pod-monitor-card.cpu circle{fill:#3c77e8}.pod-monitor-card.memory circle{fill:#20a581}.pod-monitor-card.cpu path{stroke:#3c77e8}.pod-monitor-card.memory path{stroke:#20a581}.pod-chart-tooltip{position:absolute;z-index:2;top:12px;min-width:112px;padding:8px 9px;border:1px solid #d6e1ef;border-radius:7px;background:rgba(255,255,255,.96);box-shadow:0 7px 18px rgba(42,69,104,.18);color:#63758f;font-size:11px;pointer-events:none;transform:translateX(-50%)}.pod-chart-tooltip strong{display:block;margin-bottom:4px;color:#294b79;font-size:12px}.pod-chart-tooltip span{margin-right:8px}.pod-chart-tooltip b{color:#294b79}.pod-monitor-axis{justify-content:space-between;color:#8b98ac;font-size:11px}@media(max-width:900px){.pod-monitor-charts{grid-template-columns:1fr}.pod-monitor-head{align-items:flex-start;flex-direction:column}}
</style>
