package proxmox

// slice_c_seed_test.go — slice-c E2E 시드 생성기(계획 N9·위험 R10). R10
// ("손작성 JSON 금지")에 따라 infra_resource·resource_observation에 싣는
// kind·subtype·external_urn·normalized·raw는 전부 이 패키지 normalizer의
// 산출물이다: PVE 와이어 픽스처를 normalizeGuest·normalizeHypervisorNode에
// 통과시키고 그 결과를 SQL로 렌더해 SLICEC_SEED_OUT 경로에 기록한다.
//
// 실행 주체는 web/e2e/stack.sh의 serve-c(시드 모드)다 — 평시 go test ./...에서는
// SLICEC_SEED_OUT이 비어 Skip되어 파일 시스템 부작용이 없다.
//
// lifecycle/health·labels·observation_hash 컬럼 규칙은 inventory 패키지의
// resourceStates·adapterLabels·observationHash를 미러링한다(unexported + 패키지
// 방향이 inventory→adapter/proxmox라 직접 참조하면 순환 — 미러 함수에 그 사실을
// 명시했다. 규칙 변경 시 양쪽이 함께 움직인다).

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"ops-admin/backend/internal/infra/contract"
)

// 시드 상수 — stack.sh가 생성된 SQL을 그대로 적용하므로 uid 체계는 고정이다.
const (
	seedConnectionUID = "conn-mock-pve"
	seedContextUID    = "ctx-mock-pve"
	seedGenerationUID = "gen-pve-mock-1"
	// urnFor의 ctxID 자리 — 실 sync라면 provider_context.id가 들어가지만 시드는
	// 표시 전용(이 스택에서 실 sync는 돌지 않는다)이므로 고정값으로 정규화만
	// 통과시킨다. 스펙이 단얫하는 URN도 이 상수에서 나온다.
	seedContextID = 1
	// absenceLabelKey의 inventory 패키지 미러(adapterLabels 규약 — 이 키만
	// labels_json에서 제외한다).
	seedAbsenceLabelKey = "v2.absenceRuns"
)

// TestSliceCSeedWriter writes web/e2e/.stack/data/slice-c/seed.sql through the
// real normalizer. Skipped everywhere except the stack.sh serve-c lane.
func TestSliceCSeedWriter(t *testing.T) {
	out := os.Getenv("SLICEC_SEED_OUT")
	if out == "" {
		t.Skip("SLICEC_SEED_OUT unset — seed generation belongs to the serve-c lane")
	}

	// PVE 와이어 픽스처 — /cluster/status node행 1개 + qemu 게스트 1 + lxc
	// 게스트 1. 디스커버리가 실제로 소비하는 표면과 동일한 필드 집합이다.
	node := clusterStatusEntry{Type: "node", Name: "pve-e2e-1", IP: "10.20.0.11", Online: 1}
	vm := guestItem{
		VMID: 100, Name: "web-e2e-01", Status: "running",
		Template: seedIntPtr(0),
		MaxMem:   seedFloatPtr(2147483648), MaxCPU: seedFloatPtr(2), MaxDisk: seedFloatPtr(34359738368),
		Tags: "e2e,web", Uptime: seedFloatPtr(3600),
	}
	ct := guestItem{
		VMID: 110, Name: "ct-e2e-01", Status: "running",
		MaxMem: seedFloatPtr(536870912), MaxCPU: seedFloatPtr(1), MaxDisk: seedFloatPtr(8589934592),
	}

	resVM, err := normalizeGuest(seedContextID, node.Name, "qemu", vm)
	if err != nil {
		t.Fatalf("normalize qemu guest: %v", err)
	}
	resCT, err := normalizeGuest(seedContextID, node.Name, "lxc", ct)
	if err != nil {
		t.Fatalf("normalize lxc guest: %v", err)
	}
	resNode, err := normalizeHypervisorNode(seedContextID, node)
	if err != nil {
		t.Fatalf("normalize hypervisor node: %v", err)
	}

	seeded := []struct {
		uid string
		res contract.DiscoveredResource
	}{
		{uid: "res-pve-mock-vm-100", res: resVM},
		{uid: "res-pve-mock-ct-110", res: resCT},
		{uid: "res-pve-mock-node-1", res: resNode},
	}

	var b strings.Builder
	b.WriteString("-- Generated by TestSliceCSeedWriter (normalizer-driven — plan N9/R10). Do not edit:\n")
	b.WriteString("-- every kind/URN/JSON literal below is the proxmox normalizer's output.\n")
	writeConnectionAndContext(&b)
	for _, s := range seeded {
		writeResource(&b, s.uid, s.res)
		writeObservation(&b, s.uid, s.res)
	}

	if err := os.MkdirAll(filepath.Dir(out), 0o755); err != nil {
		t.Fatalf("create seed dir: %v", err)
	}
	if err := os.WriteFile(out, []byte(b.String()), 0o644); err != nil {
		t.Fatalf("write seed sql: %v", err)
	}
	t.Logf("slice-c seed written: %s (%d resources)", out, len(seeded))
}

// writeConnectionAndContext emits the provider_connection + provider_context
// shell the resources hang off (same shape the register-pve CLI writes —
// Kind "cluster"; a placeholder endpoint this DB-seeded stack never calls).
func writeConnectionAndContext(b *strings.Builder) {
	b.WriteString("INSERT INTO provider_connection\n" +
		"  (uid, provider_type, name, endpoint, status, stale_source, created_at, updated_at)\n" +
		"VALUES\n" +
		"  ('" + seedConnectionUID + "', '" + ProviderName + "', 'mock-pve-endpoint', " +
		"'http://127.0.0.1:9/mock-pve', 'active', 0, NOW(3), NOW(3));\n")

	b.WriteString("INSERT INTO provider_context (uid, connection_id, kind, external_id, name, status, created_at, updated_at)\n" +
		"SELECT '" + seedContextUID + "', id, 'cluster', 'pve-e2e-1', 'mock-pve-endpoint', 'active', NOW(3), NOW(3)\n" +
		"FROM provider_connection WHERE uid = '" + seedConnectionUID + "';\n")
}

// writeResource mirrors inventory.createResource's column wiring: Name rides
// ExternalID, lifecycle/health come from the normalized state keys (the PVE
// normalizer sets none — the columns stay empty, exactly as a real sync would
// leave them), labels mirror the raw payload minus the absence counter.
func writeResource(b *strings.Builder, uid string, res contract.DiscoveredResource) {
	lifecycle, health := seedStates(res)
	labels, err := json.Marshal(seedLabels(res))
	if err != nil {
		panic("slice-c seed: marshal labels: " + err.Error())
	}
	b.WriteString("INSERT INTO infra_resource\n" +
		"  (uid, context_id, kind, subtype, external_id, external_urn, name, display_name,\n" +
		"   lifecycle_state, health_state, managed_state, labels_json, first_seen_at, last_seen_at)\n" +
		"SELECT '" + uid + "', pc.id, " + seedQuote(res.Kind) + ", " + seedQuote(res.Subtype) + ", " +
		seedQuote(res.ExternalID) + ", " + seedQuote(res.ExternalURN) + ", " +
		seedQuote(res.ExternalID) + ", " + seedQuote(res.DisplayName) + ",\n" +
		"       " + seedQuote(lifecycle) + ", " + seedQuote(health) + ", 'discovered', " +
		seedQuote(string(labels)) + ", NOW(3), NOW(3)\n" +
		"FROM provider_context pc WHERE pc.uid = '" + seedContextUID + "';\n")
}

// writeObservation mirrors inventory.storeObservation: generation-stamped,
// hash of the canonical payload bundle, normalizer_version left empty (the
// sync writer does not set it either).
func writeObservation(b *strings.Builder, uid string, res contract.DiscoveredResource) {
	normalized, err := json.Marshal(res.Normalized)
	if err != nil {
		panic("slice-c seed: marshal normalized: " + err.Error())
	}
	raw, err := json.Marshal(res.Raw)
	if err != nil {
		panic("slice-c seed: marshal raw: " + err.Error())
	}
	b.WriteString("INSERT INTO resource_observation\n" +
		"  (resource_id, generation_uid, observation_hash, normalizer_version, normalized_json, raw_json, observed_at)\n" +
		"SELECT r.id, '" + seedGenerationUID + "', " + seedQuote(seedHash(res)) + ", '', " +
		seedQuote(string(normalized)) + ", " + seedQuote(string(raw)) + ", NOW(3)\n" +
		"FROM infra_resource r WHERE r.uid = '" + uid + "';\n")
}

// seedStates mirrors inventory.resourceStates (unexported — cycle-free mirror;
// keep in step with that function).
func seedStates(res contract.DiscoveredResource) (lifecycle, health string) {
	if res.Normalized != nil {
		lifecycle, _ = res.Normalized["lifecycleState"].(string)
		health, _ = res.Normalized["healthState"].(string)
	}
	return lifecycle, health
}

// seedLabels mirrors inventory.adapterLabels (keep in step).
func seedLabels(res contract.DiscoveredResource) contract.JSONMap {
	labels := make(contract.JSONMap, len(res.Raw))
	for k, v := range res.Raw {
		if k == seedAbsenceLabelKey {
			continue
		}
		labels[k] = v
	}
	return labels
}

// seedHash mirrors inventory.observationHash (keep in step): the canonical
// payload bundle, re-marshalled so map key order is Go-stable.
func seedHash(res contract.DiscoveredResource) string {
	payload := contract.JSONMap{
		"urn":        res.ExternalURN,
		"kind":       res.Kind,
		"subtype":    res.Subtype,
		"normalized": res.Normalized,
		"raw":        res.Raw,
	}
	b, err := json.Marshal(payload)
	if err != nil {
		return ""
	}
	sum := sha256.Sum256(b)
	return hex.EncodeToString(sum[:])
}

// seedQuote renders a Go string as a SQL single-quoted literal (doubled
// quotes); the normalizer payloads carry no control characters, but the guard
// is cheap and keeps the emitted SQL total.
func seedQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", "''") + "'"
}

func seedFloatPtr(v float64) *float64 { return &v }
func seedIntPtr(v int) *int           { return &v }
